// Code generated by cotorp. DO NOT EDIT.
// source: editions/editions.proto

package editionspb

import (
	"bytes"
	"cmp"
	"encoding/binary"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"io"
	"math"
	"math/big"
	"math/bits"
	"slices"
	"strconv"
	"strings"
	"unicode/utf8"
)

const (
	editionsWireVarint        = 0
	editionsWireFixed64       = 1
	editionsWireBytes         = 2
	editionsWireStartGroup    = 3
	editionsWireEndGroup      = 4
	editionsWireFixed32       = 5
	editionsTagTypeBits       = 3
	editionsTagTypeMask       = 1<<3 - 1
	editionsMaxFieldNumber    = 1<<29 - 1
	editionsMapKeyField       = 1
	editionsMapValueField     = 2
	editionsFixed32Size       = 4
	editionsFixed64Size       = 8
	editionsVarintPayloadBits = 7
	editionsVarintContBit     = 0x80
	editionsMaxDepth          = 10000
	editionsMaxJSONExponent   = 100
	editionsE1                = "proto: field cotorp.test.editions.Features.verified contains invalid UTF-8"
	editionsE2                = "proto: field cotorp.test.editions.Features.with_default contains invalid UTF-8"
	editionsE3                = "proto: field cotorp.test.editions.Features.VerifiedMapEntry.value contains invalid UTF-8"
	editionsE4                = "proto: field cotorp.test.editions.Features.VerifiedMapEntry.key contains invalid UTF-8"
	editionsE5                = "proto: cannot parse invalid wire-format data"
	editionsE6                = "proto: field cotorp.test.editions.ImplicitMessage.b contains invalid UTF-8"
	editionsE7                = "duplicate field "
	editionsE8                = "null is not allowed in repeated fields or map values"
)

type OpenEnum int32

const (
	OpenEnum_OPEN_ZERO OpenEnum = 0
	OpenEnum_OPEN_ONE  OpenEnum = 1
)

// OpenEnum_name maps OpenEnum numbers to their names, and OpenEnum_value the reverse.
var OpenEnum_name = map[int32]string{
	0: "OPEN_ZERO",
	1: "OPEN_ONE",
}
var OpenEnum_value = editionsInvert(OpenEnum_name)

// Enum returns a pointer to a copy of x.
func (x OpenEnum) Enum() *OpenEnum { return &x }

// String returns the name of x, or its number if it has no name.
func (x OpenEnum) String() string { return editionsEnumString(OpenEnum_name, int32(x)) }

// IsValid reports whether x is a declared value of OpenEnum.
func (x OpenEnum) IsValid() bool { return x >= 0 && x <= 1 }

type ClosedEnum int32

const (
	ClosedEnum_CLOSED_ONE ClosedEnum = 1
	ClosedEnum_CLOSED_TWO ClosedEnum = 2
)

// ClosedEnum_name maps ClosedEnum numbers to their names, and ClosedEnum_value the reverse.
var ClosedEnum_name = map[int32]string{
	1: "CLOSED_ONE",
	2: "CLOSED_TWO",
}
var ClosedEnum_value = editionsInvert(ClosedEnum_name)

// Enum returns a pointer to a copy of x.
func (x ClosedEnum) Enum() *ClosedEnum { return &x }

// String returns the name of x, or its number if it has no name.
func (x ClosedEnum) String() string { return editionsEnumString(ClosedEnum_name, int32(x)) }

// IsValid reports whether x is a declared value of ClosedEnum.
func (x ClosedEnum) IsValid() bool { return x >= 1 && x <= 2 }

type Features struct {
	ExplicitInt    *int32
	ImplicitInt    int32
	RequiredInt    *int32
	PackedInts     []int32
	ExpandedInts   []int32
	Verified       *string
	Unverified     *string
	Delimited      *Features_Child
	DelimitedList  []*Features_Child
	LengthPrefixed *Features_Child
	OpenEnum       *OpenEnum
	ClosedEnum     *ClosedEnum
	WithDefault    *string
	VerifiedMap    map[string]string
	UnverifiedMap  map[string]string

	u []byte
}

// Default values for Features fields.
const (
	Default_Features_WithDefault string = "dflt"
)

// Reset clears all fields of m.
func (m *Features) Reset()                              { *m = Features{} }
func (m *Features) z() *Features                        { return editionsIf(m == nil, &editionsZFeatures, m) }
func (m *Features) GetExplicitInt() int32               { return editionsDeref(m.z().ExplicitInt, 0) }
func (m *Features) GetImplicitInt() int32               { return m.z().ImplicitInt }
func (m *Features) GetRequiredInt() int32               { return editionsDeref(m.z().RequiredInt, 0) }
func (m *Features) GetPackedInts() []int32              { return m.z().PackedInts }
func (m *Features) GetExpandedInts() []int32            { return m.z().ExpandedInts }
func (m *Features) GetVerified() string                 { return editionsDeref(m.z().Verified, "") }
func (m *Features) GetUnverified() string               { return editionsDeref(m.z().Unverified, "") }
func (m *Features) GetDelimited() *Features_Child       { return m.z().Delimited }
func (m *Features) GetDelimitedList() []*Features_Child { return m.z().DelimitedList }
func (m *Features) GetLengthPrefixed() *Features_Child  { return m.z().LengthPrefixed }
func (m *Features) GetOpenEnum() OpenEnum               { return editionsDeref(m.z().OpenEnum, OpenEnum_OPEN_ZERO) }
func (m *Features) GetClosedEnum() ClosedEnum {
	return editionsDeref(m.z().ClosedEnum, ClosedEnum_CLOSED_ONE)
}
func (m *Features) GetWithDefault() string {
	return editionsDeref(m.z().WithDefault, Default_Features_WithDefault)
}
func (m *Features) GetVerifiedMap() map[string]string   { return m.z().VerifiedMap }
func (m *Features) GetUnverifiedMap() map[string]string { return m.z().UnverifiedMap }

// ProtoUnknownFields returns the raw bytes of fields that were not recognized when m was decoded.
func (m *Features) ProtoUnknownFields() []byte { return m.z().u }

// ProtoSize returns the size of the wire-format encoding of m.
func (m *Features) ProtoSize() (n int) {
	m = m.z()
	n += editionsSizeOpt(1, m.ExplicitInt, editionsVarintLen)
	n += editionsSizeVarint(1, uint64(int64(m.ImplicitInt)))
	n += editionsSizeOpt(1, m.RequiredInt, editionsVarintLen)
	n += editionsSizePacked(1, m.PackedInts, editionsVarintLen)
	n += editionsSizeEach(1, m.ExpandedInts, editionsVarintLen)
	n += editionsSizeOpt(1, m.Verified, editionsBytesLen)
	n += editionsSizeOpt(1, m.Unverified, editionsBytesLen)
	if m.Delimited != nil {
		n += 2 + m.Delimited.ProtoSize()
	}
	for _, v := range m.DelimitedList {
		n += 2 + v.ProtoSize()
	}
	n += editionsSizeMsg(1, m.LengthPrefixed, func(v *Features_Child) int { return v.ProtoSize() })
	n += editionsSizeOpt(1, m.OpenEnum, editionsVarintLen)
	n += editionsSizeOpt(1, m.ClosedEnum, editionsVarintLen)
	n += editionsSizeOpt(1, m.WithDefault, editionsBytesLen)
	for k, v := range m.VerifiedMap {
		n += 1 + editionsSizeLen(1+editionsSizeLen(len(k))+1+editionsSizeLen(len(v)))
	}
	for k, v := range m.UnverifiedMap {
		n += 1 + editionsSizeLen(1+editionsSizeLen(len(k))+1+editionsSizeLen(len(v)))
	}
	return n + len(m.u)
}

// MarshalBinary returns the wire-format encoding of m.
func (m *Features) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *Features) AppendBinary(b []byte) ([]byte, error) {
	if err := m.ProtoCheckInitialized(); err != nil {
		return b, err
	}
	return editionsAppendBinary(b, m.ProtoSize(), m.ProtoMarshalToSizedBuffer)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must hold m.ProtoSize() bytes, and returns the count written, without checking required fields.
func (m *Features) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	m = m.z()
	i := editionsCopyUnknown(b, len(b), m.u)
	if err := editionsCheckUTF8(m.GetWithDefault(), editionsE2, editionsCheckUTF8(m.GetVerified(), editionsE1, nil)); err != nil {
		return 0, err
	}
	if len(m.UnverifiedMap) > 0 {
		for _, k := range slices.Backward(editionsSortedKeys(m.UnverifiedMap, make([]string, 0, len(m.UnverifiedMap)))) {
			v := m.UnverifiedMap[k]
			start := i
			i = editionsPutVarint(b, editionsPutVarint(b, i-copy(b[i-len(v):], v), uint64(len(v))), editionsMapValueField<<editionsTagTypeBits|editionsWireBytes)
			i = editionsPutVarint(b, editionsPutVarint(b, i-copy(b[i-len(k):], k), uint64(len(k))), editionsMapKeyField<<editionsTagTypeBits|editionsWireBytes)
			i = editionsPutVarint(b, editionsPutVarint(b, i, uint64(start-i)), 15<<editionsTagTypeBits|editionsWireBytes)
		}
	}
	if len(m.VerifiedMap) > 0 {
		for _, k := range slices.Backward(editionsSortedKeys(m.VerifiedMap, make([]string, 0, len(m.VerifiedMap)))) {
			v := m.VerifiedMap[k]
			start := i
			if !utf8.ValidString(v) {
				return 0, errors.New(editionsE3)
			}
			i = editionsPutVarint(b, editionsPutVarint(b, i-copy(b[i-len(v):], v), uint64(len(v))), editionsMapValueField<<editionsTagTypeBits|editionsWireBytes)
			if !utf8.ValidString(k) {
				return 0, errors.New(editionsE4)
			}
			i = editionsPutVarint(b, editionsPutVarint(b, i-copy(b[i-len(k):], k), uint64(len(k))), editionsMapKeyField<<editionsTagTypeBits|editionsWireBytes)
			i = editionsPutVarint(b, editionsPutVarint(b, i, uint64(start-i)), 14<<editionsTagTypeBits|editionsWireBytes)
		}
	}
	if m.WithDefault != nil {
		i = editionsPutVarint(b, editionsPutVarint(b, i-copy(b[i-len((*m.WithDefault)):], (*m.WithDefault)), uint64(len((*m.WithDefault)))), 13<<editionsTagTypeBits|editionsWireBytes)
	}
	if m.ClosedEnum != nil {
		i = editionsPutVarint(b, editionsPutVarint(b, i, uint64(int64((*m.ClosedEnum)))), 12<<editionsTagTypeBits|editionsWireVarint)
	}
	if m.OpenEnum != nil {
		i = editionsPutVarint(b, editionsPutVarint(b, i, uint64(int64((*m.OpenEnum)))), 11<<editionsTagTypeBits|editionsWireVarint)
	}
	if m.LengthPrefixed != nil {
		n, err := m.LengthPrefixed.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = editionsPutVarint(b, editionsPutVarint(b, i-n, uint64(n)), 10<<editionsTagTypeBits|editionsWireBytes)
	}
	for _, v := range slices.Backward(m.DelimitedList) {
		i = editionsPutVarint(b, i, 9<<editionsTagTypeBits|editionsWireEndGroup)
		n, err := v.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = editionsPutVarint(b, i-n, 9<<editionsTagTypeBits|editionsWireStartGroup)
	}
	if m.Delimited != nil {
		i = editionsPutVarint(b, i, 8<<editionsTagTypeBits|editionsWireEndGroup)
		n, err := m.Delimited.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = editionsPutVarint(b, i-n, 8<<editionsTagTypeBits|editionsWireStartGroup)
	}
	if m.Unverified != nil {
		i = editionsPutVarint(b, editionsPutVarint(b, i-copy(b[i-len((*m.Unverified)):], (*m.Unverified)), uint64(len((*m.Unverified)))), 7<<editionsTagTypeBits|editionsWireBytes)
	}
	if m.Verified != nil {
		i = editionsPutVarint(b, editionsPutVarint(b, i-copy(b[i-len((*m.Verified)):], (*m.Verified)), uint64(len((*m.Verified)))), 6<<editionsTagTypeBits|editionsWireBytes)
	}
	for _, v := range slices.Backward(m.ExpandedInts) {
		i = editionsPutVarint(b, editionsPutVarint(b, i, uint64(int64(v))), 5<<editionsTagTypeBits|editionsWireVarint)
	}
	if len(m.PackedInts) > 0 {
		start := i
		for _, v := range slices.Backward(m.PackedInts) {
			i = editionsPutVarint(b, i, uint64(int64(v)))
		}
		i = editionsPutVarint(b, editionsPutVarint(b, i, uint64(start-i)), 4<<editionsTagTypeBits|editionsWireBytes)
	}
	if m.RequiredInt != nil {
		i = editionsPutVarint(b, editionsPutVarint(b, i, uint64(int64((*m.RequiredInt)))), 3<<editionsTagTypeBits|editionsWireVarint)
	}
	i = editionsPutVarintField(b, i, uint64(int64(m.ImplicitInt)), 2<<editionsTagTypeBits|editionsWireVarint)
	if m.ExplicitInt != nil {
		i = editionsPutVarint(b, editionsPutVarint(b, i, uint64(int64((*m.ExplicitInt)))), 1<<editionsTagTypeBits|editionsWireVarint)
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the wire-format message in b.
func (m *Features) UnmarshalBinary(b []byte) error {
	*m = Features{}
	return cmp.Or(m.ProtoMergeDepth(b, 0), m.ProtoCheckInitialized())
}

// ProtoMerge decodes the wire-format message in b and merges it into m, without checking required fields.
func (m *Features) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *Features) ProtoMergeDepth(b []byte, depth int) error {
	var x, err = []byte(nil), editionsDepth(depth)
	for t, n := binary.Uvarint(b); n > 0 && err == nil; t, n = binary.Uvarint(b) {
		b = b[n:]
		switch t {
		case 1<<editionsTagTypeBits | editionsWireVarint:
			n = editionsVarint(b, editionsNew(&m.ExplicitInt))
		case 2<<editionsTagTypeBits | editionsWireVarint:
			n = editionsVarint(b, &m.ImplicitInt)
		case 3<<editionsTagTypeBits | editionsWireVarint:
			n = editionsVarint(b, editionsNew(&m.RequiredInt))
		case 4<<editionsTagTypeBits | editionsWireBytes:
			n = editionsPackedVarint(b, &m.PackedInts)
		case 4<<editionsTagTypeBits | editionsWireVarint:
			n = editionsVarint(b, editionsGrow(&m.PackedInts))
		case 5<<editionsTagTypeBits | editionsWireBytes:
			n = editionsPackedVarint(b, &m.ExpandedInts)
		case 5<<editionsTagTypeBits | editionsWireVarint:
			n = editionsVarint(b, editionsGrow(&m.ExpandedInts))
		case 6<<editionsTagTypeBits | editionsWireBytes:
			n, err = editionsString(b, editionsNew(&m.Verified), editionsE1)
		case 7<<editionsTagTypeBits | editionsWireBytes:
			n, err = editionsString(b, editionsNew(&m.Unverified), "")
		case 8<<editionsTagTypeBits | editionsWireStartGroup:
			x, n, err = editionsGroup(b, 8, depth)
			err = cmp.Or(err, editionsAlloc(&m.Delimited).ProtoMergeDepth(x, depth+1))
		case 9<<editionsTagTypeBits | editionsWireStartGroup:
			x, n, err = editionsGroup(b, 9, depth)
			err = cmp.Or(err, editionsAlloc(editionsGrow(&m.DelimitedList)).ProtoMergeDepth(x, depth+1))
		case 10<<editionsTagTypeBits | editionsWireBytes:
			x, n = editionsReadBytes(b)
			err = editionsAlloc(&m.LengthPrefixed).ProtoMergeDepth(x, depth+1)
		case 11<<editionsTagTypeBits | editionsWireVarint:
			n = editionsVarint(b, editionsNew(&m.OpenEnum))
		case 12<<editionsTagTypeBits | editionsWireVarint:
			n = editionsClosedEnum(b, &m.u, 12<<editionsTagTypeBits|editionsWireVarint, func(e ClosedEnum) { m.ClosedEnum = new(e) })
		case 13<<editionsTagTypeBits | editionsWireBytes:
			n, err = editionsString(b, editionsNew(&m.WithDefault), editionsE2)
		case 14<<editionsTagTypeBits | editionsWireBytes:
			x, n = editionsReadBytes(b)
			mk, mv := "", ""
			for t, k := binary.Uvarint(x); k > 0; t, k = binary.Uvarint(x) {
				x = x[k:]
				switch t {
				case editionsMapKeyField<<editionsTagTypeBits | editionsWireBytes:
					k, err = editionsString(x, &mk, editionsE4)
				case editionsMapValueField<<editionsTagTypeBits | editionsWireBytes:
					k, err = editionsString(x, &mv, editionsE3)
				default:
					k, err = editionsSkipField(x, t, depth)
				}
				if k <= 0 || err != nil {
					return cmp.Or(err, errors.New(editionsE5))
				}
				x = x[k:]
			}
			editionsMapSet(&m.VerifiedMap, mk, mv)
			err = editionsEnd(x, err)
		case 15<<editionsTagTypeBits | editionsWireBytes:
			x, n = editionsReadBytes(b)
			mk, mv := "", ""
			for t, k := binary.Uvarint(x); k > 0; t, k = binary.Uvarint(x) {
				x = x[k:]
				switch t {
				case editionsMapKeyField<<editionsTagTypeBits | editionsWireBytes:
					k, err = editionsString(x, &mk, "")
				case editionsMapValueField<<editionsTagTypeBits | editionsWireBytes:
					k, err = editionsString(x, &mv, "")
				default:
					k, err = editionsSkipField(x, t, depth)
				}
				if k <= 0 || err != nil {
					return cmp.Or(err, errors.New(editionsE5))
				}
				x = x[k:]
			}
			editionsMapSet(&m.UnverifiedMap, mk, mv)
			err = editionsEnd(x, err)
		default:
			n, err = editionsUnknown(b, t, depth, &m.u)
		}
		if n <= 0 || err != nil {
			return cmp.Or(err, errors.New(editionsE5))
		}
		b = b[n:]
	}
	return editionsEnd(b, err)
}

// ProtoCheckInitialized returns an error if a required field of m or of a message in m is not set.
func (m *Features) ProtoCheckInitialized() error {
	if m == nil {
		return nil
	}
	if m.RequiredInt == nil {
		return errors.New("proto: required field cotorp.test.editions.Features.required_int not set")
	}
	return nil
}

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *Features) MarshalJSON() ([]byte, error) {
	if err := m.ProtoCheckInitialized(); err != nil {
		return nil, err
	}
	return m.ProtoAppendJSON(nil)
}

// MarshalJSONTo writes the ProtoJSON encoding of m to e, implementing json.MarshalerTo from encoding/json/v2.
func (m *Features) MarshalJSONTo(e *jsontext.Encoder) error {
	if err := m.ProtoCheckInitialized(); err != nil {
		return err
	}
	return editionsMarshalTo(e, m.ProtoAppendJSON)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b, without checking required fields.
func (m *Features) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	m, start := m.z(), len(b)
	if m.ExplicitInt != nil {
		b = strconv.AppendInt(append(b, ",\"explicitInt\":"...), int64((*m.ExplicitInt)), 10)
	}
	if m.ImplicitInt != 0 {
		b = strconv.AppendInt(append(b, ",\"implicitInt\":"...), int64(m.ImplicitInt), 10)
	}
	if m.RequiredInt != nil {
		b = strconv.AppendInt(append(b, ",\"requiredInt\":"...), int64((*m.RequiredInt)), 10)
	}
	b, err = editionsAppendList(b, ",\"packedInts\":[", m.PackedInts, func(v int32, b []byte) ([]byte, error) { return strconv.AppendInt(b, int64(v), 10), nil }, err)
	b, err = editionsAppendList(b, ",\"expandedInts\":[", m.ExpandedInts, func(v int32, b []byte) ([]byte, error) { return strconv.AppendInt(b, int64(v), 10), nil }, err)
	if m.Verified != nil {
		b, err = editionsQuote(append(b, ",\"verified\":"...), (*m.Verified), err)
	}
	if m.Unverified != nil {
		b, err = editionsQuote(append(b, ",\"unverified\":"...), (*m.Unverified), err)
	}
	b, err = editionsAppendMsg(b, ",\"delimited\":", m.Delimited, func(v *Features_Child, b []byte) ([]byte, error) { return v.ProtoAppendJSON(b) }, err)
	b, err = editionsAppendList(b, ",\"delimitedList\":[", m.DelimitedList, (*Features_Child).ProtoAppendJSON, err)
	b, err = editionsAppendMsg(b, ",\"lengthPrefixed\":", m.LengthPrefixed, func(v *Features_Child, b []byte) ([]byte, error) { return v.ProtoAppendJSON(b) }, err)
	if m.OpenEnum != nil {
		b = editionsAppendEnum(append(b, ",\"openEnum\":"...), int32((*m.OpenEnum)), OpenEnum_name)
	}
	if m.ClosedEnum != nil {
		b = editionsAppendEnum(append(b, ",\"closedEnum\":"...), int32((*m.ClosedEnum)), ClosedEnum_name)
	}
	if m.WithDefault != nil {
		b, err = editionsQuote(append(b, ",\"withDefault\":"...), (*m.WithDefault), err)
	}
	b, err = editionsAppendMap(b, ",\"verifiedMap\":{", m.VerifiedMap, func(k string, b []byte) ([]byte, error) { return jsontext.AppendQuote(b, k) }, func(v string, b []byte) ([]byte, error) { return jsontext.AppendQuote(b, v) }, err)
	b, err = editionsAppendMap(b, ",\"unverifiedMap\":{", m.UnverifiedMap, func(k string, b []byte) ([]byte, error) { return jsontext.AppendQuote(b, k) }, func(v string, b []byte) ([]byte, error) { return jsontext.AppendQuote(b, v) }, err)
	return editionsCloseObject(b, start), err
}

// UnmarshalJSON replaces the contents of m with the ProtoJSON value in b.
func (m *Features) UnmarshalJSON(b []byte) error {
	*m = Features{}
	return cmp.Or(m.ProtoMergeJSON(b), m.ProtoCheckInitialized())
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m, without checking required fields.
func (m *Features) ProtoMergeJSON(b []byte) error {
	return editionsMergeJSON(b, "cotorp.test.editions.Features", m.ProtoMergeJSONFrom)
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value read from d, implementing json.UnmarshalerFrom from encoding/json/v2.
func (m *Features) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	*m = Features{}
	return cmp.Or(editionsMergeFrom(d, m.ProtoMergeJSONFrom), m.ProtoCheckInitialized())
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it into m, without checking required fields; d should reject invalid UTF-8, as jsontext decoders do by default.
func (m *Features) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	var seen [15]bool
	for kt, err := editionsOpenObject(d, "cotorp.test.editions.Features"); kt.Kind() != jsontext.KindEndObject; kt, err = editionsNextKey(d, err) {
		if err != nil {
			return err
		}
		switch key := kt.String(); key {
		case "explicitInt", "explicit_int":
			err = editionsOptField(d, &seen[0], key, "cotorp.test.editions.Features", &m.ExplicitInt, editionsJSONInt)
		case "implicitInt", "implicit_int":
			err = editionsField(d, &seen[1], key, "cotorp.test.editions.Features", &m.ImplicitInt, editionsJSONInt)
		case "requiredInt", "required_int":
			err = editionsOptField(d, &seen[2], key, "cotorp.test.editions.Features", &m.RequiredInt, editionsJSONInt)
		case "packedInts", "packed_ints":
			err = editionsRepField(d, &seen[3], key, "cotorp.test.editions.Features", &m.PackedInts, false, editionsJSONInt)
		case "expandedInts", "expanded_ints":
			err = editionsRepField(d, &seen[4], key, "cotorp.test.editions.Features", &m.ExpandedInts, false, editionsJSONInt)
		case "verified":
			err = editionsOptField(d, &seen[5], key, "cotorp.test.editions.Features", &m.Verified, editionsJSONString)
		case "unverified":
			err = editionsOptField(d, &seen[6], key, "cotorp.test.editions.Features", &m.Unverified, editionsJSONString)
		case "delimited":
			err = editionsField(d, &seen[7], key, "cotorp.test.editions.Features", &m.Delimited, editionsJSONMsg)
		case "delimitedList", "delimited_list":
			err = editionsRepField(d, &seen[8], key, "cotorp.test.editions.Features", &m.DelimitedList, false, editionsJSONMsg)
		case "lengthPrefixed", "length_prefixed":
			err = editionsField(d, &seen[9], key, "cotorp.test.editions.Features", &m.LengthPrefixed, editionsJSONMsg)
		case "openEnum", "open_enum":
			err = editionsOptField(d, &seen[10], key, "cotorp.test.editions.Features", &m.OpenEnum, editionsJOpenEnum)
		case "closedEnum", "closed_enum":
			err = editionsOptField(d, &seen[11], key, "cotorp.test.editions.Features", &m.ClosedEnum, editionsJClosedEnum)
		case "withDefault", "with_default":
			err = editionsOptField(d, &seen[12], key, "cotorp.test.editions.Features", &m.WithDefault, editionsJSONString)
		case "verifiedMap", "verified_map":
			err = editionsMapField(d, &seen[13], key, "cotorp.test.editions.Features", "verified_map", &m.VerifiedMap, false, editionsStringKey, editionsJSONString)
		case "unverifiedMap", "unverified_map":
			err = editionsMapField(d, &seen[14], key, "cotorp.test.editions.Features", "unverified_map", &m.UnverifiedMap, false, editionsStringKey, editionsJSONString)
		default:
			return errors.New("proto: cotorp.test.editions.Features: unknown field " + strconv.Quote(key))
		}
	}
	return nil
}

func editionsJOpenEnum(d *jsontext.Decoder, p *OpenEnum, name string) error {
	return editionsJSONEnum(d, p, OpenEnum_value, name, "cotorp.test.editions.OpenEnum", false)
}

func editionsJClosedEnum(d *jsontext.Decoder, p *ClosedEnum, name string) error {
	return editionsJSONEnum(d, p, ClosedEnum_value, name, "cotorp.test.editions.ClosedEnum", false)
}

type Features_Child struct {
	X *int32

	u []byte
}

// Reset clears all fields of m.
func (m *Features_Child) Reset() { *m = Features_Child{} }
func (m *Features_Child) z() *Features_Child {
	return editionsIf(m == nil, &editionsZFeatures_Child, m)
}
func (m *Features_Child) GetX() int32 { return editionsDeref(m.z().X, 0) }

// ProtoUnknownFields returns the raw bytes of fields that were not recognized when m was decoded.
func (m *Features_Child) ProtoUnknownFields() []byte { return m.z().u }

// ProtoSize returns the size of the wire-format encoding of m.
func (m *Features_Child) ProtoSize() (n int) {
	m = m.z()
	n += editionsSizeOpt(1, m.X, editionsVarintLen)
	return n + len(m.u)
}

// MarshalBinary returns the wire-format encoding of m.
func (m *Features_Child) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *Features_Child) AppendBinary(b []byte) ([]byte, error) {
	return editionsAppendBinary(b, m.ProtoSize(), m.ProtoMarshalToSizedBuffer)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must hold m.ProtoSize() bytes, and returns the count written, without checking required fields.
func (m *Features_Child) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	m = m.z()
	i := editionsCopyUnknown(b, len(b), m.u)
	if m.X != nil {
		i = editionsPutVarint(b, editionsPutVarint(b, i, uint64(int64((*m.X)))), 1<<editionsTagTypeBits|editionsWireVarint)
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the wire-format message in b.
func (m *Features_Child) UnmarshalBinary(b []byte) error {
	*m = Features_Child{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m, without checking required fields.
func (m *Features_Child) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *Features_Child) ProtoMergeDepth(b []byte, depth int) error {
	err := editionsDepth(depth)
	for t, n := binary.Uvarint(b); n > 0 && err == nil; t, n = binary.Uvarint(b) {
		b = b[n:]
		switch t {
		case 1<<editionsTagTypeBits | editionsWireVarint:
			n = editionsVarint(b, editionsNew(&m.X))
		default:
			n, err = editionsUnknown(b, t, depth, &m.u)
		}
		if n <= 0 || err != nil {
			return cmp.Or(err, errors.New(editionsE5))
		}
		b = b[n:]
	}
	return editionsEnd(b, err)
}

// ProtoCheckInitialized returns an error if a required field of m or of a message in m is not set.
func (m *Features_Child) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *Features_Child) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e, implementing json.MarshalerTo from encoding/json/v2.
func (m *Features_Child) MarshalJSONTo(e *jsontext.Encoder) error {
	return editionsMarshalTo(e, m.ProtoAppendJSON)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b, without checking required fields.
func (m *Features_Child) ProtoAppendJSON(b []byte) ([]byte, error) {
	m, start := m.z(), len(b)
	if m.X != nil {
		b = strconv.AppendInt(append(b, ",\"x\":"...), int64((*m.X)), 10)
	}
	return editionsCloseObject(b, start), nil
}

// UnmarshalJSON replaces the contents of m with the ProtoJSON value in b.
func (m *Features_Child) UnmarshalJSON(b []byte) error {
	*m = Features_Child{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m, without checking required fields.
func (m *Features_Child) ProtoMergeJSON(b []byte) error {
	return editionsMergeJSON(b, "cotorp.test.editions.Features.Child", m.ProtoMergeJSONFrom)
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value read from d, implementing json.UnmarshalerFrom from encoding/json/v2.
func (m *Features_Child) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	*m = Features_Child{}
	return editionsMergeFrom(d, m.ProtoMergeJSONFrom)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it into m, without checking required fields; d should reject invalid UTF-8, as jsontext decoders do by default.
func (m *Features_Child) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	var seen [1]bool
	for kt, err := editionsOpenObject(d, "cotorp.test.editions.Features.Child"); kt.Kind() != jsontext.KindEndObject; kt, err = editionsNextKey(d, err) {
		if err != nil {
			return err
		}
		switch key := kt.String(); key {
		case "x":
			err = editionsOptField(d, &seen[0], key, "cotorp.test.editions.Features.Child", &m.X, editionsJSONInt)
		default:
			return errors.New("proto: cotorp.test.editions.Features.Child: unknown field " + strconv.Quote(key))
		}
	}
	return nil
}

type ImplicitMessage struct {
	A int32
	B string
	C *Features_Child

	u []byte
}

// Reset clears all fields of m.
func (m *ImplicitMessage) Reset() { *m = ImplicitMessage{} }
func (m *ImplicitMessage) z() *ImplicitMessage {
	return editionsIf(m == nil, &editionsZImplicitMessage, m)
}
func (m *ImplicitMessage) GetA() int32           { return m.z().A }
func (m *ImplicitMessage) GetB() string          { return m.z().B }
func (m *ImplicitMessage) GetC() *Features_Child { return m.z().C }

// ProtoUnknownFields returns the raw bytes of fields that were not recognized when m was decoded.
func (m *ImplicitMessage) ProtoUnknownFields() []byte { return m.z().u }

// ProtoSize returns the size of the wire-format encoding of m.
func (m *ImplicitMessage) ProtoSize() (n int) {
	m = m.z()
	n += editionsSizeVarint(1, uint64(int64(m.A)))
	n += editionsSizeLenField(1, len(m.B))
	n += editionsSizeMsg(1, m.C, func(v *Features_Child) int { return v.ProtoSize() })
	return n + len(m.u)
}

// MarshalBinary returns the wire-format encoding of m.
func (m *ImplicitMessage) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *ImplicitMessage) AppendBinary(b []byte) ([]byte, error) {
	return editionsAppendBinary(b, m.ProtoSize(), m.ProtoMarshalToSizedBuffer)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must hold m.ProtoSize() bytes, and returns the count written, without checking required fields.
func (m *ImplicitMessage) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	m = m.z()
	i := editionsCopyUnknown(b, len(b), m.u)
	if err := editionsCheckUTF8(m.B, editionsE6, nil); err != nil {
		return 0, err
	}
	if m.C != nil {
		n, err := m.C.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = editionsPutVarint(b, editionsPutVarint(b, i-n, uint64(n)), 3<<editionsTagTypeBits|editionsWireBytes)
	}
	i = editionsPutStringField(b, i, m.B, 2<<editionsTagTypeBits|editionsWireBytes)
	i = editionsPutVarintField(b, i, uint64(int64(m.A)), 1<<editionsTagTypeBits|editionsWireVarint)
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the wire-format message in b.
func (m *ImplicitMessage) UnmarshalBinary(b []byte) error {
	*m = ImplicitMessage{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m, without checking required fields.
func (m *ImplicitMessage) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *ImplicitMessage) ProtoMergeDepth(b []byte, depth int) error {
	var x, err = []byte(nil), editionsDepth(depth)
	for t, n := binary.Uvarint(b); n > 0 && err == nil; t, n = binary.Uvarint(b) {
		b = b[n:]
		switch t {
		case 1<<editionsTagTypeBits | editionsWireVarint:
			n = editionsVarint(b, &m.A)
		case 2<<editionsTagTypeBits | editionsWireBytes:
			n, err = editionsString(b, &m.B, editionsE6)
		case 3<<editionsTagTypeBits | editionsWireBytes:
			x, n = editionsReadBytes(b)
			err = editionsAlloc(&m.C).ProtoMergeDepth(x, depth+1)
		default:
			n, err = editionsUnknown(b, t, depth, &m.u)
		}
		if n <= 0 || err != nil {
			return cmp.Or(err, errors.New(editionsE5))
		}
		b = b[n:]
	}
	return editionsEnd(b, err)
}

// ProtoCheckInitialized returns an error if a required field of m or of a message in m is not set.
func (m *ImplicitMessage) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *ImplicitMessage) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e, implementing json.MarshalerTo from encoding/json/v2.
func (m *ImplicitMessage) MarshalJSONTo(e *jsontext.Encoder) error {
	return editionsMarshalTo(e, m.ProtoAppendJSON)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b, without checking required fields.
func (m *ImplicitMessage) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	m, start := m.z(), len(b)
	if m.A != 0 {
		b = strconv.AppendInt(append(b, ",\"a\":"...), int64(m.A), 10)
	}
	if len(m.B) > 0 {
		b, err = editionsQuote(append(b, ",\"b\":"...), m.B, err)
	}
	b, err = editionsAppendMsg(b, ",\"c\":", m.C, func(v *Features_Child, b []byte) ([]byte, error) { return v.ProtoAppendJSON(b) }, err)
	return editionsCloseObject(b, start), err
}

// UnmarshalJSON replaces the contents of m with the ProtoJSON value in b.
func (m *ImplicitMessage) UnmarshalJSON(b []byte) error {
	*m = ImplicitMessage{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m, without checking required fields.
func (m *ImplicitMessage) ProtoMergeJSON(b []byte) error {
	return editionsMergeJSON(b, "cotorp.test.editions.ImplicitMessage", m.ProtoMergeJSONFrom)
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value read from d, implementing json.UnmarshalerFrom from encoding/json/v2.
func (m *ImplicitMessage) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	*m = ImplicitMessage{}
	return editionsMergeFrom(d, m.ProtoMergeJSONFrom)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it into m, without checking required fields; d should reject invalid UTF-8, as jsontext decoders do by default.
func (m *ImplicitMessage) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	var seen [3]bool
	for kt, err := editionsOpenObject(d, "cotorp.test.editions.ImplicitMessage"); kt.Kind() != jsontext.KindEndObject; kt, err = editionsNextKey(d, err) {
		if err != nil {
			return err
		}
		switch key := kt.String(); key {
		case "a":
			err = editionsField(d, &seen[0], key, "cotorp.test.editions.ImplicitMessage", &m.A, editionsJSONInt)
		case "b":
			err = editionsField(d, &seen[1], key, "cotorp.test.editions.ImplicitMessage", &m.B, editionsJSONString)
		case "c":
			err = editionsField(d, &seen[2], key, "cotorp.test.editions.ImplicitMessage", &m.C, editionsJSONMsg)
		default:
			return errors.New("proto: cotorp.test.editions.ImplicitMessage: unknown field " + strconv.Quote(key))
		}
	}
	return nil
}

var (
	editionsZFeatures        Features
	editionsZFeatures_Child  Features_Child
	editionsZImplicitMessage ImplicitMessage
)

func editionsSizeLen(l int) int { return l + editionsVarintLen(l) }
func editionsSizeVarint(tag int, u uint64) int {
	return editionsIf(u == 0, 0, tag+editionsVarintLen(u))
}
func editionsSizeLenField(tag, l int) int { return editionsIf(l == 0, 0, tag+editionsSizeLen(l)) }
func editionsSizeMsg[T any](tag int, p *T, size func(*T) int) int {
	if p == nil {
		return 0
	}
	return tag + editionsSizeLen(size(p))
}
func editionsSizeOpt[T any](tag int, p *T, size func(T) int) int {
	if p == nil {
		return 0
	}
	return tag + size(*p)
}
func editionsSizePacked[T any](tag int, s []T, size func(T) int) int {
	if len(s) == 0 {
		return 0
	}
	l := 0
	for _, v := range s {
		l += size(v)
	}
	return tag + editionsSizeLen(l)
}
func editionsSizeEach[T any](tag int, s []T, size func(T) int) (n int) {
	for _, v := range s {
		n += tag + size(v)
	}
	return n
}
func editionsVarintLen[T ~int | ~int32 | ~int64 | ~uint32 | ~uint64](v T) int {
	return (bits.Len64(uint64(int64(v))|1) + editionsVarintPayloadBits - 1) / editionsVarintPayloadBits
}
func editionsBytesLen[T ~string | ~[]byte](v T) int { return editionsSizeLen(len(v)) }
func editionsCheckUTF8(s, msg string, err error) error {
	if len(s) > 0 && !utf8.ValidString(s) {
		return errors.New(msg)
	}
	return err
}
func editionsCopyUnknown(b []byte, i int, u []byte) int {
	if len(u) > 0 {
		i -= copy(b[i-len(u):], u)
	}
	return i
}
func editionsAppendBinary(b []byte, size int, marshal func([]byte) (int, error)) ([]byte, error) {
	b = slices.Grow(b, size)
	n, err := marshal(b[len(b) : len(b)+size])
	if err == nil && n != size {
		err = errors.New("proto: message size changed during marshal")
	}
	if err != nil {
		return b, err
	}
	return b[:len(b)+size], nil
}
func editionsPutVarint(b []byte, i int, u uint64) int {
	if u < editionsVarintContBit {
		b[i-1] = byte(u)
		return i - 1
	}
	i -= (bits.Len64(u|1) + editionsVarintPayloadBits - 1) / editionsVarintPayloadBits
	binary.PutUvarint(b[i:], u)
	return i
}
func editionsPutVarintField(b []byte, i int, u uint64, tag byte) int {
	if u == 0 {
		return i
	}
	i -= (bits.Len64(u|1)+editionsVarintPayloadBits-1)/editionsVarintPayloadBits + 1
	b[i] = tag
	p := i + 1
	for ; u >= editionsVarintContBit; u >>= editionsVarintPayloadBits {
		b[p] = byte(u) | editionsVarintContBit
		p++
	}
	b[p] = byte(u)
	return i
}
func editionsPutStringField(b []byte, i int, v string, tag byte) int {
	if len(v) == 0 {
		return i
	}
	i -= copy(b[i-len(v):], v)
	u := uint64(len(v))
	i -= (bits.Len64(u|1)+editionsVarintPayloadBits-1)/editionsVarintPayloadBits + 1
	b[i] = tag
	p := i + 1
	for ; u >= editionsVarintContBit; u >>= editionsVarintPayloadBits {
		b[p] = byte(u) | editionsVarintContBit
		p++
	}
	b[p] = byte(u)
	return i
}
func editionsSortedKeys[K cmp.Ordered, V any](m map[K]V, keys []K) []K {
	for k := range m {
		keys = append(keys, k)
	}
	slices.Sort(keys)
	return keys
}
func editionsIf[T any](c bool, a, b T) T {
	if c {
		return a
	}
	return b
}
func editionsDepth(depth int) error {
	if depth >= editionsMaxDepth {
		return errors.New("proto: exceeded maximum recursion depth")
	}
	return nil
}
func editionsReadBytes(b []byte) (v []byte, n int) {
	ln, k := binary.Uvarint(b)
	if k <= 0 || ln > uint64(len(b)-k) {
		return nil, -1
	}
	return b[k : k+int(ln)], k + int(ln)
}
func editionsSkipField(b []byte, t uint64, depth int) (int, error) {
	n, num := 0, t>>editionsTagTypeBits
	switch wt := t & editionsTagTypeMask; {
	case num == 0 || num > editionsMaxFieldNumber:
	case wt == editionsWireVarint:
		_, n = binary.Uvarint(b)
	case wt == editionsWireBytes:
		_, n = editionsReadBytes(b)
	case wt == editionsWireStartGroup:
		return editionsSkipGroup(b, int32(num), depth+1)
	case wt == editionsWireFixed64 || wt == editionsWireFixed32:
		n = editionsIf(wt == editionsWireFixed64, editionsFixed64Size, editionsFixed32Size)
		n = editionsIf(len(b) >= n, n, 0)
	}
	if n <= 0 {
		return 0, errors.New(editionsE5)
	}
	return n, nil
}
func editionsSkipGroup(b []byte, num int32, depth int) (int, error) {
	n, err := 0, editionsDepth(depth)
	for err == nil {
		t, k := binary.Uvarint(b[n:])
		if k <= 0 {
			return 0, errors.New(editionsE5)
		}
		if n += k; t == uint64(num)<<editionsTagTypeBits|editionsWireEndGroup {
			return n, nil
		}
		k, err = editionsSkipField(b[n:], t, depth)
		n += k
	}
	return 0, err
}
func editionsUnknown(b []byte, t uint64, depth int, unk *[]byte) (int, error) {
	n, err := editionsSkipField(b, t, depth)
	if err == nil {
		*unk = append(binary.AppendUvarint(*unk, t), b[:n]...)
	}
	return n, err
}
func editionsEnd(b []byte, err error) error {
	if err == nil && len(b) > 0 {
		return errors.New(editionsE5)
	}
	return err
}
func editionsVarint[T ~int | ~int32 | ~int64 | ~uint32 | ~uint64](b []byte, p *T) int {
	u, n := binary.Uvarint(b)
	*p = T(u)
	return n
}
func editionsString(b []byte, p *string, errUTF8 string) (int, error) {
	ln, k := binary.Uvarint(b)
	if k <= 0 || ln > uint64(len(b)-k) {
		return -1, nil
	}
	x := b[k : k+int(ln)]
	if errUTF8 != "" && !utf8.Valid(x) {
		return 0, errors.New(errUTF8)
	}
	*p = string(x)
	return k + int(ln), nil
}
func editionsPackedVarint[T ~int | ~int32 | ~int64 | ~uint32 | ~uint64](b []byte, s *[]T) int {
	x, n := editionsReadBytes(b)
	if n < 0 {
		return -1
	}
	for len(x) > 0 {
		u, k := binary.Uvarint(x)
		if k <= 0 {
			return -1
		}
		x, *s = x[k:], append(*s, T(u))
	}
	return n
}
func editionsClosedEnum[E interface {
	~int32
	IsValid() bool
}](b []byte, unk *[]byte, tag uint64, set func(E)) int {
	u, n := binary.Uvarint(b)
	if n <= 0 {
		return -1
	}
	if e := E(u); e.IsValid() {
		set(e)
	} else {
		*unk = append(binary.AppendUvarint(*unk, tag), b[:n]...)
	}
	return n
}
func editionsGroup(b []byte, num int32, depth int) ([]byte, int, error) {
	n, err := editionsSkipGroup(b, num, depth)
	if err != nil {
		return nil, 0, err
	}
	return b[:n-(bits.Len64(uint64(num)<<editionsTagTypeBits|editionsWireEndGroup|1)+editionsVarintPayloadBits-1)/editionsVarintPayloadBits], n, nil
}
func editionsNew[T any](p **T) *T   { *p = new(T); return *p }
func editionsGrow[T any](s *[]T) *T { var z T; *s = append(*s, z); return &(*s)[len(*s)-1] }
func editionsAlloc[T any](p **T) *T {
	if *p == nil {
		*p = new(T)
	}
	return *p
}
func editionsMapSet[K comparable, V any](m *map[K]V, k K, v V) {
	if *m == nil {
		*m = make(map[K]V)
	}
	(*m)[k] = v
}
func editionsInvert[K, V comparable](m map[K]V) map[V]K {
	r := make(map[V]K, len(m))
	for k, v := range m {
		r[v] = k
	}
	return r
}
func editionsEnumString(names map[int32]string, v int32) string {
	if s, ok := names[v]; ok {
		return s
	}
	return strconv.Itoa(int(v))
}
func editionsDeref[T any](p *T, def T) T {
	if p != nil {
		return *p
	}
	return def
}
func editionsMarshalTo(e *jsontext.Encoder, f func([]byte) ([]byte, error)) error {
	b, err := f(e.AvailableBuffer())
	if err != nil {
		return err
	}
	return e.WriteValue(b)
}
func editionsAppendEnum(b []byte, v int32, names map[int32]string) []byte {
	if s, ok := names[v]; ok {
		b = append(b, '"')
		b = append(b, s...)
		return append(b, '"')
	}
	return strconv.AppendInt(b, int64(v), 10)
}
func editionsQuote(b []byte, s string, err error) ([]byte, error) {
	if err != nil {
		return b, err
	}
	return jsontext.AppendQuote(b, s)
}
func editionsAppendMsg[T any](b []byte, lit string, p *T, f func(*T, []byte) ([]byte, error), err error) ([]byte, error) {
	if err != nil || p == nil {
		return b, err
	}
	return f(p, append(b, lit...))
}
func editionsAppendList[T any](b []byte, lit string, s []T, f func(T, []byte) ([]byte, error), err error) ([]byte, error) {
	if err != nil || len(s) == 0 {
		return b, err
	}
	b = append(b, lit...)
	for _, v := range s {
		if b, err = f(v, b); err != nil {
			return b, err
		}
		b = append(b, ',')
	}
	b[len(b)-1] = ']'
	return b, nil
}
func editionsAppendMap[K cmp.Ordered, V any](b []byte, lit string, m map[K]V, fk func(K, []byte) ([]byte, error), fv func(V, []byte) ([]byte, error), err error) ([]byte, error) {
	if err != nil || len(m) == 0 {
		return b, err
	}
	b = append(b, lit...)
	for _, k := range editionsSortedKeys(m, make([]K, 0, len(m))) {
		if b, err = fk(k, b); err != nil {
			return b, err
		}
		if b, err = fv(m[k], append(b, ':')); err != nil {
			return b, err
		}
		b = append(b, ',')
	}
	b[len(b)-1] = '}'
	return b, nil
}
func editionsCloseObject(b []byte, start int) []byte {
	if len(b) == start {
		return append(b, "{}"...)
	}
	b[start] = '{'
	return append(b, '}')
}
func editionsMergeJSON(b []byte, name string, merge func(*jsontext.Decoder) error) error {
	d := jsontext.NewDecoder(bytes.NewBuffer(b))
	if err := merge(d); err != nil {
		return err
	}
	if _, err := d.ReadToken(); err != io.EOF {
		return editionsJSONError(name, "unexpected data after JSON value")
	}
	return nil
}
func editionsMergeFrom(d *jsontext.Decoder, merge func(*jsontext.Decoder) error) error {
	d, err := editionsStrictDecoder(d)
	return cmp.Or(err, merge(d))
}
func editionsStrictDecoder(d *jsontext.Decoder) (*jsontext.Decoder, error) {
	if lax, _ := json.GetOption(d.Options(), jsontext.AllowInvalidUTF8); !lax {
		return d, nil
	}
	v, err := d.ReadValue()
	if err != nil {
		return d, err
	}
	return jsontext.NewDecoder(bytes.NewBuffer(v)), nil
}
func editionsExpectJSON(d *jsontext.Decoder, kind jsontext.Kind, name, what string) error {
	tok, err := d.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != kind {
		return editionsJSONError(name, "expected a JSON "+what)
	}
	return nil
}
func editionsOpenObject(d *jsontext.Decoder, name string) (jsontext.Token, error) {
	if d.PeekKind() == jsontext.KindNull {
		return jsontext.EndObject, d.SkipValue()
	}
	return editionsNextKey(d, editionsExpectJSON(d, jsontext.KindBeginObject, name, "object"))
}
func editionsNextKey(d *jsontext.Decoder, err error) (jsontext.Token, error) {
	if err != nil {
		return jsontext.Token{}, err
	}
	return d.ReadToken()
}
func editionsField[T any](d *jsontext.Decoder, seen *bool, key, name string, p *T, parse func(*jsontext.Decoder, *T, string) error) error {
	if *seen {
		return editionsJSONError(name, editionsE7+strconv.Quote(key))
	}
	*seen = true
	return parse(d, p, name)
}
func editionsOptField[T any](d *jsontext.Decoder, seen *bool, key, name string, p **T, parse func(*jsontext.Decoder, *T, string) error) error {
	if *seen {
		return editionsJSONError(name, editionsE7+strconv.Quote(key))
	}
	*seen = true
	if d.PeekKind() == jsontext.KindNull {
		return d.SkipValue()
	}
	return parse(d, editionsNew(p), name)
}
func editionsRepField[T any](d *jsontext.Decoder, seen *bool, key, name string, s *[]T, nullOK bool, parse func(*jsontext.Decoder, *T, string) error) error {
	if *seen {
		return editionsJSONError(name, editionsE7+strconv.Quote(key))
	}
	*seen = true
	if d.PeekKind() == jsontext.KindNull {
		return d.SkipValue()
	}
	return editionsJSONArray(d, s, name, nullOK, parse)
}
func editionsMapField[K comparable, V any](d *jsontext.Decoder, seen *bool, key, name, field string, m *map[K]V, nullOK bool, pk func(string, string, string) (K, error), pv func(*jsontext.Decoder, *V, string) error) error {
	if *seen {
		return editionsJSONError(name, editionsE7+strconv.Quote(key))
	}
	*seen = true
	if d.PeekKind() == jsontext.KindNull {
		return d.SkipValue()
	}
	return editionsJSONMap(d, m, name, field, nullOK, pk, pv)
}
func editionsJSONArray[T any](d *jsontext.Decoder, s *[]T, name string, nullOK bool, parse func(*jsontext.Decoder, *T, string) error) error {
	if err := editionsExpectJSON(d, jsontext.KindBeginArray, name, "array"); err != nil {
		return err
	}
	for d.PeekKind() != jsontext.KindEndArray {
		if !nullOK && d.PeekKind() == jsontext.KindNull {
			return editionsJSONError(name, editionsE8)
		}
		if err := parse(d, editionsGrow(s), name); err != nil {
			return err
		}
	}
	_, err := d.ReadToken()
	return err
}
func editionsJSONMap[K comparable, V any](d *jsontext.Decoder, m *map[K]V, name, field string, nullOK bool, pk func(string, string, string) (K, error), pv func(*jsontext.Decoder, *V, string) error) error {
	if err := editionsExpectJSON(d, jsontext.KindBeginObject, name, "object"); err != nil {
		return err
	}
	for d.PeekKind() != jsontext.KindEndObject {
		kt, err := d.ReadToken()
		if err != nil {
			return err
		}
		k, err := pk(kt.String(), name, field)
		if err != nil {
			return err
		}
		if !nullOK && d.PeekKind() == jsontext.KindNull {
			return editionsJSONError(name, editionsE8)
		}
		var v V
		if err := pv(d, &v, name); err != nil {
			return err
		}
		editionsMapSet(m, k, v)
	}
	_, err := d.ReadToken()
	return err
}
func editionsJSONInt[T ~int32 | ~int64](d *jsontext.Decoder, p *T, name string) error {
	tok, err := d.ReadToken()
	if err != nil || tok.Kind() == jsontext.KindNull {
		return err
	}
	bits := 64
	if T(1)<<31 < 0 {
		bits = 32
	}
	v, err := editionsParseInt(tok, bits, name)
	*p = T(v)
	return err
}
func editionsJSONString(d *jsontext.Decoder, p *string, name string) error {
	tok, err := d.ReadToken()
	if err != nil || tok.Kind() == jsontext.KindNull {
		return err
	}
	if tok.Kind() != jsontext.KindString {
		return editionsJSONError(name, "invalid string "+tok.String())
	}
	*p = tok.String()
	return nil
}
func editionsJSONEnum[E ~int32](d *jsontext.Decoder, p *E, values map[string]int32, name, enum string, nullOK bool) error {
	tok, err := d.ReadToken()
	if err != nil {
		return err
	}
	switch tok.Kind() {
	case jsontext.KindNull:
		if nullOK {
			*p = 0
		}
		return nil
	case jsontext.KindString:
		s := tok.String()
		if n, ok := values[s]; ok {
			*p = E(n)
			return nil
		}
		return editionsJSONError(name, "invalid value for enum "+enum+": "+strconv.Quote(s))
	}
	v, err := editionsParseInt(tok, 32, name)
	*p = E(v)
	return err
}
func editionsJSONMsg[T any, PT interface {
	*T
	ProtoMergeJSONFrom(*jsontext.Decoder) error
}](d *jsontext.Decoder, p **T, _ string) error {
	if d.PeekKind() == jsontext.KindNull {
		return d.SkipValue()
	}
	return PT(editionsAlloc(p)).ProtoMergeJSONFrom(d)
}
func editionsParseInt(tok jsontext.Token, bits int, name string) (int64, error) {
	s, err := editionsJSONNumber(tok, name)
	if err != nil {
		return 0, err
	}
	if v, err := strconv.ParseInt(s, 10, bits); err == nil {
		return v, nil
	}
	n := editionsExactInt(s)
	if n == nil || !n.IsInt64() || (bits == 32 && (n.Int64() < math.MinInt32 || n.Int64() > math.MaxInt32)) {
		return 0, editionsJSONError(name, "invalid integer "+s)
	}
	return n.Int64(), nil
}
func editionsExactInt(s string) *big.Int {
	if i := strings.IndexAny(s, "eE"); i >= 0 {
		if e, err := strconv.Atoi(s[i+1:]); err != nil || e > editionsMaxJSONExponent || e < -editionsMaxJSONExponent {
			return nil
		}
	}
	r, ok := new(big.Rat).SetString(s)
	if !ok || !r.IsInt() {
		return nil
	}
	return r.Num()
}
func editionsJSONNumber(tok jsontext.Token, name string) (string, error) {
	s := tok.String()
	if k := tok.Kind(); k != jsontext.KindNumber && (k != jsontext.KindString || s == "" || (s[0] != '-' && (s[0] < '0' || s[0] > '9')) || !jsontext.Value(s).IsValid()) {
		return "", editionsJSONError(name, "invalid number "+s)
	}
	return s, nil
}
func editionsStringKey(s, _, _ string) (string, error) { return s, nil }
func editionsJSONError(name, msg string) error         { return errors.New("proto: " + name + ": " + msg) }
