// Code generated by cotorp. DO NOT EDIT.
// source: editions/editions.proto

package editionspb

import (
	"encoding/binary"
	"errors"
	"math/bits"
	"slices"
	"strconv"
	"unicode/utf8"
)

type OpenEnum int32

const (
	OpenEnum_OPEN_ZERO OpenEnum = 0
	OpenEnum_OPEN_ONE  OpenEnum = 1
)

// OpenEnum_name maps OpenEnum numbers to their names.
var OpenEnum_name = map[int32]string{
	0: "OPEN_ZERO",
	1: "OPEN_ONE",
}

// OpenEnum_value maps OpenEnum names to their numbers.
var OpenEnum_value = map[string]int32{
	"OPEN_ZERO": 0,
	"OPEN_ONE":  1,
}

// Enum returns a pointer to a copy of x.
func (x OpenEnum) Enum() *OpenEnum { return &x }

// String returns the name of x, or its number if it has no name.
func (x OpenEnum) String() string {
	if s, ok := OpenEnum_name[int32(x)]; ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// IsValid reports whether x is a declared value of OpenEnum.
func (x OpenEnum) IsValid() bool {
	switch x {
	case 0, 1:
		return true
	}
	return false
}

type ClosedEnum int32

const (
	ClosedEnum_CLOSED_ONE ClosedEnum = 1
	ClosedEnum_CLOSED_TWO ClosedEnum = 2
)

// ClosedEnum_name maps ClosedEnum numbers to their names.
var ClosedEnum_name = map[int32]string{
	1: "CLOSED_ONE",
	2: "CLOSED_TWO",
}

// ClosedEnum_value maps ClosedEnum names to their numbers.
var ClosedEnum_value = map[string]int32{
	"CLOSED_ONE": 1,
	"CLOSED_TWO": 2,
}

// Enum returns a pointer to a copy of x.
func (x ClosedEnum) Enum() *ClosedEnum { return &x }

// String returns the name of x, or its number if it has no name.
func (x ClosedEnum) String() string {
	if s, ok := ClosedEnum_name[int32(x)]; ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// IsValid reports whether x is a declared value of ClosedEnum.
func (x ClosedEnum) IsValid() bool {
	switch x {
	case 1, 2:
		return true
	}
	return false
}

type Features struct {
	ExplicitInt    *int32
	ImplicitInt    int32
	RequiredInt    *int32
	PackedInts     []int32
	ExpandedInts   []int32
	Verified       *string
	Unverified     *string
	Delimited      *Features_Child
	DelimitedList  []*Features_Child
	LengthPrefixed *Features_Child
	OpenEnum       *OpenEnum
	ClosedEnum     *ClosedEnum
	WithDefault    *string
	VerifiedMap    map[string]string
	UnverifiedMap  map[string]string

	unknownFields []byte
}

// Default values for Features fields.
const (
	Default_Features_WithDefault string = "dflt"
)

// Reset clears all fields of m.
func (m *Features) Reset() { *m = Features{} }

func (m *Features) GetExplicitInt() int32 {
	if m != nil && m.ExplicitInt != nil {
		return *m.ExplicitInt
	}
	return 0
}

func (m *Features) GetImplicitInt() int32 {
	if m != nil {
		return m.ImplicitInt
	}
	return 0
}

func (m *Features) GetRequiredInt() int32 {
	if m != nil && m.RequiredInt != nil {
		return *m.RequiredInt
	}
	return 0
}

func (m *Features) GetPackedInts() []int32 {
	if m != nil {
		return m.PackedInts
	}
	return nil
}

func (m *Features) GetExpandedInts() []int32 {
	if m != nil {
		return m.ExpandedInts
	}
	return nil
}

func (m *Features) GetVerified() string {
	if m != nil && m.Verified != nil {
		return *m.Verified
	}
	return ""
}

func (m *Features) GetUnverified() string {
	if m != nil && m.Unverified != nil {
		return *m.Unverified
	}
	return ""
}

func (m *Features) GetDelimited() *Features_Child {
	if m != nil {
		return m.Delimited
	}
	return nil
}

func (m *Features) GetDelimitedList() []*Features_Child {
	if m != nil {
		return m.DelimitedList
	}
	return nil
}

func (m *Features) GetLengthPrefixed() *Features_Child {
	if m != nil {
		return m.LengthPrefixed
	}
	return nil
}

func (m *Features) GetOpenEnum() OpenEnum {
	if m != nil && m.OpenEnum != nil {
		return *m.OpenEnum
	}
	return OpenEnum_OPEN_ZERO
}

func (m *Features) GetClosedEnum() ClosedEnum {
	if m != nil && m.ClosedEnum != nil {
		return *m.ClosedEnum
	}
	return ClosedEnum_CLOSED_ONE
}

func (m *Features) GetWithDefault() string {
	if m != nil && m.WithDefault != nil {
		return *m.WithDefault
	}
	return Default_Features_WithDefault
}

func (m *Features) GetVerifiedMap() map[string]string {
	if m != nil {
		return m.VerifiedMap
	}
	return nil
}

func (m *Features) GetUnverifiedMap() map[string]string {
	if m != nil {
		return m.UnverifiedMap
	}
	return nil
}

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *Features) ProtoUnknownFields() []byte {
	if m == nil {
		return nil
	}
	return m.unknownFields
}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *Features) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	if m.ExplicitInt != nil {
		n += 1 + (bits.Len64((uint64(int64((*m.ExplicitInt))))|1)+6)/7
	}
	if m.ImplicitInt != 0 {
		n += 1 + (bits.Len64((uint64(int64(m.ImplicitInt)))|1)+6)/7
	}
	if m.RequiredInt != nil {
		n += 1 + (bits.Len64((uint64(int64((*m.RequiredInt))))|1)+6)/7
	}
	if len(m.PackedInts) > 0 {
		l := 0
		for _, v := range m.PackedInts {
			l += (bits.Len64((uint64(int64(v)))|1) + 6) / 7
		}
		n += 1 + l + (bits.Len64((uint64(l))|1)+6)/7
	}
	for _, v := range m.ExpandedInts {
		n += 1 + (bits.Len64((uint64(int64(v)))|1)+6)/7
	}
	if m.Verified != nil {
		n += 1 + len((*m.Verified)) + (bits.Len64((uint64(len((*m.Verified))))|1)+6)/7
	}
	if m.Unverified != nil {
		n += 1 + len((*m.Unverified)) + (bits.Len64((uint64(len((*m.Unverified))))|1)+6)/7
	}
	if m.Delimited != nil {
		{
			l := m.Delimited.ProtoSize()
			n += 2 + l
		}
	}
	for _, v := range m.DelimitedList {
		{
			l := v.ProtoSize()
			n += 2 + l
		}
	}
	if m.LengthPrefixed != nil {
		{
			l := m.LengthPrefixed.ProtoSize()
			n += 1 + l + (bits.Len64((uint64(l))|1)+6)/7
		}
	}
	if m.OpenEnum != nil {
		n += 1 + (bits.Len64((uint64(int64((*m.OpenEnum))))|1)+6)/7
	}
	if m.ClosedEnum != nil {
		n += 1 + (bits.Len64((uint64(int64((*m.ClosedEnum))))|1)+6)/7
	}
	if m.WithDefault != nil {
		n += 1 + len((*m.WithDefault)) + (bits.Len64((uint64(len((*m.WithDefault))))|1)+6)/7
	}
	for k, v := range m.VerifiedMap {
		_, _ = k, v
		l := 1 + len(k) + (bits.Len64((uint64(len(k)))|1)+6)/7 + 1 + len(v) + (bits.Len64((uint64(len(v)))|1)+6)/7
		n += 1 + l + (bits.Len64((uint64(l))|1)+6)/7
	}
	for k, v := range m.UnverifiedMap {
		_, _ = k, v
		l := 1 + len(k) + (bits.Len64((uint64(len(k)))|1)+6)/7 + 1 + len(v) + (bits.Len64((uint64(len(v)))|1)+6)/7
		n += 1 + l + (bits.Len64((uint64(l))|1)+6)/7
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *Features) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// AppendBinary appends the wire-format encoding of m to b.
func (m *Features) AppendBinary(b []byte) ([]byte, error) {
	if err := m.ProtoCheckInitialized(); err != nil {
		return b, err
	}
	size := m.ProtoSize()
	l := len(b)
	b = slices.Grow(b, size)[:l+size]
	n, err := m.ProtoMarshalToSizedBuffer(b[l:])
	if err != nil {
		return b[:l], err
	}
	if n != size {
		return b[:l], errors.New("proto: message size changed during marshal")
	}
	return b, nil
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *Features) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	var u uint64
	if len(m.unknownFields) > 0 {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if len(m.UnverifiedMap) > 0 {
		keys := make([]string, 0, len(m.UnverifiedMap))
		for k := range m.UnverifiedMap {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		for j := len(keys) - 1; j >= 0; j-- {
			k := keys[j]
			v := m.UnverifiedMap[k]
			start := i
			i -= len(v)
			copy(b[i:], v)
			u = uint64(len(v))
			if u < 0x80 {
				i--
				b[i] = byte(u)
			} else {
				i -= (bits.Len64((u)|1) + 6) / 7
				binary.PutUvarint(b[i:], u)
			}
			i--
			b[i] = 0x12
			i -= len(k)
			copy(b[i:], k)
			u = uint64(len(k))
			if u < 0x80 {
				i--
				b[i] = byte(u)
			} else {
				i -= (bits.Len64((u)|1) + 6) / 7
				binary.PutUvarint(b[i:], u)
			}
			i--
			b[i] = 0x0a
			u = uint64(start - i)
			if u < 0x80 {
				i--
				b[i] = byte(u)
			} else {
				i -= (bits.Len64((u)|1) + 6) / 7
				binary.PutUvarint(b[i:], u)
			}
			i--
			b[i] = 0x7a
		}
	}
	if len(m.VerifiedMap) > 0 {
		keys := make([]string, 0, len(m.VerifiedMap))
		for k := range m.VerifiedMap {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		for j := len(keys) - 1; j >= 0; j-- {
			k := keys[j]
			v := m.VerifiedMap[k]
			start := i
			if !utf8.ValidString(v) {
				return 0, errors.New("proto: field cotorp.test.editions.Features.VerifiedMapEntry.value contains invalid UTF-8")
			}
			i -= len(v)
			copy(b[i:], v)
			u = uint64(len(v))
			if u < 0x80 {
				i--
				b[i] = byte(u)
			} else {
				i -= (bits.Len64((u)|1) + 6) / 7
				binary.PutUvarint(b[i:], u)
			}
			i--
			b[i] = 0x12
			if !utf8.ValidString(k) {
				return 0, errors.New("proto: field cotorp.test.editions.Features.VerifiedMapEntry.key contains invalid UTF-8")
			}
			i -= len(k)
			copy(b[i:], k)
			u = uint64(len(k))
			if u < 0x80 {
				i--
				b[i] = byte(u)
			} else {
				i -= (bits.Len64((u)|1) + 6) / 7
				binary.PutUvarint(b[i:], u)
			}
			i--
			b[i] = 0x0a
			u = uint64(start - i)
			if u < 0x80 {
				i--
				b[i] = byte(u)
			} else {
				i -= (bits.Len64((u)|1) + 6) / 7
				binary.PutUvarint(b[i:], u)
			}
			i--
			b[i] = 0x72
		}
	}
	if m.WithDefault != nil {
		if !utf8.ValidString((*m.WithDefault)) {
			return 0, errors.New("proto: field cotorp.test.editions.Features.with_default contains invalid UTF-8")
		}
		i -= len((*m.WithDefault))
		copy(b[i:], (*m.WithDefault))
		u = uint64(len((*m.WithDefault)))
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x6a
	}
	if m.ClosedEnum != nil {
		u = uint64(int64((*m.ClosedEnum)))
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x60
	}
	if m.OpenEnum != nil {
		u = uint64(int64((*m.OpenEnum)))
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x58
	}
	if m.LengthPrefixed != nil {
		{
			n, err := m.LengthPrefixed.ProtoMarshalToSizedBuffer(b[:i])
			if err != nil {
				return 0, err
			}
			i -= n
			u = uint64(n)
			if u < 0x80 {
				i--
				b[i] = byte(u)
			} else {
				i -= (bits.Len64((u)|1) + 6) / 7
				binary.PutUvarint(b[i:], u)
			}
			i--
			b[i] = 0x52
		}
	}
	for j := len(m.DelimitedList) - 1; j >= 0; j-- {
		{
			i--
			b[i] = 0x4c
			n, err := m.DelimitedList[j].ProtoMarshalToSizedBuffer(b[:i])
			if err != nil {
				return 0, err
			}
			i -= n
			i--
			b[i] = 0x4b
		}
	}
	if m.Delimited != nil {
		{
			i--
			b[i] = 0x44
			n, err := m.Delimited.ProtoMarshalToSizedBuffer(b[:i])
			if err != nil {
				return 0, err
			}
			i -= n
			i--
			b[i] = 0x43
		}
	}
	if m.Unverified != nil {
		i -= len((*m.Unverified))
		copy(b[i:], (*m.Unverified))
		u = uint64(len((*m.Unverified)))
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x3a
	}
	if m.Verified != nil {
		if !utf8.ValidString((*m.Verified)) {
			return 0, errors.New("proto: field cotorp.test.editions.Features.verified contains invalid UTF-8")
		}
		i -= len((*m.Verified))
		copy(b[i:], (*m.Verified))
		u = uint64(len((*m.Verified)))
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x32
	}
	for j := len(m.ExpandedInts) - 1; j >= 0; j-- {
		u = uint64(int64(m.ExpandedInts[j]))
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x28
	}
	if len(m.PackedInts) > 0 {
		start := i
		for j := len(m.PackedInts) - 1; j >= 0; j-- {
			u = uint64(int64(m.PackedInts[j]))
			if u < 0x80 {
				i--
				b[i] = byte(u)
			} else {
				i -= (bits.Len64((u)|1) + 6) / 7
				binary.PutUvarint(b[i:], u)
			}
		}
		u = uint64(start - i)
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x22
	}
	if m.RequiredInt != nil {
		u = uint64(int64((*m.RequiredInt)))
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x18
	}
	if m.ImplicitInt != 0 {
		u = uint64(int64(m.ImplicitInt))
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x10
	}
	if m.ExplicitInt != nil {
		u = uint64(int64((*m.ExplicitInt)))
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x08
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *Features) UnmarshalBinary(b []byte) error {
	*m = Features{}
	if err := m.ProtoMergeDepth(b, 0); err != nil {
		return err
	}
	return m.ProtoCheckInitialized()
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *Features) ProtoMerge(b []byte) error {
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *Features) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= 10000 {
		goto errDepth
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>3 == 0 || t>>3 > 536870911 {
			goto errParse
		}
		num, typ := int32(t>>3), int(t&7)
		start := b
		b = b[n:]
		switch num {
		case 1:
			if typ == 0 {
				x, n := binary.Uvarint(b)
				if n <= 0 {
					goto errParse
				}
				b = b[n:]
				v := int32(x)
				m.ExplicitInt = &v
				continue
			}
		case 2:
			if typ == 0 {
				x, n := binary.Uvarint(b)
				if n <= 0 {
					goto errParse
				}
				b = b[n:]
				m.ImplicitInt = int32(x)
				continue
			}
		case 3:
			if typ == 0 {
				x, n := binary.Uvarint(b)
				if n <= 0 {
					goto errParse
				}
				b = b[n:]
				v := int32(x)
				m.RequiredInt = &v
				continue
			}
		case 4:
			if typ == 2 {
				ln, n := binary.Uvarint(b)
				if n <= 0 || ln > uint64(len(b)-n) {
					goto errParse
				}
				v := b[n : n+int(ln)]
				n += int(ln)
				b = b[n:]
				for len(v) > 0 {
					x, n := binary.Uvarint(v)
					if n <= 0 {
						goto errParse
					}
					v = v[n:]
					m.PackedInts = append(m.PackedInts, int32(x))
				}
				continue
			}
			if typ == 0 {
				x, n := binary.Uvarint(b)
				if n <= 0 {
					goto errParse
				}
				b = b[n:]
				m.PackedInts = append(m.PackedInts, int32(x))
				continue
			}
		case 5:
			if typ == 2 {
				ln, n := binary.Uvarint(b)
				if n <= 0 || ln > uint64(len(b)-n) {
					goto errParse
				}
				v := b[n : n+int(ln)]
				n += int(ln)
				b = b[n:]
				for len(v) > 0 {
					x, n := binary.Uvarint(v)
					if n <= 0 {
						goto errParse
					}
					v = v[n:]
					m.ExpandedInts = append(m.ExpandedInts, int32(x))
				}
				continue
			}
			if typ == 0 {
				x, n := binary.Uvarint(b)
				if n <= 0 {
					goto errParse
				}
				b = b[n:]
				m.ExpandedInts = append(m.ExpandedInts, int32(x))
				continue
			}
		case 6:
			if typ == 2 {
				ln, n := binary.Uvarint(b)
				if n <= 0 || ln > uint64(len(b)-n) {
					goto errParse
				}
				x := b[n : n+int(ln)]
				n += int(ln)
				if !utf8.Valid(x) {
					return errors.New("proto: field cotorp.test.editions.Features.verified contains invalid UTF-8")
				}
				b = b[n:]
				v := string(x)
				m.Verified = &v
				continue
			}
		case 7:
			if typ == 2 {
				ln, n := binary.Uvarint(b)
				if n <= 0 || ln > uint64(len(b)-n) {
					goto errParse
				}
				x := b[n : n+int(ln)]
				n += int(ln)
				b = b[n:]
				v := string(x)
				m.Unverified = &v
				continue
			}
		case 8:
			if typ == 3 {
				var n int
				var stk [16]int32
				open := append(stk[:0], num)
				n = 0
				for len(open) > 0 {
					if depth+len(open) > 10000 {
						goto errDepth
					}
					t, k := binary.Uvarint(b[n:])
					if k <= 0 || t>>3 == 0 || t>>3 > 536870911 {
						goto errParse
					}
					n += k
					switch t & 7 {
					case 0:
						_, k = binary.Uvarint(b[n:])
						if k <= 0 {
							goto errParse
						}
					case 1:
						k = 8
					case 2:
						ln, k2 := binary.Uvarint(b[n:])
						if k2 <= 0 || ln > uint64(len(b)-n-k2) {
							goto errParse
						}
						k = k2 + int(ln)
					case 3:
						open = append(open, int32(t>>3))
						k = 0
					case 4:
						if open[len(open)-1] != int32(t>>3) {
							goto errParse
						}
						open = open[:len(open)-1]
						k = 0
					case 5:
						k = 4
					default:
						goto errParse
					}
					if k > len(b)-n {
						goto errParse
					}
					n += k
				}
				if m.Delimited == nil {
					m.Delimited = &Features_Child{}
				}
				mv := m.Delimited
				if err := mv.ProtoMergeDepth(b[:n-1], depth+1); err != nil {
					return err
				}
				b = b[n:]
				continue
			}
		case 9:
			if typ == 3 {
				var n int
				var stk [16]int32
				open := append(stk[:0], num)
				n = 0
				for len(open) > 0 {
					if depth+len(open) > 10000 {
						goto errDepth
					}
					t, k := binary.Uvarint(b[n:])
					if k <= 0 || t>>3 == 0 || t>>3 > 536870911 {
						goto errParse
					}
					n += k
					switch t & 7 {
					case 0:
						_, k = binary.Uvarint(b[n:])
						if k <= 0 {
							goto errParse
						}
					case 1:
						k = 8
					case 2:
						ln, k2 := binary.Uvarint(b[n:])
						if k2 <= 0 || ln > uint64(len(b)-n-k2) {
							goto errParse
						}
						k = k2 + int(ln)
					case 3:
						open = append(open, int32(t>>3))
						k = 0
					case 4:
						if open[len(open)-1] != int32(t>>3) {
							goto errParse
						}
						open = open[:len(open)-1]
						k = 0
					case 5:
						k = 4
					default:
						goto errParse
					}
					if k > len(b)-n {
						goto errParse
					}
					n += k
				}
				mv := &Features_Child{}
				m.DelimitedList = append(m.DelimitedList, mv)
				if err := mv.ProtoMergeDepth(b[:n-1], depth+1); err != nil {
					return err
				}
				b = b[n:]
				continue
			}
		case 10:
			if typ == 2 {
				ln, n := binary.Uvarint(b)
				if n <= 0 || ln > uint64(len(b)-n) {
					goto errParse
				}
				v := b[n : n+int(ln)]
				n += int(ln)
				if m.LengthPrefixed == nil {
					m.LengthPrefixed = &Features_Child{}
				}
				mv := m.LengthPrefixed
				if err := mv.ProtoMergeDepth(v, depth+1); err != nil {
					return err
				}
				b = b[n:]
				continue
			}
		case 11:
			if typ == 0 {
				x, n := binary.Uvarint(b)
				if n <= 0 {
					goto errParse
				}
				b = b[n:]
				v := OpenEnum(int32(x))
				m.OpenEnum = &v
				continue
			}
		case 12:
			if typ == 0 {
				x, n := binary.Uvarint(b)
				if n <= 0 {
					goto errParse
				}
				b = b[n:]
				e := ClosedEnum(int32(x))
				if !e.IsValid() {
					m.unknownFields = binary.AppendUvarint(append(m.unknownFields, 0x60), x)
					continue
				}
				v := e
				m.ClosedEnum = &v
				continue
			}
		case 13:
			if typ == 2 {
				ln, n := binary.Uvarint(b)
				if n <= 0 || ln > uint64(len(b)-n) {
					goto errParse
				}
				x := b[n : n+int(ln)]
				n += int(ln)
				if !utf8.Valid(x) {
					return errors.New("proto: field cotorp.test.editions.Features.with_default contains invalid UTF-8")
				}
				b = b[n:]
				v := string(x)
				m.WithDefault = &v
				continue
			}
		case 14:
			if typ == 2 {
				ln, n := binary.Uvarint(b)
				if n <= 0 || ln > uint64(len(b)-n) {
					goto errParse
				}
				v := b[n : n+int(ln)]
				n += int(ln)
				var mk string
				var mv string
				for len(v) > 0 {
					t, n := binary.Uvarint(v)
					if n <= 0 || t>>3 == 0 || t>>3 > 536870911 {
						goto errParse
					}
					num, typ := int32(t>>3), int(t&7)
					v = v[n:]
					if num == 1 && typ == 2 {
						ln, n := binary.Uvarint(v)
						if n <= 0 || ln > uint64(len(v)-n) {
							goto errParse
						}
						x := v[n : n+int(ln)]
						n += int(ln)
						if !utf8.Valid(x) {
							return errors.New("proto: field cotorp.test.editions.Features.VerifiedMapEntry.key contains invalid UTF-8")
						}
						mk = string(x)
						v = v[n:]
						continue
					}
					if num == 2 && typ == 2 {
						ln, n := binary.Uvarint(v)
						if n <= 0 || ln > uint64(len(v)-n) {
							goto errParse
						}
						x := v[n : n+int(ln)]
						n += int(ln)
						if !utf8.Valid(x) {
							return errors.New("proto: field cotorp.test.editions.Features.VerifiedMapEntry.value contains invalid UTF-8")
						}
						mv = string(x)
						v = v[n:]
						continue
					}
					switch typ {
					case 0:
						_, n = binary.Uvarint(v)
						if n <= 0 {
							goto errParse
						}
					case 1:
						if len(v) < 8 {
							goto errParse
						}
						n = 8
					case 2:
						ln, k := binary.Uvarint(v)
						if k <= 0 || ln > uint64(len(v)-k) {
							goto errParse
						}
						n = k + int(ln)
					case 3:
						var stk [16]int32
						open := append(stk[:0], num)
						n = 0
						for len(open) > 0 {
							if depth+len(open) > 10000 {
								goto errDepth
							}
							t, k := binary.Uvarint(v[n:])
							if k <= 0 || t>>3 == 0 || t>>3 > 536870911 {
								goto errParse
							}
							n += k
							switch t & 7 {
							case 0:
								_, k = binary.Uvarint(v[n:])
								if k <= 0 {
									goto errParse
								}
							case 1:
								k = 8
							case 2:
								ln, k2 := binary.Uvarint(v[n:])
								if k2 <= 0 || ln > uint64(len(v)-n-k2) {
									goto errParse
								}
								k = k2 + int(ln)
							case 3:
								open = append(open, int32(t>>3))
								k = 0
							case 4:
								if open[len(open)-1] != int32(t>>3) {
									goto errParse
								}
								open = open[:len(open)-1]
								k = 0
							case 5:
								k = 4
							default:
								goto errParse
							}
							if k > len(v)-n {
								goto errParse
							}
							n += k
						}
					case 5:
						if len(v) < 4 {
							goto errParse
						}
						n = 4
					default:
						goto errParse
					}
					v = v[n:]
				}
				if m.VerifiedMap == nil {
					m.VerifiedMap = make(map[string]string)
				}
				m.VerifiedMap[mk] = mv
				b = b[n:]
				continue
			}
		case 15:
			if typ == 2 {
				ln, n := binary.Uvarint(b)
				if n <= 0 || ln > uint64(len(b)-n) {
					goto errParse
				}
				v := b[n : n+int(ln)]
				n += int(ln)
				var mk string
				var mv string
				for len(v) > 0 {
					t, n := binary.Uvarint(v)
					if n <= 0 || t>>3 == 0 || t>>3 > 536870911 {
						goto errParse
					}
					num, typ := int32(t>>3), int(t&7)
					v = v[n:]
					if num == 1 && typ == 2 {
						ln, n := binary.Uvarint(v)
						if n <= 0 || ln > uint64(len(v)-n) {
							goto errParse
						}
						x := v[n : n+int(ln)]
						n += int(ln)
						mk = string(x)
						v = v[n:]
						continue
					}
					if num == 2 && typ == 2 {
						ln, n := binary.Uvarint(v)
						if n <= 0 || ln > uint64(len(v)-n) {
							goto errParse
						}
						x := v[n : n+int(ln)]
						n += int(ln)
						mv = string(x)
						v = v[n:]
						continue
					}
					switch typ {
					case 0:
						_, n = binary.Uvarint(v)
						if n <= 0 {
							goto errParse
						}
					case 1:
						if len(v) < 8 {
							goto errParse
						}
						n = 8
					case 2:
						ln, k := binary.Uvarint(v)
						if k <= 0 || ln > uint64(len(v)-k) {
							goto errParse
						}
						n = k + int(ln)
					case 3:
						var stk [16]int32
						open := append(stk[:0], num)
						n = 0
						for len(open) > 0 {
							if depth+len(open) > 10000 {
								goto errDepth
							}
							t, k := binary.Uvarint(v[n:])
							if k <= 0 || t>>3 == 0 || t>>3 > 536870911 {
								goto errParse
							}
							n += k
							switch t & 7 {
							case 0:
								_, k = binary.Uvarint(v[n:])
								if k <= 0 {
									goto errParse
								}
							case 1:
								k = 8
							case 2:
								ln, k2 := binary.Uvarint(v[n:])
								if k2 <= 0 || ln > uint64(len(v)-n-k2) {
									goto errParse
								}
								k = k2 + int(ln)
							case 3:
								open = append(open, int32(t>>3))
								k = 0
							case 4:
								if open[len(open)-1] != int32(t>>3) {
									goto errParse
								}
								open = open[:len(open)-1]
								k = 0
							case 5:
								k = 4
							default:
								goto errParse
							}
							if k > len(v)-n {
								goto errParse
							}
							n += k
						}
					case 5:
						if len(v) < 4 {
							goto errParse
						}
						n = 4
					default:
						goto errParse
					}
					v = v[n:]
				}
				if m.UnverifiedMap == nil {
					m.UnverifiedMap = make(map[string]string)
				}
				m.UnverifiedMap[mk] = mv
				b = b[n:]
				continue
			}
		}
		// Unknown field, or a known field with an unexpected wire type.
		switch typ {
		case 0:
			_, n = binary.Uvarint(b)
			if n <= 0 {
				goto errParse
			}
		case 1:
			if len(b) < 8 {
				goto errParse
			}
			n = 8
		case 2:
			ln, k := binary.Uvarint(b)
			if k <= 0 || ln > uint64(len(b)-k) {
				goto errParse
			}
			n = k + int(ln)
		case 3:
			var stk [16]int32
			open := append(stk[:0], num)
			n = 0
			for len(open) > 0 {
				if depth+len(open) > 10000 {
					goto errDepth
				}
				t, k := binary.Uvarint(b[n:])
				if k <= 0 || t>>3 == 0 || t>>3 > 536870911 {
					goto errParse
				}
				n += k
				switch t & 7 {
				case 0:
					_, k = binary.Uvarint(b[n:])
					if k <= 0 {
						goto errParse
					}
				case 1:
					k = 8
				case 2:
					ln, k2 := binary.Uvarint(b[n:])
					if k2 <= 0 || ln > uint64(len(b)-n-k2) {
						goto errParse
					}
					k = k2 + int(ln)
				case 3:
					open = append(open, int32(t>>3))
					k = 0
				case 4:
					if open[len(open)-1] != int32(t>>3) {
						goto errParse
					}
					open = open[:len(open)-1]
					k = 0
				case 5:
					k = 4
				default:
					goto errParse
				}
				if k > len(b)-n {
					goto errParse
				}
				n += k
			}
		case 5:
			if len(b) < 4 {
				goto errParse
			}
			n = 4
		default:
			goto errParse
		}
		m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
		b = b[n:]
	}
	return nil
errParse:
	return errors.New("proto: cannot parse invalid wire-format data")
errDepth:
	return errors.New("proto: exceeded maximum recursion depth")
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *Features) ProtoCheckInitialized() error {
	if m == nil {
		return nil
	}
	if m.RequiredInt == nil {
		return errors.New("proto: required field cotorp.test.editions.Features.required_int not set")
	}
	return nil
}

type Features_Child struct {
	X *int32

	unknownFields []byte
}

// Reset clears all fields of m.
func (m *Features_Child) Reset() { *m = Features_Child{} }

func (m *Features_Child) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *Features_Child) ProtoUnknownFields() []byte {
	if m == nil {
		return nil
	}
	return m.unknownFields
}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *Features_Child) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	if m.X != nil {
		n += 1 + (bits.Len64((uint64(int64((*m.X))))|1)+6)/7
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *Features_Child) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// AppendBinary appends the wire-format encoding of m to b.
func (m *Features_Child) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	l := len(b)
	b = slices.Grow(b, size)[:l+size]
	n, err := m.ProtoMarshalToSizedBuffer(b[l:])
	if err != nil {
		return b[:l], err
	}
	if n != size {
		return b[:l], errors.New("proto: message size changed during marshal")
	}
	return b, nil
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *Features_Child) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	var u uint64
	if len(m.unknownFields) > 0 {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if m.X != nil {
		u = uint64(int64((*m.X)))
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x08
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *Features_Child) UnmarshalBinary(b []byte) error {
	*m = Features_Child{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *Features_Child) ProtoMerge(b []byte) error {
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *Features_Child) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= 10000 {
		goto errDepth
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>3 == 0 || t>>3 > 536870911 {
			goto errParse
		}
		num, typ := int32(t>>3), int(t&7)
		start := b
		b = b[n:]
		switch num {
		case 1:
			if typ == 0 {
				x, n := binary.Uvarint(b)
				if n <= 0 {
					goto errParse
				}
				b = b[n:]
				v := int32(x)
				m.X = &v
				continue
			}
		}
		// Unknown field, or a known field with an unexpected wire type.
		switch typ {
		case 0:
			_, n = binary.Uvarint(b)
			if n <= 0 {
				goto errParse
			}
		case 1:
			if len(b) < 8 {
				goto errParse
			}
			n = 8
		case 2:
			ln, k := binary.Uvarint(b)
			if k <= 0 || ln > uint64(len(b)-k) {
				goto errParse
			}
			n = k + int(ln)
		case 3:
			var stk [16]int32
			open := append(stk[:0], num)
			n = 0
			for len(open) > 0 {
				if depth+len(open) > 10000 {
					goto errDepth
				}
				t, k := binary.Uvarint(b[n:])
				if k <= 0 || t>>3 == 0 || t>>3 > 536870911 {
					goto errParse
				}
				n += k
				switch t & 7 {
				case 0:
					_, k = binary.Uvarint(b[n:])
					if k <= 0 {
						goto errParse
					}
				case 1:
					k = 8
				case 2:
					ln, k2 := binary.Uvarint(b[n:])
					if k2 <= 0 || ln > uint64(len(b)-n-k2) {
						goto errParse
					}
					k = k2 + int(ln)
				case 3:
					open = append(open, int32(t>>3))
					k = 0
				case 4:
					if open[len(open)-1] != int32(t>>3) {
						goto errParse
					}
					open = open[:len(open)-1]
					k = 0
				case 5:
					k = 4
				default:
					goto errParse
				}
				if k > len(b)-n {
					goto errParse
				}
				n += k
			}
		case 5:
			if len(b) < 4 {
				goto errParse
			}
			n = 4
		default:
			goto errParse
		}
		m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
		b = b[n:]
	}
	return nil
errParse:
	return errors.New("proto: cannot parse invalid wire-format data")
errDepth:
	return errors.New("proto: exceeded maximum recursion depth")
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *Features_Child) ProtoCheckInitialized() error {
	return nil
}

type ImplicitMessage struct {
	A int32
	B string
	C *Features_Child

	unknownFields []byte
}

// Reset clears all fields of m.
func (m *ImplicitMessage) Reset() { *m = ImplicitMessage{} }

func (m *ImplicitMessage) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *ImplicitMessage) GetB() string {
	if m != nil {
		return m.B
	}
	return ""
}

func (m *ImplicitMessage) GetC() *Features_Child {
	if m != nil {
		return m.C
	}
	return nil
}

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *ImplicitMessage) ProtoUnknownFields() []byte {
	if m == nil {
		return nil
	}
	return m.unknownFields
}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *ImplicitMessage) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	if m.A != 0 {
		n += 1 + (bits.Len64((uint64(int64(m.A)))|1)+6)/7
	}
	if len(m.B) > 0 {
		n += 1 + len(m.B) + (bits.Len64((uint64(len(m.B)))|1)+6)/7
	}
	if m.C != nil {
		{
			l := m.C.ProtoSize()
			n += 1 + l + (bits.Len64((uint64(l))|1)+6)/7
		}
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *ImplicitMessage) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// AppendBinary appends the wire-format encoding of m to b.
func (m *ImplicitMessage) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	l := len(b)
	b = slices.Grow(b, size)[:l+size]
	n, err := m.ProtoMarshalToSizedBuffer(b[l:])
	if err != nil {
		return b[:l], err
	}
	if n != size {
		return b[:l], errors.New("proto: message size changed during marshal")
	}
	return b, nil
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *ImplicitMessage) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	var u uint64
	if len(m.unknownFields) > 0 {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if m.C != nil {
		{
			n, err := m.C.ProtoMarshalToSizedBuffer(b[:i])
			if err != nil {
				return 0, err
			}
			i -= n
			u = uint64(n)
			if u < 0x80 {
				i--
				b[i] = byte(u)
			} else {
				i -= (bits.Len64((u)|1) + 6) / 7
				binary.PutUvarint(b[i:], u)
			}
			i--
			b[i] = 0x1a
		}
	}
	if len(m.B) > 0 {
		if !utf8.ValidString(m.B) {
			return 0, errors.New("proto: field cotorp.test.editions.ImplicitMessage.b contains invalid UTF-8")
		}
		i -= len(m.B)
		copy(b[i:], m.B)
		u = uint64(len(m.B))
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x12
	}
	if m.A != 0 {
		u = uint64(int64(m.A))
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x08
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *ImplicitMessage) UnmarshalBinary(b []byte) error {
	*m = ImplicitMessage{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *ImplicitMessage) ProtoMerge(b []byte) error {
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *ImplicitMessage) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= 10000 {
		goto errDepth
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>3 == 0 || t>>3 > 536870911 {
			goto errParse
		}
		num, typ := int32(t>>3), int(t&7)
		start := b
		b = b[n:]
		switch num {
		case 1:
			if typ == 0 {
				x, n := binary.Uvarint(b)
				if n <= 0 {
					goto errParse
				}
				b = b[n:]
				m.A = int32(x)
				continue
			}
		case 2:
			if typ == 2 {
				ln, n := binary.Uvarint(b)
				if n <= 0 || ln > uint64(len(b)-n) {
					goto errParse
				}
				x := b[n : n+int(ln)]
				n += int(ln)
				if !utf8.Valid(x) {
					return errors.New("proto: field cotorp.test.editions.ImplicitMessage.b contains invalid UTF-8")
				}
				b = b[n:]
				m.B = string(x)
				continue
			}
		case 3:
			if typ == 2 {
				ln, n := binary.Uvarint(b)
				if n <= 0 || ln > uint64(len(b)-n) {
					goto errParse
				}
				v := b[n : n+int(ln)]
				n += int(ln)
				if m.C == nil {
					m.C = &Features_Child{}
				}
				mv := m.C
				if err := mv.ProtoMergeDepth(v, depth+1); err != nil {
					return err
				}
				b = b[n:]
				continue
			}
		}
		// Unknown field, or a known field with an unexpected wire type.
		switch typ {
		case 0:
			_, n = binary.Uvarint(b)
			if n <= 0 {
				goto errParse
			}
		case 1:
			if len(b) < 8 {
				goto errParse
			}
			n = 8
		case 2:
			ln, k := binary.Uvarint(b)
			if k <= 0 || ln > uint64(len(b)-k) {
				goto errParse
			}
			n = k + int(ln)
		case 3:
			var stk [16]int32
			open := append(stk[:0], num)
			n = 0
			for len(open) > 0 {
				if depth+len(open) > 10000 {
					goto errDepth
				}
				t, k := binary.Uvarint(b[n:])
				if k <= 0 || t>>3 == 0 || t>>3 > 536870911 {
					goto errParse
				}
				n += k
				switch t & 7 {
				case 0:
					_, k = binary.Uvarint(b[n:])
					if k <= 0 {
						goto errParse
					}
				case 1:
					k = 8
				case 2:
					ln, k2 := binary.Uvarint(b[n:])
					if k2 <= 0 || ln > uint64(len(b)-n-k2) {
						goto errParse
					}
					k = k2 + int(ln)
				case 3:
					open = append(open, int32(t>>3))
					k = 0
				case 4:
					if open[len(open)-1] != int32(t>>3) {
						goto errParse
					}
					open = open[:len(open)-1]
					k = 0
				case 5:
					k = 4
				default:
					goto errParse
				}
				if k > len(b)-n {
					goto errParse
				}
				n += k
			}
		case 5:
			if len(b) < 4 {
				goto errParse
			}
			n = 4
		default:
			goto errParse
		}
		m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
		b = b[n:]
	}
	return nil
errParse:
	return errors.New("proto: cannot parse invalid wire-format data")
errDepth:
	return errors.New("proto: exceeded maximum recursion depth")
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *ImplicitMessage) ProtoCheckInitialized() error {
	return nil
}
