// Code generated by cotorp. DO NOT EDIT.
// source: otlp/ids.proto

package otlppb

import (
	"bytes"
	"encoding/binary"
	"encoding/hex"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"io"
	"math/bits"
	"slices"
	"strconv"
)

const (
	idsWireVarint        = 0
	idsWireFixed64       = 1
	idsWireBytes         = 2
	idsWireStartGroup    = 3
	idsWireEndGroup      = 4
	idsWireFixed32       = 5
	idsTagTypeBits       = 3
	idsTagTypeMask       = 1<<3 - 1
	idsMaxFieldNumber    = 1<<29 - 1
	idsFixed32Size       = 4
	idsFixed64Size       = 8
	idsVarintPayloadBits = 7
	idsVarintContBit     = 0x80
	idsMaxDepth          = 10000
	idsSkipStackSize     = 16
	idsClassNone         = 0
	idsClassHex          = 7
	idsErrDepth          = "proto: exceeded maximum recursion depth"
	idsErrParse          = "proto: cannot parse invalid wire-format data"
)

type Ids struct {
	TraceId []byte
	SpanIds [][]byte

	unknownFields []byte
}

// Reset clears all fields of m.
func (m *Ids) Reset() { *m = Ids{} }

func (m *Ids) GetTraceId() []byte   { return idsGet(m, func(m *Ids) []byte { return m.TraceId }) }
func (m *Ids) GetSpanIds() [][]byte { return idsGet(m, func(m *Ids) [][]byte { return m.SpanIds }) }

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *Ids) ProtoUnknownFields() []byte {
	return idsGet(m, func(m *Ids) []byte { return m.unknownFields })
}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *Ids) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	if len(m.TraceId) > 0 {
		n += 1 + idsSizeLen(len(m.TraceId))
	}
	for _, v := range m.SpanIds {
		n += 1 + idsSizeLen(len(v))
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *Ids) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *Ids) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	b = slices.Grow(b, size)
	n, err := m.ProtoMarshalToSizedBuffer(b[len(b) : len(b)+size])
	return idsAppended(b, size, n, err)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *Ids) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if len(m.unknownFields) > 0 {
		i -= copy(b[i-len(m.unknownFields):], m.unknownFields)
	}
	for _, v := range slices.Backward(m.SpanIds) {
		i = idsPutVarint(b, idsPutVarint(b, i-copy(b[i-len(v):], v), uint64(len(v))), 2<<idsTagTypeBits|idsWireBytes)
	}
	if len(m.TraceId) > 0 {
		i = idsPutVarint(b, idsPutVarint(b, i-copy(b[i-len(m.TraceId):], m.TraceId), uint64(len(m.TraceId))), 1<<idsTagTypeBits|idsWireBytes)
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *Ids) UnmarshalBinary(b []byte) error {
	*m = Ids{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *Ids) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *Ids) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= idsMaxDepth {
		return errors.New(idsErrDepth)
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>idsTagTypeBits == 0 || t>>idsTagTypeBits > idsMaxFieldNumber {
			goto errParse
		}
		start := b
		b = b[n:]
		switch t {
		case 1<<idsTagTypeBits | idsWireBytes:
			x, n := idsReadBytes(b)
			if n < 0 {
				goto errParse
			}
			b, m.TraceId = b[n:], append([]byte{}, x...)
		case 2<<idsTagTypeBits | idsWireBytes:
			x, n := idsReadBytes(b)
			if n < 0 {
				goto errParse
			}
			b, m.SpanIds = b[n:], append(m.SpanIds, append([]byte{}, x...))
		default:
			n, err := idsSkipField(b, t, depth)
			if err != nil {
				return err
			}
			m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
errParse:
	return errors.New(idsErrParse)
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *Ids) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *Ids) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e. It implements
// json.MarshalerTo from encoding/json/v2.
func (m *Ids) MarshalJSONTo(e *jsontext.Encoder) error {
	b, err := m.ProtoAppendJSON(e.AvailableBuffer())
	return idsWriteJSON(e, b, err)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b. It does not
// check required fields.
func (m *Ids) ProtoAppendJSON(b []byte) ([]byte, error) {
	if m == nil {
		return append(b, "{}"...), nil
	}
	start := len(b)
	if len(m.TraceId) > 0 {
		b = append(hex.AppendEncode(append(b, ",\"traceId\":\""...), m.TraceId), '"')
	}
	if len(m.SpanIds) > 0 {
		b = append(b, ",\"spanIds\":["...)
		for j := range m.SpanIds {
			b = append(append(hex.AppendEncode(append(b, '"'), m.SpanIds[j]), '"'), ',')
		}
		b[len(b)-1] = ']'
	}
	return idsCloseObject(b, start), nil
}

// UnmarshalJSON replaces the contents of m with the decoded ProtoJSON
// value in b.
func (m *Ids) UnmarshalJSON(b []byte) error {
	*m = Ids{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m.
// It does not check required fields.
func (m *Ids) ProtoMergeJSON(b []byte) error {
	d := jsontext.NewDecoder(bytes.NewBuffer(b))
	return idsEndJSON(d, m.ProtoMergeJSONFrom(d), "cotorp.test.otlp.Ids")
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value
// read from d. It implements json.UnmarshalerFrom from encoding/json/v2.
func (m *Ids) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	d, err := idsStrictDecoder(d)
	if err != nil {
		return err
	}
	*m = Ids{}
	return m.ProtoMergeJSONFrom(d)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it
// into m. It does not check required fields. d should reject invalid
// UTF-8, as jsontext decoders do by default.
func (m *Ids) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	ok, err := idsOpenJSON(d, jsontext.KindBeginObject, "cotorp.test.otlp.Ids", "object")
	if !ok {
		return err
	}
	seen, in, f := [2]bool{}, jsontext.KindInvalid, 0
	for {
		if in == jsontext.KindInvalid {
			kt, more, err := idsNextKey(d)
			if !more {
				return err
			}
			key := kt.String()
			switch key {
			case "traceId", "trace_id":
				f = 0
			case "spanIds", "span_ids":
				f = 1
			default:
				if err := d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if seen[f] {
				return errors.New("proto: cotorp.test.otlp.Ids: duplicate field " + strconv.Quote(key))
			}
			seen[f] = true
			if d.PeekKind() == jsontext.KindNull {
				if err := d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			switch f {
			case 1:
				if err := idsExpectJSON(d, jsontext.KindBeginArray, "cotorp.test.otlp.Ids", "array"); err != nil {
					return err
				}
				in = jsontext.KindBeginArray
				continue
			}
		} else {
			if k := d.PeekKind(); k == jsontext.KindEndArray || k == jsontext.KindEndObject {
				if _, err := d.ReadToken(); err != nil {
					return err
				}
				in = jsontext.KindInvalid
				continue
			}
			if d.PeekKind() == jsontext.KindNull {
				return errors.New("proto: cotorp.test.otlp.Ids: null is not allowed in repeated fields or map values")
			}
		}
		class, by, tok := idsIdsJSONClasses[f], []byte(nil), jsontext.Token{}
		if class != idsClassNone {
			if tok, err = d.ReadToken(); err != nil {
				return err
			}
		}
		switch class {
		case idsClassHex:
			by, err = idsParseHex(tok, "cotorp.test.otlp.Ids")
		}
		if err != nil {
			return err
		}
		switch f {
		case 0:
			m.TraceId = by
		case 1:
			m.SpanIds = append(m.SpanIds, by)
		}
	}
}

var idsIdsJSONClasses = [2]int{idsClassHex, idsClassHex}

func idsPutVarint(b []byte, i int, u uint64) int {
	if u < idsVarintContBit {
		b[i-1] = byte(u)
		return i - 1
	}
	i -= (bits.Len64(u|1) + idsVarintPayloadBits - 1) / idsVarintPayloadBits
	binary.PutUvarint(b[i:], u)
	return i
}

func idsSizeLen(l int) int {
	return l + (bits.Len64(uint64(l)|1)+idsVarintPayloadBits-1)/idsVarintPayloadBits
}

func idsReadBytes(b []byte) (v []byte, n int) {
	ln, k := binary.Uvarint(b)
	if k <= 0 || ln > uint64(len(b)-k) {
		return nil, -1
	}
	return b[k : k+int(ln)], k + int(ln)
}

func idsSkipField(b []byte, t uint64, depth int) (int, error) {
	switch t & idsTagTypeMask {
	case idsWireVarint:
		if _, n := binary.Uvarint(b); n > 0 {
			return n, nil
		}
	case idsWireFixed64:
		if len(b) >= idsFixed64Size {
			return idsFixed64Size, nil
		}
	case idsWireBytes:
		if _, n := idsReadBytes(b); n >= 0 {
			return n, nil
		}
	case idsWireStartGroup:
		return idsSkipGroup(b, int32(t>>idsTagTypeBits), depth)
	case idsWireFixed32:
		if len(b) >= idsFixed32Size {
			return idsFixed32Size, nil
		}
	}
	return 0, errors.New(idsErrParse)
}

func idsSkipGroup(b []byte, num int32, depth int) (int, error) {
	var stk [idsSkipStackSize]int32
	open := append(stk[:0], num)
	n := 0
	for len(open) > 0 {
		if depth+len(open) > idsMaxDepth {
			return 0, errors.New(idsErrDepth)
		}
		t, k := binary.Uvarint(b[n:])
		if k <= 0 || t>>idsTagTypeBits == 0 || t>>idsTagTypeBits > idsMaxFieldNumber {
			return 0, errors.New(idsErrParse)
		}
		n += k
		switch t & idsTagTypeMask {
		case idsWireStartGroup:
			open = append(open, int32(t>>idsTagTypeBits))
		case idsWireEndGroup:
			if open[len(open)-1] != int32(t>>idsTagTypeBits) {
				return 0, errors.New(idsErrParse)
			}
			open = open[:len(open)-1]
		default:
			k, err := idsSkipField(b[n:], t, depth)
			if err != nil {
				return 0, err
			}
			n += k
		}
	}
	return n, nil
}

func idsAppended(b []byte, size, n int, err error) ([]byte, error) {
	if err == nil && n != size {
		err = errors.New("proto: message size changed during marshal")
	}
	if err != nil {
		return b, err
	}
	return b[:len(b)+size], nil
}

func idsGet[M, T any](m *M, f func(*M) T) (t T) {
	if m != nil {
		t = f(m)
	}
	return t
}

func idsWriteJSON(e *jsontext.Encoder, b []byte, err error) error {
	if err != nil {
		return err
	}
	return e.WriteValue(b)
}

func idsCloseObject(b []byte, start int) []byte {
	if len(b) == start {
		return append(b, "{}"...)
	}
	b[start] = '{'
	return append(b, '}')
}

func idsEndJSON(d *jsontext.Decoder, err error, name string) error {
	if err != nil {
		return err
	}
	if _, err := d.ReadToken(); err != io.EOF {
		return idsJSONError(name, "unexpected data after JSON value")
	}
	return nil
}

func idsStrictDecoder(d *jsontext.Decoder) (*jsontext.Decoder, error) {
	if lax, _ := json.GetOption(d.Options(), jsontext.AllowInvalidUTF8); !lax {
		return d, nil
	}
	v, err := d.ReadValue()
	if err != nil {
		return nil, err
	}
	return jsontext.NewDecoder(bytes.NewBuffer(v)), nil
}

func idsOpenJSON(d *jsontext.Decoder, kind jsontext.Kind, name, what string) (bool, error) {
	if d.PeekKind() == jsontext.KindNull {
		return false, d.SkipValue()
	}
	err := idsExpectJSON(d, kind, name, what)
	return err == nil, err
}

func idsExpectJSON(d *jsontext.Decoder, kind jsontext.Kind, name, what string) error {
	tok, err := d.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != kind {
		return idsJSONError(name, "expected a JSON "+what)
	}
	return nil
}

func idsNextKey(d *jsontext.Decoder) (jsontext.Token, bool, error) {
	if d.PeekKind() == jsontext.KindEndObject {
		_, err := d.ReadToken()
		return jsontext.Token{}, false, err
	}
	tok, err := d.ReadToken()
	return tok, err == nil, err
}

func idsParseHex(tok jsontext.Token, name string) ([]byte, error) {
	s := tok.String()
	if tok.Kind() == jsontext.KindString {
		if by, err := hex.DecodeString(s); err == nil {
			return by, nil
		}
	}
	return nil, idsJSONError(name, "invalid hex bytes "+s)
}

func idsJSONError(name, msg string) error {
	return errors.New("proto: " + name + ": " + msg)
}
