// Code generated by cotorp. DO NOT EDIT.
// source: otlp/trace.proto

package otlppb

import (
	"cmp"
	"encoding/base64"
	"encoding/binary"
	"encoding/hex"
	"encoding/json/jsontext"
	"errors"
	"slices"
	"strconv"
	"unicode/utf8"

	h "github.com/canonical/cotorp/internal/testprotos/otlp/internal/h"
	wktpb "github.com/canonical/cotorp/internal/testprotos/wkt"
)

const (
	traceE1 = "proto: field cotorp.test.otlp.Span.trace_state contains invalid UTF-8"
	traceE2 = "proto: field cotorp.test.otlp.Span.name contains invalid UTF-8"
	traceE3 = "proto: field cotorp.test.otlp.Span.CodesEntry.key contains invalid UTF-8"
	traceE4 = "proto: field cotorp.test.otlp.Status.message contains invalid UTF-8"
	traceE5 = "proto: field cotorp.test.otlp.AnyValue.string_value contains invalid UTF-8"
)

type Span_SpanKind int32

const (
	Span_SPAN_KIND_UNSPECIFIED Span_SpanKind = 0
	Span_SPAN_KIND_INTERNAL    Span_SpanKind = 1
	Span_SPAN_KIND_SERVER      Span_SpanKind = 2
	Span_SPAN_KIND_CLIENT      Span_SpanKind = 3
)

// Span_SpanKind_name maps Span_SpanKind numbers to their names, and Span_SpanKind_value the reverse.
var Span_SpanKind_name = map[int32]string{
	0: "SPAN_KIND_UNSPECIFIED",
	1: "SPAN_KIND_INTERNAL",
	2: "SPAN_KIND_SERVER",
	3: "SPAN_KIND_CLIENT",
}
var Span_SpanKind_value = h.Invert(Span_SpanKind_name)

// Enum returns a pointer to a copy of x.
func (x Span_SpanKind) Enum() *Span_SpanKind { return &x }

// String returns the name of x, or its number if it has no name.
func (x Span_SpanKind) String() string { return h.EnumString(Span_SpanKind_name, int32(x)) }

// IsValid reports whether x is a declared value of Span_SpanKind.
func (x Span_SpanKind) IsValid() bool { return x >= 0 && x <= 3 }

type Status_StatusCode int32

const (
	Status_STATUS_CODE_UNSET Status_StatusCode = 0
	Status_STATUS_CODE_OK    Status_StatusCode = 1
	Status_STATUS_CODE_ERROR Status_StatusCode = 2
)

// Status_StatusCode_name maps Status_StatusCode numbers to their names, and Status_StatusCode_value the reverse.
var Status_StatusCode_name = map[int32]string{
	0: "STATUS_CODE_UNSET",
	1: "STATUS_CODE_OK",
	2: "STATUS_CODE_ERROR",
}
var Status_StatusCode_value = h.Invert(Status_StatusCode_name)

// Enum returns a pointer to a copy of x.
func (x Status_StatusCode) Enum() *Status_StatusCode { return &x }

// String returns the name of x, or its number if it has no name.
func (x Status_StatusCode) String() string { return h.EnumString(Status_StatusCode_name, int32(x)) }

// IsValid reports whether x is a declared value of Status_StatusCode.
func (x Status_StatusCode) IsValid() bool { return x >= 0 && x <= 2 }

type Span struct {
	TraceId           []byte
	SpanId            []byte
	TraceState        string
	ParentSpanId      []byte
	Name              string
	Kind              Span_SpanKind
	StartTimeUnixNano uint64
	Links             []*Span_Link
	Status            *Status
	// Not OTLP: exercise repeated hex fields, base64 fields left alone, and
	// NullValue (always null) under -json_enum_numbers.
	HexList   [][]byte
	Plain     []byte
	NullValue *wktpb.NullValue
	Codes     map[string]Status_StatusCode

	u []byte
}

// Reset clears all fields of m.
func (m *Span) Reset()                       { *m = Span{} }
func (m *Span) z() *Span                     { return h.If(m == nil, &traceZSpan, m) }
func (m *Span) GetTraceId() []byte           { return m.z().TraceId }
func (m *Span) GetSpanId() []byte            { return m.z().SpanId }
func (m *Span) GetTraceState() string        { return m.z().TraceState }
func (m *Span) GetParentSpanId() []byte      { return m.z().ParentSpanId }
func (m *Span) GetName() string              { return m.z().Name }
func (m *Span) GetKind() Span_SpanKind       { return m.z().Kind }
func (m *Span) GetStartTimeUnixNano() uint64 { return m.z().StartTimeUnixNano }
func (m *Span) GetLinks() []*Span_Link       { return m.z().Links }
func (m *Span) GetStatus() *Status           { return m.z().Status }
func (m *Span) GetHexList() [][]byte         { return m.z().HexList }
func (m *Span) GetPlain() []byte             { return m.z().Plain }
func (m *Span) GetNullValue() wktpb.NullValue {
	return h.Deref(m.z().NullValue, wktpb.NullValue_NULL_VALUE)
}
func (m *Span) GetCodes() map[string]Status_StatusCode { return m.z().Codes }

// ProtoUnknownFields returns the raw bytes of fields that were not recognized when m was decoded.
func (m *Span) ProtoUnknownFields() []byte { return m.z().u }

// ProtoSize returns the size of the wire-format encoding of m.
func (m *Span) ProtoSize() (n int) {
	m = m.z()
	n += h.SizeLenField(1, len(m.TraceId))
	n += h.SizeLenField(1, len(m.SpanId))
	n += h.SizeLenField(1, len(m.TraceState))
	n += h.SizeLenField(1, len(m.ParentSpanId))
	n += h.SizeLenField(1, len(m.Name))
	n += h.SizeVarint(1, uint64(int64(m.Kind)))
	n += h.SizeFixed(1, h.Fixed64Size, m.StartTimeUnixNano != 0)
	n += h.SizeMsgs(1, m.Links, func(v *Span_Link) int { return v.ProtoSize() })
	n += h.SizeMsg(1, m.Status, func(v *Status) int { return v.ProtoSize() })
	n += h.SizeEach(2, m.HexList, h.BytesLen)
	n += h.SizeLenField(2, len(m.Plain))
	n += h.SizeOpt(2, m.NullValue, h.VarintLen)
	for k, v := range m.Codes {
		n += 2 + h.SizeLen(1+h.SizeLen(len(k))+1+h.VarintLen(v))
	}
	return n + len(m.u)
}

// MarshalBinary returns the wire-format encoding of m.
func (m *Span) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *Span) AppendBinary(b []byte) ([]byte, error) {
	return h.AppendBinary(b, m.ProtoSize(), m.ProtoMarshalToSizedBuffer)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must hold m.ProtoSize() bytes, and returns the count written, without checking required fields.
func (m *Span) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	m = m.z()
	i := h.CopyUnknown(b, len(b), m.u)
	if err := h.CheckUTF8(m.Name, traceE2, h.CheckUTF8(m.TraceState, traceE1, nil)); err != nil {
		return 0, err
	}
	if len(m.Codes) > 0 {
		for _, k := range slices.Backward(h.SortedKeys(m.Codes, make([]string, 0, len(m.Codes)))) {
			v := m.Codes[k]
			start := i
			i = h.PutVarint(b, h.PutVarint(b, i, uint64(int64(v))), h.MapValueField<<h.TagTypeBits|h.WireVarint)
			if !utf8.ValidString(k) {
				return 0, errors.New(traceE3)
			}
			i = h.PutVarint(b, h.PutVarint(b, i-copy(b[i-len(k):], k), uint64(len(k))), h.MapKeyField<<h.TagTypeBits|h.WireBytes)
			i = h.PutVarint(b, h.PutVarint(b, i, uint64(start-i)), 103<<h.TagTypeBits|h.WireBytes)
		}
	}
	if m.NullValue != nil {
		i = h.PutVarint(b, h.PutVarint(b, i, uint64(int64((*m.NullValue)))), 102<<h.TagTypeBits|h.WireVarint)
	}
	if len(m.Plain) > 0 {
		i = h.PutVarint(b, h.PutVarint(b, i-copy(b[i-len(m.Plain):], m.Plain), uint64(len(m.Plain))), 101<<h.TagTypeBits|h.WireBytes)
	}
	for _, v := range slices.Backward(m.HexList) {
		i = h.PutVarint(b, h.PutVarint(b, i-copy(b[i-len(v):], v), uint64(len(v))), 100<<h.TagTypeBits|h.WireBytes)
	}
	if m.Status != nil {
		n, err := m.Status.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = h.PutVarint(b, h.PutVarint(b, i-n, uint64(n)), 15<<h.TagTypeBits|h.WireBytes)
	}
	for _, v := range slices.Backward(m.Links) {
		n, err := v.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i = h.PutVarint(b, h.PutVarint(b, i-n, uint64(n)), 13<<h.TagTypeBits|h.WireBytes)
	}
	i = h.PutFixed64Field(b, i, uint64(m.StartTimeUnixNano), 7<<h.TagTypeBits|h.WireFixed64)
	i = h.PutVarintField(b, i, uint64(int64(m.Kind)), 6<<h.TagTypeBits|h.WireVarint)
	i = h.PutStringField(b, i, m.Name, 5<<h.TagTypeBits|h.WireBytes)
	i = h.PutBytesField(b, i, m.ParentSpanId, 4<<h.TagTypeBits|h.WireBytes)
	i = h.PutStringField(b, i, m.TraceState, 3<<h.TagTypeBits|h.WireBytes)
	i = h.PutBytesField(b, i, m.SpanId, 2<<h.TagTypeBits|h.WireBytes)
	i = h.PutBytesField(b, i, m.TraceId, 1<<h.TagTypeBits|h.WireBytes)
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the wire-format message in b.
func (m *Span) UnmarshalBinary(b []byte) error { *m = Span{}; return m.ProtoMergeDepth(b, 0) }

// ProtoMerge decodes the wire-format message in b and merges it into m, without checking required fields.
func (m *Span) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *Span) ProtoMergeDepth(b []byte, depth int) error {
	var x, err = []byte(nil), h.Depth(depth)
	for t, n := binary.Uvarint(b); n > 0 && err == nil; t, n = binary.Uvarint(b) {
		b = b[n:]
		switch t {
		case 1<<h.TagTypeBits | h.WireBytes:
			n = h.Bytes(b, &m.TraceId)
		case 2<<h.TagTypeBits | h.WireBytes:
			n = h.Bytes(b, &m.SpanId)
		case 3<<h.TagTypeBits | h.WireBytes:
			n, err = h.String(b, &m.TraceState, traceE1)
		case 4<<h.TagTypeBits | h.WireBytes:
			n = h.Bytes(b, &m.ParentSpanId)
		case 5<<h.TagTypeBits | h.WireBytes:
			n, err = h.String(b, &m.Name, traceE2)
		case 6<<h.TagTypeBits | h.WireVarint:
			n = h.Varint(b, &m.Kind)
		case 7<<h.TagTypeBits | h.WireFixed64:
			n = h.Fixed64(b, &m.StartTimeUnixNano)
		case 13<<h.TagTypeBits | h.WireBytes:
			x, n = h.ReadBytes(b)
			err = h.Alloc(h.Grow(&m.Links)).ProtoMergeDepth(x, depth+1)
		case 15<<h.TagTypeBits | h.WireBytes:
			x, n = h.ReadBytes(b)
			err = h.Alloc(&m.Status).ProtoMergeDepth(x, depth+1)
		case 100<<h.TagTypeBits | h.WireBytes:
			n = h.Bytes(b, h.Grow(&m.HexList))
		case 101<<h.TagTypeBits | h.WireBytes:
			n = h.Bytes(b, &m.Plain)
		case 102<<h.TagTypeBits | h.WireVarint:
			n = h.Varint(b, h.New(&m.NullValue))
		case 103<<h.TagTypeBits | h.WireBytes:
			x, n = h.ReadBytes(b)
			mk, mv := "", Status_StatusCode(0)
			for t, k := binary.Uvarint(x); k > 0; t, k = binary.Uvarint(x) {
				x = x[k:]
				switch t {
				case h.MapKeyField<<h.TagTypeBits | h.WireBytes:
					k, err = h.String(x, &mk, traceE3)
				case h.MapValueField<<h.TagTypeBits | h.WireVarint:
					k = h.Varint(x, &mv)
				default:
					k, err = h.SkipField(x, t, depth)
				}
				if k <= 0 || err != nil {
					return cmp.Or(err, errors.New(h.ErrParse))
				}
				x = x[k:]
			}
			h.MapSet(&m.Codes, mk, mv)
			err = h.End(x, err)
		default:
			n, err = h.Unknown(b, t, depth, &m.u)
		}
		if n <= 0 || err != nil {
			return cmp.Or(err, errors.New(h.ErrParse))
		}
		b = b[n:]
	}
	return h.End(b, err)
}

// ProtoCheckInitialized returns an error if a required field of m or of a message in m is not set.
func (m *Span) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *Span) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e, implementing json.MarshalerTo from encoding/json/v2.
func (m *Span) MarshalJSONTo(e *jsontext.Encoder) error {
	return h.MarshalTo(e, m.ProtoAppendJSON)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b, without checking required fields.
func (m *Span) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	m, start := m.z(), len(b)
	if len(m.TraceId) > 0 {
		b = append(hex.AppendEncode(append(b, ",\"traceId\":\""...), m.TraceId), '"')
	}
	if len(m.SpanId) > 0 {
		b = append(hex.AppendEncode(append(b, ",\"spanId\":\""...), m.SpanId), '"')
	}
	if len(m.TraceState) > 0 {
		b, err = h.Quote(append(b, ",\"traceState\":"...), m.TraceState, err)
	}
	if len(m.ParentSpanId) > 0 {
		b = append(hex.AppendEncode(append(b, ",\"parentSpanId\":\""...), m.ParentSpanId), '"')
	}
	if len(m.Name) > 0 {
		b, err = h.Quote(append(b, ",\"name\":"...), m.Name, err)
	}
	if m.Kind != 0 {
		b = strconv.AppendInt(append(b, ",\"kind\":"...), int64(m.Kind), 10)
	}
	if m.StartTimeUnixNano != 0 {
		b = append(strconv.AppendUint(append(b, ",\"startTimeUnixNano\":\""...), m.StartTimeUnixNano, 10), '"')
	}
	b, err = h.AppendList(b, ",\"links\":[", m.Links, (*Span_Link).ProtoAppendJSON, err)
	b, err = h.AppendMsg(b, ",\"status\":", m.Status, func(v *Status, b []byte) ([]byte, error) { return v.ProtoAppendJSON(b) }, err)
	b, err = h.AppendList(b, ",\"hexList\":[", m.HexList, func(v []byte, b []byte) ([]byte, error) { return append(hex.AppendEncode(append(b, '"'), v), '"'), nil }, err)
	if len(m.Plain) > 0 {
		b = append(base64.StdEncoding.AppendEncode(append(b, ",\"plain\":\""...), m.Plain), '"')
	}
	if m.NullValue != nil {
		b = append(b, ",\"nullValue\":null"...)
	}
	b, err = h.AppendMap(b, ",\"codes\":{", m.Codes, func(k string, b []byte) ([]byte, error) { return jsontext.AppendQuote(b, k) }, func(v Status_StatusCode, b []byte) ([]byte, error) { return strconv.AppendInt(b, int64(v), 10), nil }, err)
	return h.CloseObject(b, start), err
}

// UnmarshalJSON replaces the contents of m with the ProtoJSON value in b.
func (m *Span) UnmarshalJSON(b []byte) error { *m = Span{}; return m.ProtoMergeJSON(b) }

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m, without checking required fields.
func (m *Span) ProtoMergeJSON(b []byte) error {
	return h.MergeJSON(b, "cotorp.test.otlp.Span", m.ProtoMergeJSONFrom)
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value read from d, implementing json.UnmarshalerFrom from encoding/json/v2.
func (m *Span) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	*m = Span{}
	return h.MergeFrom(d, m.ProtoMergeJSONFrom)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it into m, without checking required fields; d should reject invalid UTF-8, as jsontext decoders do by default.
func (m *Span) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	var seen [13]bool
	for kt, err := h.OpenObject(d, "cotorp.test.otlp.Span"); kt.Kind() != jsontext.KindEndObject; kt, err = h.NextKey(d, err) {
		if err != nil {
			return err
		}
		switch key := kt.String(); key {
		case "traceId", "trace_id":
			err = h.Field(d, &seen[0], key, "cotorp.test.otlp.Span", &m.TraceId, h.JSONHex)
		case "spanId", "span_id":
			err = h.Field(d, &seen[1], key, "cotorp.test.otlp.Span", &m.SpanId, h.JSONHex)
		case "traceState", "trace_state":
			err = h.Field(d, &seen[2], key, "cotorp.test.otlp.Span", &m.TraceState, h.JSONString)
		case "parentSpanId", "parent_span_id":
			err = h.Field(d, &seen[3], key, "cotorp.test.otlp.Span", &m.ParentSpanId, h.JSONHex)
		case "name":
			err = h.Field(d, &seen[4], key, "cotorp.test.otlp.Span", &m.Name, h.JSONString)
		case "kind":
			err = h.Field(d, &seen[5], key, "cotorp.test.otlp.Span", &m.Kind, traceJSpanSpanKind)
		case "startTimeUnixNano", "start_time_unix_nano":
			err = h.Field(d, &seen[6], key, "cotorp.test.otlp.Span", &m.StartTimeUnixNano, h.JSONUint)
		case "links":
			err = h.RepField(d, &seen[7], key, "cotorp.test.otlp.Span", &m.Links, false, h.JSONMsg)
		case "status":
			err = h.Field(d, &seen[8], key, "cotorp.test.otlp.Span", &m.Status, h.JSONMsg)
		case "hexList", "hex_list":
			err = h.RepField(d, &seen[9], key, "cotorp.test.otlp.Span", &m.HexList, false, h.JSONHex)
		case "plain":
			err = h.Field(d, &seen[10], key, "cotorp.test.otlp.Span", &m.Plain, h.JSONBytes)
		case "nullValue", "null_value":
			err = h.Field(d, &seen[11], key, "cotorp.test.otlp.Span", h.New(&m.NullValue), traceJGoogleProtobufNullValue)
		case "codes":
			err = h.MapField(d, &seen[12], key, "cotorp.test.otlp.Span", "codes", &m.Codes, false, h.StringKey, traceJStatusStatusCode)
		default:
			err = d.SkipValue()
		}
	}
	return nil
}

func traceJSpanSpanKind(d *jsontext.Decoder, p *Span_SpanKind, name string) error {
	return h.JSONEnum(d, p, Span_SpanKind_value, name, "cotorp.test.otlp.Span.SpanKind", false)
}

func traceJGoogleProtobufNullValue(d *jsontext.Decoder, p *wktpb.NullValue, name string) error {
	return h.JSONEnum(d, p, wktpb.NullValue_value, name, "google.protobuf.NullValue", true)
}

func traceJStatusStatusCode(d *jsontext.Decoder, p *Status_StatusCode, name string) error {
	return h.JSONEnum(d, p, Status_StatusCode_value, name, "cotorp.test.otlp.Status.StatusCode", false)
}

type Span_Link struct {
	TraceId []byte
	SpanId  []byte

	u []byte
}

// Reset clears all fields of m.
func (m *Span_Link) Reset()             { *m = Span_Link{} }
func (m *Span_Link) z() *Span_Link      { return h.If(m == nil, &traceZSpan_Link, m) }
func (m *Span_Link) GetTraceId() []byte { return m.z().TraceId }
func (m *Span_Link) GetSpanId() []byte  { return m.z().SpanId }

// ProtoUnknownFields returns the raw bytes of fields that were not recognized when m was decoded.
func (m *Span_Link) ProtoUnknownFields() []byte { return m.z().u }

// ProtoSize returns the size of the wire-format encoding of m.
func (m *Span_Link) ProtoSize() (n int) {
	m = m.z()
	n += h.SizeLenField(1, len(m.TraceId))
	n += h.SizeLenField(1, len(m.SpanId))
	return n + len(m.u)
}

// MarshalBinary returns the wire-format encoding of m.
func (m *Span_Link) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *Span_Link) AppendBinary(b []byte) ([]byte, error) {
	return h.AppendBinary(b, m.ProtoSize(), m.ProtoMarshalToSizedBuffer)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must hold m.ProtoSize() bytes, and returns the count written, without checking required fields.
func (m *Span_Link) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	m = m.z()
	i := h.CopyUnknown(b, len(b), m.u)
	i = h.PutBytesField(b, i, m.SpanId, 2<<h.TagTypeBits|h.WireBytes)
	i = h.PutBytesField(b, i, m.TraceId, 1<<h.TagTypeBits|h.WireBytes)
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the wire-format message in b.
func (m *Span_Link) UnmarshalBinary(b []byte) error { *m = Span_Link{}; return m.ProtoMergeDepth(b, 0) }

// ProtoMerge decodes the wire-format message in b and merges it into m, without checking required fields.
func (m *Span_Link) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *Span_Link) ProtoMergeDepth(b []byte, depth int) error {
	err := h.Depth(depth)
	for t, n := binary.Uvarint(b); n > 0 && err == nil; t, n = binary.Uvarint(b) {
		b = b[n:]
		switch t {
		case 1<<h.TagTypeBits | h.WireBytes:
			n = h.Bytes(b, &m.TraceId)
		case 2<<h.TagTypeBits | h.WireBytes:
			n = h.Bytes(b, &m.SpanId)
		default:
			n, err = h.Unknown(b, t, depth, &m.u)
		}
		if n <= 0 || err != nil {
			return cmp.Or(err, errors.New(h.ErrParse))
		}
		b = b[n:]
	}
	return h.End(b, err)
}

// ProtoCheckInitialized returns an error if a required field of m or of a message in m is not set.
func (m *Span_Link) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *Span_Link) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e, implementing json.MarshalerTo from encoding/json/v2.
func (m *Span_Link) MarshalJSONTo(e *jsontext.Encoder) error {
	return h.MarshalTo(e, m.ProtoAppendJSON)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b, without checking required fields.
func (m *Span_Link) ProtoAppendJSON(b []byte) ([]byte, error) {
	m, start := m.z(), len(b)
	if len(m.TraceId) > 0 {
		b = append(hex.AppendEncode(append(b, ",\"traceId\":\""...), m.TraceId), '"')
	}
	if len(m.SpanId) > 0 {
		b = append(hex.AppendEncode(append(b, ",\"spanId\":\""...), m.SpanId), '"')
	}
	return h.CloseObject(b, start), nil
}

// UnmarshalJSON replaces the contents of m with the ProtoJSON value in b.
func (m *Span_Link) UnmarshalJSON(b []byte) error { *m = Span_Link{}; return m.ProtoMergeJSON(b) }

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m, without checking required fields.
func (m *Span_Link) ProtoMergeJSON(b []byte) error {
	return h.MergeJSON(b, "cotorp.test.otlp.Span.Link", m.ProtoMergeJSONFrom)
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value read from d, implementing json.UnmarshalerFrom from encoding/json/v2.
func (m *Span_Link) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	*m = Span_Link{}
	return h.MergeFrom(d, m.ProtoMergeJSONFrom)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it into m, without checking required fields; d should reject invalid UTF-8, as jsontext decoders do by default.
func (m *Span_Link) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	var seen [2]bool
	for kt, err := h.OpenObject(d, "cotorp.test.otlp.Span.Link"); kt.Kind() != jsontext.KindEndObject; kt, err = h.NextKey(d, err) {
		if err != nil {
			return err
		}
		switch key := kt.String(); key {
		case "traceId", "trace_id":
			err = h.Field(d, &seen[0], key, "cotorp.test.otlp.Span.Link", &m.TraceId, h.JSONHex)
		case "spanId", "span_id":
			err = h.Field(d, &seen[1], key, "cotorp.test.otlp.Span.Link", &m.SpanId, h.JSONHex)
		default:
			err = d.SkipValue()
		}
	}
	return nil
}

type Status struct {
	Message string
	Code    Status_StatusCode

	u []byte
}

// Reset clears all fields of m.
func (m *Status) Reset()                     { *m = Status{} }
func (m *Status) z() *Status                 { return h.If(m == nil, &traceZStatus, m) }
func (m *Status) GetMessage() string         { return m.z().Message }
func (m *Status) GetCode() Status_StatusCode { return m.z().Code }

// ProtoUnknownFields returns the raw bytes of fields that were not recognized when m was decoded.
func (m *Status) ProtoUnknownFields() []byte { return m.z().u }

// ProtoSize returns the size of the wire-format encoding of m.
func (m *Status) ProtoSize() (n int) {
	m = m.z()
	n += h.SizeLenField(1, len(m.Message))
	n += h.SizeVarint(1, uint64(int64(m.Code)))
	return n + len(m.u)
}

// MarshalBinary returns the wire-format encoding of m.
func (m *Status) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *Status) AppendBinary(b []byte) ([]byte, error) {
	return h.AppendBinary(b, m.ProtoSize(), m.ProtoMarshalToSizedBuffer)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must hold m.ProtoSize() bytes, and returns the count written, without checking required fields.
func (m *Status) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	m = m.z()
	i := h.CopyUnknown(b, len(b), m.u)
	if err := h.CheckUTF8(m.Message, traceE4, nil); err != nil {
		return 0, err
	}
	i = h.PutVarintField(b, i, uint64(int64(m.Code)), 3<<h.TagTypeBits|h.WireVarint)
	i = h.PutStringField(b, i, m.Message, 2<<h.TagTypeBits|h.WireBytes)
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the wire-format message in b.
func (m *Status) UnmarshalBinary(b []byte) error { *m = Status{}; return m.ProtoMergeDepth(b, 0) }

// ProtoMerge decodes the wire-format message in b and merges it into m, without checking required fields.
func (m *Status) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *Status) ProtoMergeDepth(b []byte, depth int) error {
	err := h.Depth(depth)
	for t, n := binary.Uvarint(b); n > 0 && err == nil; t, n = binary.Uvarint(b) {
		b = b[n:]
		switch t {
		case 2<<h.TagTypeBits | h.WireBytes:
			n, err = h.String(b, &m.Message, traceE4)
		case 3<<h.TagTypeBits | h.WireVarint:
			n = h.Varint(b, &m.Code)
		default:
			n, err = h.Unknown(b, t, depth, &m.u)
		}
		if n <= 0 || err != nil {
			return cmp.Or(err, errors.New(h.ErrParse))
		}
		b = b[n:]
	}
	return h.End(b, err)
}

// ProtoCheckInitialized returns an error if a required field of m or of a message in m is not set.
func (m *Status) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *Status) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e, implementing json.MarshalerTo from encoding/json/v2.
func (m *Status) MarshalJSONTo(e *jsontext.Encoder) error {
	return h.MarshalTo(e, m.ProtoAppendJSON)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b, without checking required fields.
func (m *Status) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	m, start := m.z(), len(b)
	if len(m.Message) > 0 {
		b, err = h.Quote(append(b, ",\"message\":"...), m.Message, err)
	}
	if m.Code != 0 {
		b = strconv.AppendInt(append(b, ",\"code\":"...), int64(m.Code), 10)
	}
	return h.CloseObject(b, start), err
}

// UnmarshalJSON replaces the contents of m with the ProtoJSON value in b.
func (m *Status) UnmarshalJSON(b []byte) error { *m = Status{}; return m.ProtoMergeJSON(b) }

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m, without checking required fields.
func (m *Status) ProtoMergeJSON(b []byte) error {
	return h.MergeJSON(b, "cotorp.test.otlp.Status", m.ProtoMergeJSONFrom)
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value read from d, implementing json.UnmarshalerFrom from encoding/json/v2.
func (m *Status) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	*m = Status{}
	return h.MergeFrom(d, m.ProtoMergeJSONFrom)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it into m, without checking required fields; d should reject invalid UTF-8, as jsontext decoders do by default.
func (m *Status) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	var seen [2]bool
	for kt, err := h.OpenObject(d, "cotorp.test.otlp.Status"); kt.Kind() != jsontext.KindEndObject; kt, err = h.NextKey(d, err) {
		if err != nil {
			return err
		}
		switch key := kt.String(); key {
		case "message":
			err = h.Field(d, &seen[0], key, "cotorp.test.otlp.Status", &m.Message, h.JSONString)
		case "code":
			err = h.Field(d, &seen[1], key, "cotorp.test.otlp.Status", &m.Code, traceJStatusStatusCode)
		default:
			err = d.SkipValue()
		}
	}
	return nil
}

type AnyValue struct {
	// Types that are valid to be assigned to Value:
	//
	//	*AnyValue_StringValue
	//	*AnyValue_BytesValue
	Value isAnyValue_Value

	u []byte
}

// Reset clears all fields of m.
func (m *AnyValue) Reset()                     { *m = AnyValue{} }
func (m *AnyValue) z() *AnyValue               { return h.If(m == nil, &traceZAnyValue, m) }
func (m *AnyValue) GetValue() isAnyValue_Value { return m.z().Value }
func (m *AnyValue) GetStringValue() string {
	x, _ := m.GetValue().(*AnyValue_StringValue)
	return h.If(x == nil, new(AnyValue_StringValue), x).StringValue
}
func (m *AnyValue) GetBytesValue() []byte {
	x, _ := m.GetValue().(*AnyValue_BytesValue)
	return h.If(x == nil, new(AnyValue_BytesValue), x).BytesValue
}

// ProtoUnknownFields returns the raw bytes of fields that were not recognized when m was decoded.
func (m *AnyValue) ProtoUnknownFields() []byte { return m.z().u }

type isAnyValue_Value interface{ isAnyValue_Value() }
type AnyValue_StringValue struct{ StringValue string }
type AnyValue_BytesValue struct{ BytesValue []byte }

func (*AnyValue_StringValue) isAnyValue_Value() {}
func (*AnyValue_BytesValue) isAnyValue_Value()  {}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *AnyValue) ProtoSize() (n int) {
	m = m.z()
	switch o := m.Value.(type) {
	case *AnyValue_StringValue:
		n += 1 + h.SizeLen(len(o.StringValue))
	case *AnyValue_BytesValue:
		n += 1 + h.SizeLen(len(o.BytesValue))
	}
	return n + len(m.u)
}

// MarshalBinary returns the wire-format encoding of m.
func (m *AnyValue) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *AnyValue) AppendBinary(b []byte) ([]byte, error) {
	return h.AppendBinary(b, m.ProtoSize(), m.ProtoMarshalToSizedBuffer)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must hold m.ProtoSize() bytes, and returns the count written, without checking required fields.
func (m *AnyValue) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	m = m.z()
	i := h.CopyUnknown(b, len(b), m.u)
	if err := h.CheckUTF8(m.GetStringValue(), traceE5, nil); err != nil {
		return 0, err
	}
	if o, ok := m.Value.(*AnyValue_BytesValue); ok {
		i = h.PutVarint(b, h.PutVarint(b, i-copy(b[i-len(o.BytesValue):], o.BytesValue), uint64(len(o.BytesValue))), 7<<h.TagTypeBits|h.WireBytes)
	}
	if o, ok := m.Value.(*AnyValue_StringValue); ok {
		i = h.PutVarint(b, h.PutVarint(b, i-copy(b[i-len(o.StringValue):], o.StringValue), uint64(len(o.StringValue))), 1<<h.TagTypeBits|h.WireBytes)
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the wire-format message in b.
func (m *AnyValue) UnmarshalBinary(b []byte) error { *m = AnyValue{}; return m.ProtoMergeDepth(b, 0) }

// ProtoMerge decodes the wire-format message in b and merges it into m, without checking required fields.
func (m *AnyValue) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *AnyValue) ProtoMergeDepth(b []byte, depth int) error {
	err := h.Depth(depth)
	for t, n := binary.Uvarint(b); n > 0 && err == nil; t, n = binary.Uvarint(b) {
		b = b[n:]
		switch t {
		case 1<<h.TagTypeBits | h.WireBytes:
			o := new(AnyValue_StringValue)
			n, err = h.String(b, &o.StringValue, traceE5)
			m.Value = o
		case 7<<h.TagTypeBits | h.WireBytes:
			o := new(AnyValue_BytesValue)
			n, m.Value = h.Bytes(b, &o.BytesValue), o
		default:
			n, err = h.Unknown(b, t, depth, &m.u)
		}
		if n <= 0 || err != nil {
			return cmp.Or(err, errors.New(h.ErrParse))
		}
		b = b[n:]
	}
	return h.End(b, err)
}

// ProtoCheckInitialized returns an error if a required field of m or of a message in m is not set.
func (m *AnyValue) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *AnyValue) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e, implementing json.MarshalerTo from encoding/json/v2.
func (m *AnyValue) MarshalJSONTo(e *jsontext.Encoder) error {
	return h.MarshalTo(e, m.ProtoAppendJSON)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b, without checking required fields.
func (m *AnyValue) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	m, start := m.z(), len(b)
	if o, ok := m.Value.(*AnyValue_StringValue); ok {
		b, err = h.Quote(append(b, ",\"stringValue\":"...), o.StringValue, err)
	}
	if o, ok := m.Value.(*AnyValue_BytesValue); ok {
		b = append(base64.StdEncoding.AppendEncode(append(b, ",\"bytesValue\":\""...), o.BytesValue), '"')
	}
	return h.CloseObject(b, start), err
}

// UnmarshalJSON replaces the contents of m with the ProtoJSON value in b.
func (m *AnyValue) UnmarshalJSON(b []byte) error { *m = AnyValue{}; return m.ProtoMergeJSON(b) }

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m, without checking required fields.
func (m *AnyValue) ProtoMergeJSON(b []byte) error {
	return h.MergeJSON(b, "cotorp.test.otlp.AnyValue", m.ProtoMergeJSONFrom)
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value read from d, implementing json.UnmarshalerFrom from encoding/json/v2.
func (m *AnyValue) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	*m = AnyValue{}
	return h.MergeFrom(d, m.ProtoMergeJSONFrom)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it into m, without checking required fields; d should reject invalid UTF-8, as jsontext decoders do by default.
func (m *AnyValue) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	seen, oneofs := [2]bool{}, [1]bool{}
	for kt, err := h.OpenObject(d, "cotorp.test.otlp.AnyValue"); kt.Kind() != jsontext.KindEndObject; kt, err = h.NextKey(d, err) {
		if err != nil {
			return err
		}
		switch key := kt.String(); key {
		case "stringValue", "string_value":
			o := new(AnyValue_StringValue)
			err = h.OneofField(d, &seen[0], &oneofs[0], key, "cotorp.test.otlp.AnyValue", "value", &m.Value, isAnyValue_Value(o), &o.StringValue, false, h.JSONString)
		case "bytesValue", "bytes_value":
			o := new(AnyValue_BytesValue)
			err = h.OneofField(d, &seen[1], &oneofs[0], key, "cotorp.test.otlp.AnyValue", "value", &m.Value, isAnyValue_Value(o), &o.BytesValue, false, h.JSONBytes)
		default:
			err = d.SkipValue()
		}
	}
	return nil
}

type Nothing struct {
	u []byte
}

// Reset clears all fields of m.
func (m *Nothing) Reset()      { *m = Nothing{} }
func (m *Nothing) z() *Nothing { return h.If(m == nil, &traceZNothing, m) }

// ProtoUnknownFields returns the raw bytes of fields that were not recognized when m was decoded.
func (m *Nothing) ProtoUnknownFields() []byte { return m.z().u }

// ProtoSize returns the size of the wire-format encoding of m.
func (m *Nothing) ProtoSize() (n int) {
	m = m.z()
	return n + len(m.u)
}

// MarshalBinary returns the wire-format encoding of m.
func (m *Nothing) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *Nothing) AppendBinary(b []byte) ([]byte, error) {
	return h.AppendBinary(b, m.ProtoSize(), m.ProtoMarshalToSizedBuffer)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must hold m.ProtoSize() bytes, and returns the count written, without checking required fields.
func (m *Nothing) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	m = m.z()
	i := h.CopyUnknown(b, len(b), m.u)
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the wire-format message in b.
func (m *Nothing) UnmarshalBinary(b []byte) error { *m = Nothing{}; return m.ProtoMergeDepth(b, 0) }

// ProtoMerge decodes the wire-format message in b and merges it into m, without checking required fields.
func (m *Nothing) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *Nothing) ProtoMergeDepth(b []byte, depth int) error {
	err := h.Depth(depth)
	for t, n := binary.Uvarint(b); n > 0 && err == nil; t, n = binary.Uvarint(b) {
		b = b[n:]
		n, err = h.Unknown(b, t, depth, &m.u)
		if n <= 0 || err != nil {
			return cmp.Or(err, errors.New(h.ErrParse))
		}
		b = b[n:]
	}
	return h.End(b, err)
}

// ProtoCheckInitialized returns an error if a required field of m or of a message in m is not set.
func (m *Nothing) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *Nothing) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e, implementing json.MarshalerTo from encoding/json/v2.
func (m *Nothing) MarshalJSONTo(e *jsontext.Encoder) error {
	return h.MarshalTo(e, m.ProtoAppendJSON)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b, without checking required fields.
func (m *Nothing) ProtoAppendJSON(b []byte) ([]byte, error) {
	m, start := m.z(), len(b)
	return h.CloseObject(b, start), nil
}

// UnmarshalJSON replaces the contents of m with the ProtoJSON value in b.
func (m *Nothing) UnmarshalJSON(b []byte) error { *m = Nothing{}; return m.ProtoMergeJSON(b) }

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m, without checking required fields.
func (m *Nothing) ProtoMergeJSON(b []byte) error {
	return h.MergeJSON(b, "cotorp.test.otlp.Nothing", m.ProtoMergeJSONFrom)
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value read from d, implementing json.UnmarshalerFrom from encoding/json/v2.
func (m *Nothing) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	*m = Nothing{}
	return h.MergeFrom(d, m.ProtoMergeJSONFrom)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it into m, without checking required fields; d should reject invalid UTF-8, as jsontext decoders do by default.
func (m *Nothing) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	for kt, err := h.OpenObject(d, "cotorp.test.otlp.Nothing"); kt.Kind() != jsontext.KindEndObject; kt, err = h.NextKey(d, err) {
		if err != nil {
			return err
		}
		err = d.SkipValue()
	}
	return nil
}

var (
	traceZSpan      Span
	traceZSpan_Link Span_Link
	traceZStatus    Status
	traceZAnyValue  AnyValue
	traceZNothing   Nothing
)
