// Code generated by cotorp. DO NOT EDIT.
// source: otlp/trace.proto

package otlppb

import (
	"bytes"
	"encoding/base64"
	"encoding/binary"
	"encoding/hex"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"io"
	"math"
	"math/big"
	"math/bits"
	"slices"
	"strconv"
	"strings"
	"unicode/utf8"

	wktpb "github.com/canonical/cotorp/internal/testprotos/wkt"
)

// Wire types.
const (
	traceWireVarint     = 0
	traceWireFixed64    = 1
	traceWireBytes      = 2
	traceWireStartGroup = 3
	traceWireEndGroup   = 4
	traceWireFixed32    = 5
)

// A tag holds the field number above the wire type in its low three bits.
const (
	traceTagTypeBits    = 3
	traceTagTypeMask    = 1<<3 - 1
	traceMaxFieldNumber = 1<<29 - 1
)

// Map entries are encoded as messages with these field numbers.
const (
	traceMapKeyField   = 1
	traceMapValueField = 2
)

// Encoded sizes.
const (
	traceFixed32Size       = 4
	traceFixed64Size       = 8
	traceVarintPayloadBits = 7    // value bits per varint byte
	traceVarintContBit     = 0x80 // set on every varint byte but the last
)

// Decoding limits.
const (
	traceMaxDepth      = 10000 // maximum message and group nesting
	traceSkipStackSize = 16    // group nesting tracked without allocating
)

// ProtoJSON scalar parse classes.
const (
	traceClassNone     = 0
	traceClassSigned   = 1
	traceClassUnsigned = 2
	traceClassString   = 5
	traceClassBytes    = 6
	traceClassHex      = 7
	traceClassEnum     = 8
)

// ProtoJSON limits.
const (
	traceMaxJSONExponent = 100 // bounds exact integer parsing of exponent forms
	traceBase64Quantum   = 4   // base64 characters per padded block
)

// Error messages used more than once.
const (
	traceErrSizeChanged             = "proto: message size changed during marshal"
	traceSpanCodesEntryKeyErrUTF8   = "proto: field cotorp.test.otlp.Span.CodesEntry.key contains invalid UTF-8"
	traceSpanNameErrUTF8            = "proto: field cotorp.test.otlp.Span.name contains invalid UTF-8"
	traceSpanTraceStateErrUTF8      = "proto: field cotorp.test.otlp.Span.trace_state contains invalid UTF-8"
	traceErrParse                   = "proto: cannot parse invalid wire-format data"
	traceErrDepth                   = "proto: exceeded maximum recursion depth"
	traceSpanErrNotObject           = "proto: cotorp.test.otlp.Span: expected a JSON object"
	traceSpanErrInvalidInteger      = "proto: cotorp.test.otlp.Span: invalid integer "
	traceSpanErrInvalidBytes        = "proto: cotorp.test.otlp.Span: invalid bytes "
	traceSpanErrInvalidHex          = "proto: cotorp.test.otlp.Span: invalid hex bytes "
	traceSpanLinkErrInvalidHex      = "proto: cotorp.test.otlp.Span.Link: invalid hex bytes "
	traceStatusMessageErrUTF8       = "proto: field cotorp.test.otlp.Status.message contains invalid UTF-8"
	traceStatusErrInvalidInteger    = "proto: cotorp.test.otlp.Status: invalid integer "
	traceAnyValueStringValueErrUTF8 = "proto: field cotorp.test.otlp.AnyValue.string_value contains invalid UTF-8"
	traceAnyValueErrInvalidBytes    = "proto: cotorp.test.otlp.AnyValue: invalid bytes "
)

type Span_SpanKind int32

const (
	Span_SPAN_KIND_UNSPECIFIED Span_SpanKind = 0
	Span_SPAN_KIND_INTERNAL    Span_SpanKind = 1
	Span_SPAN_KIND_SERVER      Span_SpanKind = 2
	Span_SPAN_KIND_CLIENT      Span_SpanKind = 3
)

// Span_SpanKind_name maps Span_SpanKind numbers to their names.
var Span_SpanKind_name = map[int32]string{
	0: "SPAN_KIND_UNSPECIFIED",
	1: "SPAN_KIND_INTERNAL",
	2: "SPAN_KIND_SERVER",
	3: "SPAN_KIND_CLIENT",
}

// Span_SpanKind_value maps Span_SpanKind names to their numbers.
var Span_SpanKind_value = map[string]int32{
	"SPAN_KIND_UNSPECIFIED": 0,
	"SPAN_KIND_INTERNAL":    1,
	"SPAN_KIND_SERVER":      2,
	"SPAN_KIND_CLIENT":      3,
}

// Enum returns a pointer to a copy of x.
func (x Span_SpanKind) Enum() *Span_SpanKind { return &x }

// String returns the name of x, or its number if it has no name.
func (x Span_SpanKind) String() string {
	if s, ok := Span_SpanKind_name[int32(x)]; ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// IsValid reports whether x is a declared value of Span_SpanKind.
func (x Span_SpanKind) IsValid() bool {
	switch x {
	case Span_SPAN_KIND_UNSPECIFIED, Span_SPAN_KIND_INTERNAL, Span_SPAN_KIND_SERVER, Span_SPAN_KIND_CLIENT:
		return true
	}
	return false
}

type Status_StatusCode int32

const (
	Status_STATUS_CODE_UNSET Status_StatusCode = 0
	Status_STATUS_CODE_OK    Status_StatusCode = 1
	Status_STATUS_CODE_ERROR Status_StatusCode = 2
)

// Status_StatusCode_name maps Status_StatusCode numbers to their names.
var Status_StatusCode_name = map[int32]string{
	0: "STATUS_CODE_UNSET",
	1: "STATUS_CODE_OK",
	2: "STATUS_CODE_ERROR",
}

// Status_StatusCode_value maps Status_StatusCode names to their numbers.
var Status_StatusCode_value = map[string]int32{
	"STATUS_CODE_UNSET": 0,
	"STATUS_CODE_OK":    1,
	"STATUS_CODE_ERROR": 2,
}

// Enum returns a pointer to a copy of x.
func (x Status_StatusCode) Enum() *Status_StatusCode { return &x }

// String returns the name of x, or its number if it has no name.
func (x Status_StatusCode) String() string {
	if s, ok := Status_StatusCode_name[int32(x)]; ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// IsValid reports whether x is a declared value of Status_StatusCode.
func (x Status_StatusCode) IsValid() bool {
	switch x {
	case Status_STATUS_CODE_UNSET, Status_STATUS_CODE_OK, Status_STATUS_CODE_ERROR:
		return true
	}
	return false
}

type Span struct {
	TraceId           []byte
	SpanId            []byte
	TraceState        string
	ParentSpanId      []byte
	Name              string
	Kind              Span_SpanKind
	StartTimeUnixNano uint64
	Links             []*Span_Link
	Status            *Status
	// Not OTLP: exercise repeated hex fields, base64 fields left alone, and
	// NullValue (always null) under -json_enum_numbers.
	HexList   [][]byte
	Plain     []byte
	NullValue *wktpb.NullValue
	Codes     map[string]Status_StatusCode

	unknownFields []byte
}

// Reset clears all fields of m.
func (m *Span) Reset() { *m = Span{} }

func (m *Span) GetTraceId() []byte {
	if m != nil {
		return m.TraceId
	}
	return nil
}

func (m *Span) GetSpanId() []byte {
	if m != nil {
		return m.SpanId
	}
	return nil
}

func (m *Span) GetTraceState() string {
	if m != nil {
		return m.TraceState
	}
	return ""
}

func (m *Span) GetParentSpanId() []byte {
	if m != nil {
		return m.ParentSpanId
	}
	return nil
}

func (m *Span) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Span) GetKind() Span_SpanKind {
	if m != nil {
		return m.Kind
	}
	return Span_SPAN_KIND_UNSPECIFIED
}

func (m *Span) GetStartTimeUnixNano() uint64 {
	if m != nil {
		return m.StartTimeUnixNano
	}
	return 0
}

func (m *Span) GetLinks() []*Span_Link {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *Span) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Span) GetHexList() [][]byte {
	if m != nil {
		return m.HexList
	}
	return nil
}

func (m *Span) GetPlain() []byte {
	if m != nil {
		return m.Plain
	}
	return nil
}

func (m *Span) GetNullValue() wktpb.NullValue {
	if m != nil && m.NullValue != nil {
		return *m.NullValue
	}
	return wktpb.NullValue_NULL_VALUE
}

func (m *Span) GetCodes() map[string]Status_StatusCode {
	if m != nil {
		return m.Codes
	}
	return nil
}

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *Span) ProtoUnknownFields() []byte {
	if m == nil {
		return nil
	}
	return m.unknownFields
}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *Span) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	if len(m.TraceId) > 0 {
		n += 1 + len(m.TraceId) + (bits.Len64(uint64(len(m.TraceId))|1)+traceVarintPayloadBits-1)/traceVarintPayloadBits
	}
	if len(m.SpanId) > 0 {
		n += 1 + len(m.SpanId) + (bits.Len64(uint64(len(m.SpanId))|1)+traceVarintPayloadBits-1)/traceVarintPayloadBits
	}
	if len(m.TraceState) > 0 {
		n += 1 + len(m.TraceState) + (bits.Len64(uint64(len(m.TraceState))|1)+traceVarintPayloadBits-1)/traceVarintPayloadBits
	}
	if len(m.ParentSpanId) > 0 {
		n += 1 + len(m.ParentSpanId) + (bits.Len64(uint64(len(m.ParentSpanId))|1)+traceVarintPayloadBits-1)/traceVarintPayloadBits
	}
	if len(m.Name) > 0 {
		n += 1 + len(m.Name) + (bits.Len64(uint64(len(m.Name))|1)+traceVarintPayloadBits-1)/traceVarintPayloadBits
	}
	if m.Kind != 0 {
		n += 1 + (bits.Len64(uint64(int64(m.Kind))|1)+traceVarintPayloadBits-1)/traceVarintPayloadBits
	}
	if m.StartTimeUnixNano != 0 {
		n += 1 + traceFixed64Size
	}
	for _, v := range m.Links {
		l := v.ProtoSize()
		n += 1 + l + (bits.Len64(uint64(l)|1)+traceVarintPayloadBits-1)/traceVarintPayloadBits
	}
	if m.Status != nil {
		l := m.Status.ProtoSize()
		n += 1 + l + (bits.Len64(uint64(l)|1)+traceVarintPayloadBits-1)/traceVarintPayloadBits
	}
	for _, v := range m.HexList {
		n += 2 + len(v) + (bits.Len64(uint64(len(v))|1)+traceVarintPayloadBits-1)/traceVarintPayloadBits
	}
	if len(m.Plain) > 0 {
		n += 2 + len(m.Plain) + (bits.Len64(uint64(len(m.Plain))|1)+traceVarintPayloadBits-1)/traceVarintPayloadBits
	}
	if m.NullValue != nil {
		n += 2 + (bits.Len64(uint64(int64((*m.NullValue)))|1)+traceVarintPayloadBits-1)/traceVarintPayloadBits
	}
	for k, v := range m.Codes {
		_, _ = k, v
		l := 1 + len(k) + (bits.Len64(uint64(len(k))|1)+traceVarintPayloadBits-1)/traceVarintPayloadBits + 1 + (bits.Len64(uint64(int64(v))|1)+traceVarintPayloadBits-1)/traceVarintPayloadBits
		n += 2 + l + (bits.Len64(uint64(l)|1)+traceVarintPayloadBits-1)/traceVarintPayloadBits
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *Span) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// AppendBinary appends the wire-format encoding of m to b.
func (m *Span) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	l := len(b)
	b = slices.Grow(b, size)[:l+size]
	n, err := m.ProtoMarshalToSizedBuffer(b[l:])
	if err != nil {
		return b[:l], err
	}
	if n != size {
		return b[:l], errors.New(traceErrSizeChanged)
	}
	return b, nil
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *Span) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	var u uint64
	if len(m.unknownFields) > 0 {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if len(m.Codes) > 0 {
		keys := make([]string, 0, len(m.Codes))
		for k := range m.Codes {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		for _, k := range slices.Backward(keys) {
			v := m.Codes[k]
			start := i
			u = uint64(int64(v))
			if u < traceVarintContBit {
				i--
				b[i] = byte(u)
			} else {
				i -= (bits.Len64(u|1) + traceVarintPayloadBits - 1) / traceVarintPayloadBits
				binary.PutUvarint(b[i:], u)
			}
			i--
			b[i] = traceMapValueField<<traceTagTypeBits | traceWireVarint
			if !utf8.ValidString(k) {
				return 0, errors.New(traceSpanCodesEntryKeyErrUTF8)
			}
			i -= len(k)
			copy(b[i:], k)
			u = uint64(len(k))
			if u < traceVarintContBit {
				i--
				b[i] = byte(u)
			} else {
				i -= (bits.Len64(u|1) + traceVarintPayloadBits - 1) / traceVarintPayloadBits
				binary.PutUvarint(b[i:], u)
			}
			i--
			b[i] = traceMapKeyField<<traceTagTypeBits | traceWireBytes
			u = uint64(start - i)
			if u < traceVarintContBit {
				i--
				b[i] = byte(u)
			} else {
				i -= (bits.Len64(u|1) + traceVarintPayloadBits - 1) / traceVarintPayloadBits
				binary.PutUvarint(b[i:], u)
			}
			i -= 2
			binary.PutUvarint(b[i:], 103<<traceTagTypeBits|traceWireBytes)
		}
	}
	if m.NullValue != nil {
		u = uint64(int64((*m.NullValue)))
		if u < traceVarintContBit {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64(u|1) + traceVarintPayloadBits - 1) / traceVarintPayloadBits
			binary.PutUvarint(b[i:], u)
		}
		i -= 2
		binary.PutUvarint(b[i:], 102<<traceTagTypeBits|traceWireVarint)
	}
	if len(m.Plain) > 0 {
		i -= len(m.Plain)
		copy(b[i:], m.Plain)
		u = uint64(len(m.Plain))
		if u < traceVarintContBit {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64(u|1) + traceVarintPayloadBits - 1) / traceVarintPayloadBits
			binary.PutUvarint(b[i:], u)
		}
		i -= 2
		binary.PutUvarint(b[i:], 101<<traceTagTypeBits|traceWireBytes)
	}
	for _, v := range slices.Backward(m.HexList) {
		i -= len(v)
		copy(b[i:], v)
		u = uint64(len(v))
		if u < traceVarintContBit {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64(u|1) + traceVarintPayloadBits - 1) / traceVarintPayloadBits
			binary.PutUvarint(b[i:], u)
		}
		i -= 2
		binary.PutUvarint(b[i:], 100<<traceTagTypeBits|traceWireBytes)
	}
	if m.Status != nil {
		n, err := m.Status.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i -= n
		u = uint64(n)
		if u < traceVarintContBit {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64(u|1) + traceVarintPayloadBits - 1) / traceVarintPayloadBits
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 15<<traceTagTypeBits | traceWireBytes
	}
	for _, v := range slices.Backward(m.Links) {
		n, err := v.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i -= n
		u = uint64(n)
		if u < traceVarintContBit {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64(u|1) + traceVarintPayloadBits - 1) / traceVarintPayloadBits
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 13<<traceTagTypeBits | traceWireBytes
	}
	if m.StartTimeUnixNano != 0 {
		i -= traceFixed64Size
		binary.LittleEndian.PutUint64(b[i:], uint64(m.StartTimeUnixNano))
		i--
		b[i] = 7<<traceTagTypeBits | traceWireFixed64
	}
	if m.Kind != 0 {
		u = uint64(int64(m.Kind))
		if u < traceVarintContBit {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64(u|1) + traceVarintPayloadBits - 1) / traceVarintPayloadBits
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 6<<traceTagTypeBits | traceWireVarint
	}
	if len(m.Name) > 0 {
		if !utf8.ValidString(m.Name) {
			return 0, errors.New(traceSpanNameErrUTF8)
		}
		i -= len(m.Name)
		copy(b[i:], m.Name)
		u = uint64(len(m.Name))
		if u < traceVarintContBit {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64(u|1) + traceVarintPayloadBits - 1) / traceVarintPayloadBits
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 5<<traceTagTypeBits | traceWireBytes
	}
	if len(m.ParentSpanId) > 0 {
		i -= len(m.ParentSpanId)
		copy(b[i:], m.ParentSpanId)
		u = uint64(len(m.ParentSpanId))
		if u < traceVarintContBit {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64(u|1) + traceVarintPayloadBits - 1) / traceVarintPayloadBits
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 4<<traceTagTypeBits | traceWireBytes
	}
	if len(m.TraceState) > 0 {
		if !utf8.ValidString(m.TraceState) {
			return 0, errors.New(traceSpanTraceStateErrUTF8)
		}
		i -= len(m.TraceState)
		copy(b[i:], m.TraceState)
		u = uint64(len(m.TraceState))
		if u < traceVarintContBit {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64(u|1) + traceVarintPayloadBits - 1) / traceVarintPayloadBits
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 3<<traceTagTypeBits | traceWireBytes
	}
	if len(m.SpanId) > 0 {
		i -= len(m.SpanId)
		copy(b[i:], m.SpanId)
		u = uint64(len(m.SpanId))
		if u < traceVarintContBit {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64(u|1) + traceVarintPayloadBits - 1) / traceVarintPayloadBits
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 2<<traceTagTypeBits | traceWireBytes
	}
	if len(m.TraceId) > 0 {
		i -= len(m.TraceId)
		copy(b[i:], m.TraceId)
		u = uint64(len(m.TraceId))
		if u < traceVarintContBit {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64(u|1) + traceVarintPayloadBits - 1) / traceVarintPayloadBits
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 1<<traceTagTypeBits | traceWireBytes
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *Span) UnmarshalBinary(b []byte) error {
	*m = Span{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *Span) ProtoMerge(b []byte) error {
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *Span) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= traceMaxDepth {
		goto errDepth
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>traceTagTypeBits == 0 || t>>traceTagTypeBits > traceMaxFieldNumber {
			goto errParse
		}
		start := b
		b = b[n:]
		switch t {
		case 1<<traceTagTypeBits | traceWireBytes:
			ln, n := binary.Uvarint(b)
			if n <= 0 || ln > uint64(len(b)-n) {
				goto errParse
			}
			x := b[n : n+int(ln)]
			n += int(ln)
			b = b[n:]
			m.TraceId = append([]byte{}, x...)
		case 2<<traceTagTypeBits | traceWireBytes:
			ln, n := binary.Uvarint(b)
			if n <= 0 || ln > uint64(len(b)-n) {
				goto errParse
			}
			x := b[n : n+int(ln)]
			n += int(ln)
			b = b[n:]
			m.SpanId = append([]byte{}, x...)
		case 3<<traceTagTypeBits | traceWireBytes:
			ln, n := binary.Uvarint(b)
			if n <= 0 || ln > uint64(len(b)-n) {
				goto errParse
			}
			x := b[n : n+int(ln)]
			n += int(ln)
			if !utf8.Valid(x) {
				return errors.New(traceSpanTraceStateErrUTF8)
			}
			b = b[n:]
			m.TraceState = string(x)
		case 4<<traceTagTypeBits | traceWireBytes:
			ln, n := binary.Uvarint(b)
			if n <= 0 || ln > uint64(len(b)-n) {
				goto errParse
			}
			x := b[n : n+int(ln)]
			n += int(ln)
			b = b[n:]
			m.ParentSpanId = append([]byte{}, x...)
		case 5<<traceTagTypeBits | traceWireBytes:
			ln, n := binary.Uvarint(b)
			if n <= 0 || ln > uint64(len(b)-n) {
				goto errParse
			}
			x := b[n : n+int(ln)]
			n += int(ln)
			if !utf8.Valid(x) {
				return errors.New(traceSpanNameErrUTF8)
			}
			b = b[n:]
			m.Name = string(x)
		case 6<<traceTagTypeBits | traceWireVarint:
			x, n := binary.Uvarint(b)
			if n <= 0 {
				goto errParse
			}
			b = b[n:]
			m.Kind = Span_SpanKind(int32(x))
		case 7<<traceTagTypeBits | traceWireFixed64:
			if len(b) < traceFixed64Size {
				goto errParse
			}
			x, n := binary.LittleEndian.Uint64(b), traceFixed64Size
			b = b[n:]
			m.StartTimeUnixNano = x
		case 13<<traceTagTypeBits | traceWireBytes:
			ln, n := binary.Uvarint(b)
			if n <= 0 || ln > uint64(len(b)-n) {
				goto errParse
			}
			v := b[n : n+int(ln)]
			n += int(ln)
			mv := &Span_Link{}
			m.Links = append(m.Links, mv)
			if err := mv.ProtoMergeDepth(v, depth+1); err != nil {
				return err
			}
			b = b[n:]
		case 15<<traceTagTypeBits | traceWireBytes:
			ln, n := binary.Uvarint(b)
			if n <= 0 || ln > uint64(len(b)-n) {
				goto errParse
			}
			v := b[n : n+int(ln)]
			n += int(ln)
			if m.Status == nil {
				m.Status = &Status{}
			}
			mv := m.Status
			if err := mv.ProtoMergeDepth(v, depth+1); err != nil {
				return err
			}
			b = b[n:]
		case 100<<traceTagTypeBits | traceWireBytes:
			ln, n := binary.Uvarint(b)
			if n <= 0 || ln > uint64(len(b)-n) {
				goto errParse
			}
			x := b[n : n+int(ln)]
			n += int(ln)
			b = b[n:]
			m.HexList = append(m.HexList, append([]byte{}, x...))
		case 101<<traceTagTypeBits | traceWireBytes:
			ln, n := binary.Uvarint(b)
			if n <= 0 || ln > uint64(len(b)-n) {
				goto errParse
			}
			x := b[n : n+int(ln)]
			n += int(ln)
			b = b[n:]
			m.Plain = append([]byte{}, x...)
		case 102<<traceTagTypeBits | traceWireVarint:
			x, n := binary.Uvarint(b)
			if n <= 0 {
				goto errParse
			}
			b = b[n:]
			v := wktpb.NullValue(int32(x))
			m.NullValue = &v
		case 103<<traceTagTypeBits | traceWireBytes:
			ln, n := binary.Uvarint(b)
			if n <= 0 || ln > uint64(len(b)-n) {
				goto errParse
			}
			v := b[n : n+int(ln)]
			n += int(ln)
			var mk string
			var mv Status_StatusCode
			for len(v) > 0 {
				t, n := binary.Uvarint(v)
				if n <= 0 || t>>traceTagTypeBits == 0 || t>>traceTagTypeBits > traceMaxFieldNumber {
					goto errParse
				}
				v = v[n:]
				switch t {
				case traceMapKeyField<<traceTagTypeBits | traceWireBytes:
					ln, n := binary.Uvarint(v)
					if n <= 0 || ln > uint64(len(v)-n) {
						goto errParse
					}
					x := v[n : n+int(ln)]
					n += int(ln)
					if !utf8.Valid(x) {
						return errors.New(traceSpanCodesEntryKeyErrUTF8)
					}
					mk = string(x)
					v = v[n:]
				case traceMapValueField<<traceTagTypeBits | traceWireVarint:
					x, n := binary.Uvarint(v)
					if n <= 0 {
						goto errParse
					}
					mv = Status_StatusCode(int32(x))
					v = v[n:]
				default:
					num, typ := int32(t>>traceTagTypeBits), t&traceTagTypeMask
					switch typ {
					case traceWireVarint:
						_, n = binary.Uvarint(v)
						if n <= 0 {
							goto errParse
						}
					case traceWireFixed64:
						if len(v) < traceFixed64Size {
							goto errParse
						}
						n = traceFixed64Size
					case traceWireBytes:
						ln, k := binary.Uvarint(v)
						if k <= 0 || ln > uint64(len(v)-k) {
							goto errParse
						}
						n = k + int(ln)
					case traceWireStartGroup:
						var stk [traceSkipStackSize]int32
						open := append(stk[:0], num)
						n = 0
						for len(open) > 0 {
							if depth+len(open) > traceMaxDepth {
								goto errDepth
							}
							t, k := binary.Uvarint(v[n:])
							if k <= 0 || t>>traceTagTypeBits == 0 || t>>traceTagTypeBits > traceMaxFieldNumber {
								goto errParse
							}
							n += k
							switch t & traceTagTypeMask {
							case traceWireVarint:
								_, k = binary.Uvarint(v[n:])
								if k <= 0 {
									goto errParse
								}
							case traceWireFixed64:
								k = traceFixed64Size
							case traceWireBytes:
								ln, k2 := binary.Uvarint(v[n:])
								if k2 <= 0 || ln > uint64(len(v)-n-k2) {
									goto errParse
								}
								k = k2 + int(ln)
							case traceWireStartGroup:
								open = append(open, int32(t>>traceTagTypeBits))
								k = 0
							case traceWireEndGroup:
								if open[len(open)-1] != int32(t>>traceTagTypeBits) {
									goto errParse
								}
								open = open[:len(open)-1]
								k = 0
							case traceWireFixed32:
								k = traceFixed32Size
							default:
								goto errParse
							}
							if k > len(v)-n {
								goto errParse
							}
							n += k
						}
					case traceWireFixed32:
						if len(v) < traceFixed32Size {
							goto errParse
						}
						n = traceFixed32Size
					default:
						goto errParse
					}
					v = v[n:]
				}
			}
			if m.Codes == nil {
				m.Codes = make(map[string]Status_StatusCode)
			}
			m.Codes[mk] = mv
			b = b[n:]
		default:
			// Unknown field, or a known field with an unexpected wire type.
			num, typ := int32(t>>traceTagTypeBits), t&traceTagTypeMask
			switch typ {
			case traceWireVarint:
				_, n = binary.Uvarint(b)
				if n <= 0 {
					goto errParse
				}
			case traceWireFixed64:
				if len(b) < traceFixed64Size {
					goto errParse
				}
				n = traceFixed64Size
			case traceWireBytes:
				ln, k := binary.Uvarint(b)
				if k <= 0 || ln > uint64(len(b)-k) {
					goto errParse
				}
				n = k + int(ln)
			case traceWireStartGroup:
				var stk [traceSkipStackSize]int32
				open := append(stk[:0], num)
				n = 0
				for len(open) > 0 {
					if depth+len(open) > traceMaxDepth {
						goto errDepth
					}
					t, k := binary.Uvarint(b[n:])
					if k <= 0 || t>>traceTagTypeBits == 0 || t>>traceTagTypeBits > traceMaxFieldNumber {
						goto errParse
					}
					n += k
					switch t & traceTagTypeMask {
					case traceWireVarint:
						_, k = binary.Uvarint(b[n:])
						if k <= 0 {
							goto errParse
						}
					case traceWireFixed64:
						k = traceFixed64Size
					case traceWireBytes:
						ln, k2 := binary.Uvarint(b[n:])
						if k2 <= 0 || ln > uint64(len(b)-n-k2) {
							goto errParse
						}
						k = k2 + int(ln)
					case traceWireStartGroup:
						open = append(open, int32(t>>traceTagTypeBits))
						k = 0
					case traceWireEndGroup:
						if open[len(open)-1] != int32(t>>traceTagTypeBits) {
							goto errParse
						}
						open = open[:len(open)-1]
						k = 0
					case traceWireFixed32:
						k = traceFixed32Size
					default:
						goto errParse
					}
					if k > len(b)-n {
						goto errParse
					}
					n += k
				}
			case traceWireFixed32:
				if len(b) < traceFixed32Size {
					goto errParse
				}
				n = traceFixed32Size
			default:
				goto errParse
			}
			m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
errParse:
	return errors.New(traceErrParse)
errDepth:
	return errors.New(traceErrDepth)
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *Span) ProtoCheckInitialized() error {
	return nil
}

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *Span) MarshalJSON() ([]byte, error) {
	return m.ProtoAppendJSON(nil)
}

// MarshalJSONTo writes the ProtoJSON encoding of m to e. It implements
// json.MarshalerTo from encoding/json/v2.
func (m *Span) MarshalJSONTo(e *jsontext.Encoder) error {
	b, err := m.ProtoAppendJSON(e.AvailableBuffer())
	if err != nil {
		return err
	}
	return e.WriteValue(b)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b. It does not
// check required fields.
func (m *Span) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	if m == nil {
		return append(b, "{}"...), nil
	}
	b = append(b, '{')
	if len(m.TraceId) > 0 {
		b = append(b, "\"traceId\":"...)
		b = append(b, '"')
		b = hex.AppendEncode(b, m.TraceId)
		b = append(b, '"')
		b = append(b, ',')
	}
	if len(m.SpanId) > 0 {
		b = append(b, "\"spanId\":"...)
		b = append(b, '"')
		b = hex.AppendEncode(b, m.SpanId)
		b = append(b, '"')
		b = append(b, ',')
	}
	if len(m.TraceState) > 0 {
		b = append(b, "\"traceState\":"...)
		if b, err = jsontext.AppendQuote(b, m.TraceState); err != nil {
			return nil, errors.New("proto: cotorp.test.otlp.Span.trace_state contains invalid UTF-8")
		}
		b = append(b, ',')
	}
	if len(m.ParentSpanId) > 0 {
		b = append(b, "\"parentSpanId\":"...)
		b = append(b, '"')
		b = hex.AppendEncode(b, m.ParentSpanId)
		b = append(b, '"')
		b = append(b, ',')
	}
	if len(m.Name) > 0 {
		b = append(b, "\"name\":"...)
		if b, err = jsontext.AppendQuote(b, m.Name); err != nil {
			return nil, errors.New("proto: cotorp.test.otlp.Span.name contains invalid UTF-8")
		}
		b = append(b, ',')
	}
	if m.Kind != 0 {
		b = append(b, "\"kind\":"...)
		b = strconv.AppendInt(b, int64(m.Kind), 10)
		b = append(b, ',')
	}
	if m.StartTimeUnixNano != 0 {
		b = append(b, "\"startTimeUnixNano\":"...)
		b = append(b, '"')
		b = strconv.AppendUint(b, m.StartTimeUnixNano, 10)
		b = append(b, '"')
		b = append(b, ',')
	}
	if len(m.Links) > 0 {
		b = append(b, "\"links\":["...)
		for j := range m.Links {
			if b, err = m.Links[j].ProtoAppendJSON(b); err != nil {
				return nil, err
			}
			b = append(b, ',')
		}
		b[len(b)-1] = ']'
		b = append(b, ',')
	}
	if m.Status != nil {
		b = append(b, "\"status\":"...)
		if b, err = m.Status.ProtoAppendJSON(b); err != nil {
			return nil, err
		}
		b = append(b, ',')
	}
	if len(m.HexList) > 0 {
		b = append(b, "\"hexList\":["...)
		for j := range m.HexList {
			b = append(b, '"')
			b = hex.AppendEncode(b, m.HexList[j])
			b = append(b, '"')
			b = append(b, ',')
		}
		b[len(b)-1] = ']'
		b = append(b, ',')
	}
	if len(m.Plain) > 0 {
		b = append(b, "\"plain\":"...)
		b = append(b, '"')
		b = base64.StdEncoding.AppendEncode(b, m.Plain)
		b = append(b, '"')
		b = append(b, ',')
	}
	if m.NullValue != nil {
		b = append(b, "\"nullValue\":"...)
		b = append(b, "null"...)
		b = append(b, ',')
	}
	if len(m.Codes) > 0 {
		b = append(b, "\"codes\":{"...)
		keys := make([]string, 0, len(m.Codes))
		for k := range m.Codes {
			keys = append(keys, k)
		}
		slices.Sort(keys)
		for _, k := range keys {
			v := m.Codes[k]
			if b, err = jsontext.AppendQuote(b, k); err != nil {
				return nil, errors.New("proto: cotorp.test.otlp.Span.codes contains invalid UTF-8")
			}
			b = append(b, ':')
			b = strconv.AppendInt(b, int64(v), 10)
			b = append(b, ',')
		}
		b[len(b)-1] = '}'
		b = append(b, ',')
	}
	if b[len(b)-1] == ',' {
		b[len(b)-1] = '}'
	} else {
		b = append(b, '}')
	}
	return b, nil
}

// UnmarshalJSON replaces the contents of m with the decoded ProtoJSON
// value in b.
func (m *Span) UnmarshalJSON(b []byte) error {
	*m = Span{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m.
// It does not check required fields.
func (m *Span) ProtoMergeJSON(b []byte) error {
	d := jsontext.NewDecoder(bytes.NewBuffer(b))
	if err := m.ProtoMergeJSONFrom(d); err != nil {
		return err
	}
	if _, err := d.ReadToken(); err != io.EOF {
		return errors.New("proto: cotorp.test.otlp.Span: unexpected data after JSON value")
	}
	return nil
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value
// read from d. It implements json.UnmarshalerFrom from encoding/json/v2.
func (m *Span) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	if lax, _ := json.GetOption(d.Options(), jsontext.AllowInvalidUTF8); lax {
		// ProtoJSON rejects invalid UTF-8, which d would replace (as
		// encoding/json does), so decode the value with a strict decoder.
		v, err := d.ReadValue()
		if err != nil {
			return err
		}
		return m.UnmarshalJSON(v)
	}
	*m = Span{}
	return m.ProtoMergeJSONFrom(d)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it
// into m. It does not check required fields. d should reject invalid
// UTF-8, as jsontext decoders do by default.
func (m *Span) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	tok, err := d.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() == jsontext.KindNull {
		// JSON null leaves the message unchanged.
		return nil
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return errors.New(traceSpanErrNotObject)
	}
	var seen [13]bool
	// in is the kind of the array or object of repeated or map field f
	// while its elements are read.
	var in jsontext.Kind
	var mk string
	var f int
	for {
		if in == jsontext.KindInvalid {
			if d.PeekKind() == jsontext.KindEndObject {
				break
			}
			kt, err := d.ReadToken()
			if err != nil {
				return err
			}
			key := kt.String()
			switch key {
			case "traceId", "trace_id":
				f = 0
			case "spanId", "span_id":
				f = 1
			case "traceState", "trace_state":
				f = 2
			case "parentSpanId", "parent_span_id":
				f = 3
			case "name":
				f = 4
			case "kind":
				f = 5
			case "startTimeUnixNano", "start_time_unix_nano":
				f = 6
			case "links":
				f = 7
			case "status":
				f = 8
			case "hexList", "hex_list":
				f = 9
			case "plain":
				f = 10
			case "nullValue", "null_value":
				f = 11
			case "codes":
				f = 12
			default:
				// Unknown keys are ignored (-json_discard_unknown).
				if err := d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			if seen[f] {
				return errors.New("proto: cotorp.test.otlp.Span: duplicate field " + strconv.Quote(key))
			}
			seen[f] = true
			if d.PeekKind() == jsontext.KindNull && f != 11 {
				// null leaves the field unset.
				if err := d.SkipValue(); err != nil {
					return err
				}
				continue
			}
			switch f {
			case 7, 9:
				tok, err := d.ReadToken()
				if err != nil {
					return err
				}
				if tok.Kind() != jsontext.KindBeginArray {
					return errors.New("proto: cotorp.test.otlp.Span: expected a JSON array")
				}
				in = jsontext.KindBeginArray
				continue
			case 12:
				tok, err := d.ReadToken()
				if err != nil {
					return err
				}
				if tok.Kind() != jsontext.KindBeginObject {
					return errors.New(traceSpanErrNotObject)
				}
				in = jsontext.KindBeginObject
				continue
			}
		} else {
			if k := d.PeekKind(); k == jsontext.KindEndArray || k == jsontext.KindEndObject {
				if _, err := d.ReadToken(); err != nil {
					return err
				}
				in = jsontext.KindInvalid
				continue
			}
			if in == jsontext.KindBeginObject {
				kt, err := d.ReadToken()
				if err != nil {
					return err
				}
				mk = kt.String()
			}
			if d.PeekKind() == jsontext.KindNull {
				return errors.New("proto: cotorp.test.otlp.Span: null is not allowed in repeated fields or map values")
			}
		}
		class := traceClassNone
		bits := 64
		switch f {
		case 6:
			class, bits = traceClassUnsigned, 64
		case 2, 4:
			class = traceClassString
		case 10:
			class = traceClassBytes
		case 0, 1, 3, 9:
			class = traceClassHex
		case 5, 11, 12:
			class = traceClassEnum
		}
		var iv int64
		var uv uint64
		var sv string
		var by []byte
		var tok jsontext.Token
		if class != traceClassNone {
			var err error
			if tok, err = d.ReadToken(); err != nil {
				return err
			}
			if class == traceClassEnum {
				switch tok.Kind() {
				case jsontext.KindNull:
					class = traceClassNone
				case jsontext.KindString:
					class = traceClassString
				default:
					class, bits = traceClassSigned, 32
				}
			}
		}
		switch class {
		case traceClassSigned, traceClassUnsigned:
			s := tok.String()
			if k := tok.Kind(); k != jsontext.KindNumber && (k != jsontext.KindString || s == "" || (s[0] != '-' && (s[0] < '0' || s[0] > '9')) || !jsontext.Value(s).IsValid()) {
				return errors.New("proto: cotorp.test.otlp.Span: invalid number " + s)
			}
			var err error
			if class == traceClassSigned {
				iv, err = strconv.ParseInt(s, 10, bits)
			} else {
				uv, err = strconv.ParseUint(s, 10, bits)
			}
			if err != nil {
				// Accept exponent and fraction forms that denote an exact integer,
				// bounding the exponent so that exact arithmetic stays cheap.
				if i := strings.IndexAny(s, "eE"); i >= 0 {
					if e, err := strconv.Atoi(s[i+1:]); err != nil || e > traceMaxJSONExponent || e < -traceMaxJSONExponent {
						return errors.New(traceSpanErrInvalidInteger + s)
					}
				}
				r, ok := new(big.Rat).SetString(s)
				if !ok || !r.IsInt() {
					return errors.New(traceSpanErrInvalidInteger + s)
				}
				n := r.Num()
				if class == traceClassSigned {
					if !n.IsInt64() || (bits == 32 && (n.Int64() < math.MinInt32 || n.Int64() > math.MaxInt32)) {
						return errors.New(traceSpanErrInvalidInteger + s)
					}
					iv = n.Int64()
				} else {
					if !n.IsUint64() || (bits == 32 && n.Uint64() > math.MaxUint32) {
						return errors.New(traceSpanErrInvalidInteger + s)
					}
					uv = n.Uint64()
				}
			}
		case traceClassString:
			if tok.Kind() != jsontext.KindString {
				return errors.New("proto: cotorp.test.otlp.Span: invalid string " + tok.String())
			}
			sv = tok.String()
		case traceClassBytes:
			s := tok.String()
			if tok.Kind() != jsontext.KindString {
				return errors.New(traceSpanErrInvalidBytes + s)
			}
			// Accept standard and URL-safe alphabets, with or without padding.
			enc := base64.StdEncoding
			if strings.ContainsAny(s, "-_") {
				enc = base64.URLEncoding
			}
			if len(s)%traceBase64Quantum != 0 {
				enc = enc.WithPadding(base64.NoPadding)
			}
			var err error
			if by, err = enc.DecodeString(s); err != nil {
				return errors.New(traceSpanErrInvalidBytes + s)
			}
		case traceClassHex:
			s := tok.String()
			if tok.Kind() != jsontext.KindString {
				return errors.New(traceSpanErrInvalidHex + s)
			}
			// Either case is accepted.
			var err error
			if by, err = hex.DecodeString(s); err != nil {
				return errors.New(traceSpanErrInvalidHex + s)
			}
		}
		switch f {
		case 0:
			m.TraceId = by
		case 1:
			m.SpanId = by
		case 2:
			m.TraceState = sv
		case 3:
			m.ParentSpanId = by
		case 4:
			m.Name = sv
		case 5:
			var ev Span_SpanKind
			switch class {
			case traceClassString:
				n, ok := Span_SpanKind_value[sv]
				if !ok {
					return errors.New("proto: cotorp.test.otlp.Span: invalid value for enum cotorp.test.otlp.Span.SpanKind: " + strconv.Quote(sv))
				}
				ev = Span_SpanKind(n)
			case traceClassSigned:
				ev = Span_SpanKind(iv)
			}
			m.Kind = ev
		case 6:
			m.StartTimeUnixNano = uv
		case 7:
			mv := &Span_Link{}
			if err := mv.ProtoMergeJSONFrom(d); err != nil {
				return err
			}
			m.Links = append(m.Links, mv)
		case 8:
			if m.Status == nil {
				m.Status = &Status{}
			}
			if err := m.Status.ProtoMergeJSONFrom(d); err != nil {
				return err
			}
		case 9:
			m.HexList = append(m.HexList, by)
		case 10:
			m.Plain = by
		case 11:
			var ev wktpb.NullValue
			switch class {
			case traceClassString:
				n, ok := wktpb.NullValue_value[sv]
				if !ok {
					return errors.New("proto: cotorp.test.otlp.Span: invalid value for enum google.protobuf.NullValue: " + strconv.Quote(sv))
				}
				ev = wktpb.NullValue(n)
			case traceClassSigned:
				ev = wktpb.NullValue(iv)
			}
			x := ev
			m.NullValue = &x
		case 12:
			k := mk
			var ev Status_StatusCode
			switch class {
			case traceClassString:
				n, ok := Status_StatusCode_value[sv]
				if !ok {
					return errors.New("proto: cotorp.test.otlp.Span: invalid value for enum cotorp.test.otlp.Status.StatusCode: " + strconv.Quote(sv))
				}
				ev = Status_StatusCode(n)
			case traceClassSigned:
				ev = Status_StatusCode(iv)
			}
			if m.Codes == nil {
				m.Codes = make(map[string]Status_StatusCode)
			}
			m.Codes[k] = ev
		}
	}
	_, err = d.ReadToken()
	return err
}

type Span_Link struct {
	TraceId []byte
	SpanId  []byte

	unknownFields []byte
}

// Reset clears all fields of m.
func (m *Span_Link) Reset() { *m = Span_Link{} }

func (m *Span_Link) GetTraceId() []byte {
	if m != nil {
		return m.TraceId
	}
	return nil
}

func (m *Span_Link) GetSpanId() []byte {
	if m != nil {
		return m.SpanId
	}
	return nil
}

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *Span_Link) ProtoUnknownFields() []byte {
	if m == nil {
		return nil
	}
	return m.unknownFields
}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *Span_Link) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	if len(m.TraceId) > 0 {
		n += 1 + len(m.TraceId) + (bits.Len64(uint64(len(m.TraceId))|1)+traceVarintPayloadBits-1)/traceVarintPayloadBits
	}
	if len(m.SpanId) > 0 {
		n += 1 + len(m.SpanId) + (bits.Len64(uint64(len(m.SpanId))|1)+traceVarintPayloadBits-1)/traceVarintPayloadBits
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *Span_Link) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// AppendBinary appends the wire-format encoding of m to b.
func (m *Span_Link) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	l := len(b)
	b = slices.Grow(b, size)[:l+size]
	n, err := m.ProtoMarshalToSizedBuffer(b[l:])
	if err != nil {
		return b[:l], err
	}
	if n != size {
		return b[:l], errors.New(traceErrSizeChanged)
	}
	return b, nil
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *Span_Link) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	var u uint64
	if len(m.unknownFields) > 0 {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if len(m.SpanId) > 0 {
		i -= len(m.SpanId)
		copy(b[i:], m.SpanId)
		u = uint64(len(m.SpanId))
		if u < traceVarintContBit {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64(u|1) + traceVarintPayloadBits - 1) / traceVarintPayloadBits
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 2<<traceTagTypeBits | traceWireBytes
	}
	if len(m.TraceId) > 0 {
		i -= len(m.TraceId)
		copy(b[i:], m.TraceId)
		u = uint64(len(m.TraceId))
		if u < traceVarintContBit {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64(u|1) + traceVarintPayloadBits - 1) / traceVarintPayloadBits
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 1<<traceTagTypeBits | traceWireBytes
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *Span_Link) UnmarshalBinary(b []byte) error {
	*m = Span_Link{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *Span_Link) ProtoMerge(b []byte) error {
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *Span_Link) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= traceMaxDepth {
		goto errDepth
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>traceTagTypeBits == 0 || t>>traceTagTypeBits > traceMaxFieldNumber {
			goto errParse
		}
		start := b
		b = b[n:]
		switch t {
		case 1<<traceTagTypeBits | traceWireBytes:
			ln, n := binary.Uvarint(b)
			if n <= 0 || ln > uint64(len(b)-n) {
				goto errParse
			}
			x := b[n : n+int(ln)]
			n += int(ln)
			b = b[n:]
			m.TraceId = append([]byte{}, x...)
		case 2<<traceTagTypeBits | traceWireBytes:
			ln, n := binary.Uvarint(b)
			if n <= 0 || ln > uint64(len(b)-n) {
				goto errParse
			}
			x := b[n : n+int(ln)]
			n += int(ln)
			b = b[n:]
			m.SpanId = append([]byte{}, x...)
		default:
			// Unknown field, or a known field with an unexpected wire type.
			num, typ := int32(t>>traceTagTypeBits), t&traceTagTypeMask
			switch typ {
			case traceWireVarint:
				_, n = binary.Uvarint(b)
				if n <= 0 {
					goto errParse
				}
			case traceWireFixed64:
				if len(b) < traceFixed64Size {
					goto errParse
				}
				n = traceFixed64Size
			case traceWireBytes:
				ln, k := binary.Uvarint(b)
				if k <= 0 || ln > uint64(len(b)-k) {
					goto errParse
				}
				n = k + int(ln)
			case traceWireStartGroup:
				var stk [traceSkipStackSize]int32
				open := append(stk[:0], num)
				n = 0
				for len(open) > 0 {
					if depth+len(open) > traceMaxDepth {
						goto errDepth
					}
					t, k := binary.Uvarint(b[n:])
					if k <= 0 || t>>traceTagTypeBits == 0 || t>>traceTagTypeBits > traceMaxFieldNumber {
						goto errParse
					}
					n += k
					switch t & traceTagTypeMask {
					case traceWireVarint:
						_, k = binary.Uvarint(b[n:])
						if k <= 0 {
							goto errParse
						}
					case traceWireFixed64:
						k = traceFixed64Size
					case traceWireBytes:
						ln, k2 := binary.Uvarint(b[n:])
						if k2 <= 0 || ln > uint64(len(b)-n-k2) {
							goto errParse
						}
						k = k2 + int(ln)
					case traceWireStartGroup:
						open = append(open, int32(t>>traceTagTypeBits))
						k = 0
					case traceWireEndGroup:
						if open[len(open)-1] != int32(t>>traceTagTypeBits) {
							goto errParse
						}
						open = open[:len(open)-1]
						k = 0
					case traceWireFixed32:
						k = traceFixed32Size
					default:
						goto errParse
					}
					if k > len(b)-n {
						goto errParse
					}
					n += k
				}
			case traceWireFixed32:
				if len(b) < traceFixed32Size {
					goto errParse
				}
				n = traceFixed32Size
			default:
				goto errParse
			}
			m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
errParse:
	return errors.New(traceErrParse)
errDepth:
	return errors.New(traceErrDepth)
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *Span_Link) ProtoCheckInitialized() error {
	return nil
}

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *Span_Link) MarshalJSON() ([]byte, error) {
	return m.ProtoAppendJSON(nil)
}

// MarshalJSONTo writes the ProtoJSON encoding of m to e. It implements
// json.MarshalerTo from encoding/json/v2.
func (m *Span_Link) MarshalJSONTo(e *jsontext.Encoder) error {
	b, err := m.ProtoAppendJSON(e.AvailableBuffer())
	if err != nil {
		return err
	}
	return e.WriteValue(b)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b. It does not
// check required fields.
func (m *Span_Link) ProtoAppendJSON(b []byte) ([]byte, error) {
	if m == nil {
		return append(b, "{}"...), nil
	}
	b = append(b, '{')
	if len(m.TraceId) > 0 {
		b = append(b, "\"traceId\":"...)
		b = append(b, '"')
		b = hex.AppendEncode(b, m.TraceId)
		b = append(b, '"')
		b = append(b, ',')
	}
	if len(m.SpanId) > 0 {
		b = append(b, "\"spanId\":"...)
		b = append(b, '"')
		b = hex.AppendEncode(b, m.SpanId)
		b = append(b, '"')
		b = append(b, ',')
	}
	if b[len(b)-1] == ',' {
		b[len(b)-1] = '}'
	} else {
		b = append(b, '}')
	}
	return b, nil
}

// UnmarshalJSON replaces the contents of m with the decoded ProtoJSON
// value in b.
func (m *Span_Link) UnmarshalJSON(b []byte) error {
	*m = Span_Link{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m.
// It does not check required fields.
func (m *Span_Link) ProtoMergeJSON(b []byte) error {
	d := jsontext.NewDecoder(bytes.NewBuffer(b))
	if err := m.ProtoMergeJSONFrom(d); err != nil {
		return err
	}
	if _, err := d.ReadToken(); err != io.EOF {
		return errors.New("proto: cotorp.test.otlp.Span.Link: unexpected data after JSON value")
	}
	return nil
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value
// read from d. It implements json.UnmarshalerFrom from encoding/json/v2.
func (m *Span_Link) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	if lax, _ := json.GetOption(d.Options(), jsontext.AllowInvalidUTF8); lax {
		// ProtoJSON rejects invalid UTF-8, which d would replace (as
		// encoding/json does), so decode the value with a strict decoder.
		v, err := d.ReadValue()
		if err != nil {
			return err
		}
		return m.UnmarshalJSON(v)
	}
	*m = Span_Link{}
	return m.ProtoMergeJSONFrom(d)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it
// into m. It does not check required fields. d should reject invalid
// UTF-8, as jsontext decoders do by default.
func (m *Span_Link) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	tok, err := d.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() == jsontext.KindNull {
		// JSON null leaves the message unchanged.
		return nil
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return errors.New("proto: cotorp.test.otlp.Span.Link: expected a JSON object")
	}
	var seen [2]bool
	var f int
	for {
		if d.PeekKind() == jsontext.KindEndObject {
			break
		}
		kt, err := d.ReadToken()
		if err != nil {
			return err
		}
		key := kt.String()
		switch key {
		case "traceId", "trace_id":
			f = 0
		case "spanId", "span_id":
			f = 1
		default:
			// Unknown keys are ignored (-json_discard_unknown).
			if err := d.SkipValue(); err != nil {
				return err
			}
			continue
		}
		if seen[f] {
			return errors.New("proto: cotorp.test.otlp.Span.Link: duplicate field " + strconv.Quote(key))
		}
		seen[f] = true
		if d.PeekKind() == jsontext.KindNull {
			// null leaves the field unset.
			if err := d.SkipValue(); err != nil {
				return err
			}
			continue
		}
		class := traceClassNone
		switch f {
		case 0, 1:
			class = traceClassHex
		}
		var by []byte
		var tok jsontext.Token
		if class != traceClassNone {
			var err error
			if tok, err = d.ReadToken(); err != nil {
				return err
			}
		}
		switch class {
		case traceClassHex:
			s := tok.String()
			if tok.Kind() != jsontext.KindString {
				return errors.New(traceSpanLinkErrInvalidHex + s)
			}
			// Either case is accepted.
			var err error
			if by, err = hex.DecodeString(s); err != nil {
				return errors.New(traceSpanLinkErrInvalidHex + s)
			}
		}
		switch f {
		case 0:
			m.TraceId = by
		case 1:
			m.SpanId = by
		}
	}
	_, err = d.ReadToken()
	return err
}

type Status struct {
	Message string
	Code    Status_StatusCode

	unknownFields []byte
}

// Reset clears all fields of m.
func (m *Status) Reset() { *m = Status{} }

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Status) GetCode() Status_StatusCode {
	if m != nil {
		return m.Code
	}
	return Status_STATUS_CODE_UNSET
}

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *Status) ProtoUnknownFields() []byte {
	if m == nil {
		return nil
	}
	return m.unknownFields
}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *Status) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	if len(m.Message) > 0 {
		n += 1 + len(m.Message) + (bits.Len64(uint64(len(m.Message))|1)+traceVarintPayloadBits-1)/traceVarintPayloadBits
	}
	if m.Code != 0 {
		n += 1 + (bits.Len64(uint64(int64(m.Code))|1)+traceVarintPayloadBits-1)/traceVarintPayloadBits
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *Status) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// AppendBinary appends the wire-format encoding of m to b.
func (m *Status) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	l := len(b)
	b = slices.Grow(b, size)[:l+size]
	n, err := m.ProtoMarshalToSizedBuffer(b[l:])
	if err != nil {
		return b[:l], err
	}
	if n != size {
		return b[:l], errors.New(traceErrSizeChanged)
	}
	return b, nil
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *Status) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	var u uint64
	if len(m.unknownFields) > 0 {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if m.Code != 0 {
		u = uint64(int64(m.Code))
		if u < traceVarintContBit {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64(u|1) + traceVarintPayloadBits - 1) / traceVarintPayloadBits
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 3<<traceTagTypeBits | traceWireVarint
	}
	if len(m.Message) > 0 {
		if !utf8.ValidString(m.Message) {
			return 0, errors.New(traceStatusMessageErrUTF8)
		}
		i -= len(m.Message)
		copy(b[i:], m.Message)
		u = uint64(len(m.Message))
		if u < traceVarintContBit {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64(u|1) + traceVarintPayloadBits - 1) / traceVarintPayloadBits
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 2<<traceTagTypeBits | traceWireBytes
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *Status) UnmarshalBinary(b []byte) error {
	*m = Status{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *Status) ProtoMerge(b []byte) error {
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *Status) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= traceMaxDepth {
		goto errDepth
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>traceTagTypeBits == 0 || t>>traceTagTypeBits > traceMaxFieldNumber {
			goto errParse
		}
		start := b
		b = b[n:]
		switch t {
		case 2<<traceTagTypeBits | traceWireBytes:
			ln, n := binary.Uvarint(b)
			if n <= 0 || ln > uint64(len(b)-n) {
				goto errParse
			}
			x := b[n : n+int(ln)]
			n += int(ln)
			if !utf8.Valid(x) {
				return errors.New(traceStatusMessageErrUTF8)
			}
			b = b[n:]
			m.Message = string(x)
		case 3<<traceTagTypeBits | traceWireVarint:
			x, n := binary.Uvarint(b)
			if n <= 0 {
				goto errParse
			}
			b = b[n:]
			m.Code = Status_StatusCode(int32(x))
		default:
			// Unknown field, or a known field with an unexpected wire type.
			num, typ := int32(t>>traceTagTypeBits), t&traceTagTypeMask
			switch typ {
			case traceWireVarint:
				_, n = binary.Uvarint(b)
				if n <= 0 {
					goto errParse
				}
			case traceWireFixed64:
				if len(b) < traceFixed64Size {
					goto errParse
				}
				n = traceFixed64Size
			case traceWireBytes:
				ln, k := binary.Uvarint(b)
				if k <= 0 || ln > uint64(len(b)-k) {
					goto errParse
				}
				n = k + int(ln)
			case traceWireStartGroup:
				var stk [traceSkipStackSize]int32
				open := append(stk[:0], num)
				n = 0
				for len(open) > 0 {
					if depth+len(open) > traceMaxDepth {
						goto errDepth
					}
					t, k := binary.Uvarint(b[n:])
					if k <= 0 || t>>traceTagTypeBits == 0 || t>>traceTagTypeBits > traceMaxFieldNumber {
						goto errParse
					}
					n += k
					switch t & traceTagTypeMask {
					case traceWireVarint:
						_, k = binary.Uvarint(b[n:])
						if k <= 0 {
							goto errParse
						}
					case traceWireFixed64:
						k = traceFixed64Size
					case traceWireBytes:
						ln, k2 := binary.Uvarint(b[n:])
						if k2 <= 0 || ln > uint64(len(b)-n-k2) {
							goto errParse
						}
						k = k2 + int(ln)
					case traceWireStartGroup:
						open = append(open, int32(t>>traceTagTypeBits))
						k = 0
					case traceWireEndGroup:
						if open[len(open)-1] != int32(t>>traceTagTypeBits) {
							goto errParse
						}
						open = open[:len(open)-1]
						k = 0
					case traceWireFixed32:
						k = traceFixed32Size
					default:
						goto errParse
					}
					if k > len(b)-n {
						goto errParse
					}
					n += k
				}
			case traceWireFixed32:
				if len(b) < traceFixed32Size {
					goto errParse
				}
				n = traceFixed32Size
			default:
				goto errParse
			}
			m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
errParse:
	return errors.New(traceErrParse)
errDepth:
	return errors.New(traceErrDepth)
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *Status) ProtoCheckInitialized() error {
	return nil
}

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *Status) MarshalJSON() ([]byte, error) {
	return m.ProtoAppendJSON(nil)
}

// MarshalJSONTo writes the ProtoJSON encoding of m to e. It implements
// json.MarshalerTo from encoding/json/v2.
func (m *Status) MarshalJSONTo(e *jsontext.Encoder) error {
	b, err := m.ProtoAppendJSON(e.AvailableBuffer())
	if err != nil {
		return err
	}
	return e.WriteValue(b)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b. It does not
// check required fields.
func (m *Status) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	if m == nil {
		return append(b, "{}"...), nil
	}
	b = append(b, '{')
	if len(m.Message) > 0 {
		b = append(b, "\"message\":"...)
		if b, err = jsontext.AppendQuote(b, m.Message); err != nil {
			return nil, errors.New("proto: cotorp.test.otlp.Status.message contains invalid UTF-8")
		}
		b = append(b, ',')
	}
	if m.Code != 0 {
		b = append(b, "\"code\":"...)
		b = strconv.AppendInt(b, int64(m.Code), 10)
		b = append(b, ',')
	}
	if b[len(b)-1] == ',' {
		b[len(b)-1] = '}'
	} else {
		b = append(b, '}')
	}
	return b, nil
}

// UnmarshalJSON replaces the contents of m with the decoded ProtoJSON
// value in b.
func (m *Status) UnmarshalJSON(b []byte) error {
	*m = Status{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m.
// It does not check required fields.
func (m *Status) ProtoMergeJSON(b []byte) error {
	d := jsontext.NewDecoder(bytes.NewBuffer(b))
	if err := m.ProtoMergeJSONFrom(d); err != nil {
		return err
	}
	if _, err := d.ReadToken(); err != io.EOF {
		return errors.New("proto: cotorp.test.otlp.Status: unexpected data after JSON value")
	}
	return nil
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value
// read from d. It implements json.UnmarshalerFrom from encoding/json/v2.
func (m *Status) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	if lax, _ := json.GetOption(d.Options(), jsontext.AllowInvalidUTF8); lax {
		// ProtoJSON rejects invalid UTF-8, which d would replace (as
		// encoding/json does), so decode the value with a strict decoder.
		v, err := d.ReadValue()
		if err != nil {
			return err
		}
		return m.UnmarshalJSON(v)
	}
	*m = Status{}
	return m.ProtoMergeJSONFrom(d)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it
// into m. It does not check required fields. d should reject invalid
// UTF-8, as jsontext decoders do by default.
func (m *Status) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	tok, err := d.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() == jsontext.KindNull {
		// JSON null leaves the message unchanged.
		return nil
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return errors.New("proto: cotorp.test.otlp.Status: expected a JSON object")
	}
	var seen [2]bool
	var f int
	for {
		if d.PeekKind() == jsontext.KindEndObject {
			break
		}
		kt, err := d.ReadToken()
		if err != nil {
			return err
		}
		key := kt.String()
		switch key {
		case "message":
			f = 0
		case "code":
			f = 1
		default:
			// Unknown keys are ignored (-json_discard_unknown).
			if err := d.SkipValue(); err != nil {
				return err
			}
			continue
		}
		if seen[f] {
			return errors.New("proto: cotorp.test.otlp.Status: duplicate field " + strconv.Quote(key))
		}
		seen[f] = true
		if d.PeekKind() == jsontext.KindNull {
			// null leaves the field unset.
			if err := d.SkipValue(); err != nil {
				return err
			}
			continue
		}
		class := traceClassNone
		bits := 64
		switch f {
		case 0:
			class = traceClassString
		case 1:
			class = traceClassEnum
		}
		var iv int64
		var sv string
		var tok jsontext.Token
		if class != traceClassNone {
			var err error
			if tok, err = d.ReadToken(); err != nil {
				return err
			}
			if class == traceClassEnum {
				switch tok.Kind() {
				case jsontext.KindNull:
					class = traceClassNone
				case jsontext.KindString:
					class = traceClassString
				default:
					class, bits = traceClassSigned, 32
				}
			}
		}
		switch class {
		case traceClassSigned:
			s := tok.String()
			if k := tok.Kind(); k != jsontext.KindNumber && (k != jsontext.KindString || s == "" || (s[0] != '-' && (s[0] < '0' || s[0] > '9')) || !jsontext.Value(s).IsValid()) {
				return errors.New("proto: cotorp.test.otlp.Status: invalid number " + s)
			}
			var err error
			iv, err = strconv.ParseInt(s, 10, bits)
			if err != nil {
				// Accept exponent and fraction forms that denote an exact integer,
				// bounding the exponent so that exact arithmetic stays cheap.
				if i := strings.IndexAny(s, "eE"); i >= 0 {
					if e, err := strconv.Atoi(s[i+1:]); err != nil || e > traceMaxJSONExponent || e < -traceMaxJSONExponent {
						return errors.New(traceStatusErrInvalidInteger + s)
					}
				}
				r, ok := new(big.Rat).SetString(s)
				if !ok || !r.IsInt() {
					return errors.New(traceStatusErrInvalidInteger + s)
				}
				n := r.Num()
				if !n.IsInt64() || (bits == 32 && (n.Int64() < math.MinInt32 || n.Int64() > math.MaxInt32)) {
					return errors.New(traceStatusErrInvalidInteger + s)
				}
				iv = n.Int64()
			}
		case traceClassString:
			if tok.Kind() != jsontext.KindString {
				return errors.New("proto: cotorp.test.otlp.Status: invalid string " + tok.String())
			}
			sv = tok.String()
		}
		switch f {
		case 0:
			m.Message = sv
		case 1:
			var ev Status_StatusCode
			switch class {
			case traceClassString:
				n, ok := Status_StatusCode_value[sv]
				if !ok {
					return errors.New("proto: cotorp.test.otlp.Status: invalid value for enum cotorp.test.otlp.Status.StatusCode: " + strconv.Quote(sv))
				}
				ev = Status_StatusCode(n)
			case traceClassSigned:
				ev = Status_StatusCode(iv)
			}
			m.Code = ev
		}
	}
	_, err = d.ReadToken()
	return err
}

type AnyValue struct {
	// Types that are valid to be assigned to Value:
	//
	//	*AnyValue_StringValue
	//	*AnyValue_BytesValue
	Value isAnyValue_Value

	unknownFields []byte
}

// Reset clears all fields of m.
func (m *AnyValue) Reset() { *m = AnyValue{} }

func (m *AnyValue) GetValue() isAnyValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *AnyValue) GetStringValue() string {
	if x, ok := m.GetValue().(*AnyValue_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *AnyValue) GetBytesValue() []byte {
	if x, ok := m.GetValue().(*AnyValue_BytesValue); ok {
		return x.BytesValue
	}
	return nil
}

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *AnyValue) ProtoUnknownFields() []byte {
	if m == nil {
		return nil
	}
	return m.unknownFields
}

type isAnyValue_Value interface {
	isAnyValue_Value()
}

type AnyValue_StringValue struct {
	StringValue string
}

func (*AnyValue_StringValue) isAnyValue_Value() {}

type AnyValue_BytesValue struct {
	BytesValue []byte
}

func (*AnyValue_BytesValue) isAnyValue_Value() {}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *AnyValue) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	switch o := m.Value.(type) {
	case *AnyValue_StringValue:
		n += 1 + len(o.StringValue) + (bits.Len64(uint64(len(o.StringValue))|1)+traceVarintPayloadBits-1)/traceVarintPayloadBits
	case *AnyValue_BytesValue:
		n += 1 + len(o.BytesValue) + (bits.Len64(uint64(len(o.BytesValue))|1)+traceVarintPayloadBits-1)/traceVarintPayloadBits
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *AnyValue) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// AppendBinary appends the wire-format encoding of m to b.
func (m *AnyValue) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	l := len(b)
	b = slices.Grow(b, size)[:l+size]
	n, err := m.ProtoMarshalToSizedBuffer(b[l:])
	if err != nil {
		return b[:l], err
	}
	if n != size {
		return b[:l], errors.New(traceErrSizeChanged)
	}
	return b, nil
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *AnyValue) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	var u uint64
	if len(m.unknownFields) > 0 {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if o, ok := m.Value.(*AnyValue_BytesValue); ok {
		i -= len(o.BytesValue)
		copy(b[i:], o.BytesValue)
		u = uint64(len(o.BytesValue))
		if u < traceVarintContBit {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64(u|1) + traceVarintPayloadBits - 1) / traceVarintPayloadBits
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 7<<traceTagTypeBits | traceWireBytes
	}
	if o, ok := m.Value.(*AnyValue_StringValue); ok {
		if !utf8.ValidString(o.StringValue) {
			return 0, errors.New(traceAnyValueStringValueErrUTF8)
		}
		i -= len(o.StringValue)
		copy(b[i:], o.StringValue)
		u = uint64(len(o.StringValue))
		if u < traceVarintContBit {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64(u|1) + traceVarintPayloadBits - 1) / traceVarintPayloadBits
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 1<<traceTagTypeBits | traceWireBytes
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *AnyValue) UnmarshalBinary(b []byte) error {
	*m = AnyValue{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *AnyValue) ProtoMerge(b []byte) error {
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *AnyValue) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= traceMaxDepth {
		goto errDepth
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>traceTagTypeBits == 0 || t>>traceTagTypeBits > traceMaxFieldNumber {
			goto errParse
		}
		start := b
		b = b[n:]
		switch t {
		case 1<<traceTagTypeBits | traceWireBytes:
			ln, n := binary.Uvarint(b)
			if n <= 0 || ln > uint64(len(b)-n) {
				goto errParse
			}
			x := b[n : n+int(ln)]
			n += int(ln)
			if !utf8.Valid(x) {
				return errors.New(traceAnyValueStringValueErrUTF8)
			}
			b = b[n:]
			m.Value = &AnyValue_StringValue{StringValue: string(x)}
		case 7<<traceTagTypeBits | traceWireBytes:
			ln, n := binary.Uvarint(b)
			if n <= 0 || ln > uint64(len(b)-n) {
				goto errParse
			}
			x := b[n : n+int(ln)]
			n += int(ln)
			b = b[n:]
			m.Value = &AnyValue_BytesValue{BytesValue: append([]byte{}, x...)}
		default:
			// Unknown field, or a known field with an unexpected wire type.
			num, typ := int32(t>>traceTagTypeBits), t&traceTagTypeMask
			switch typ {
			case traceWireVarint:
				_, n = binary.Uvarint(b)
				if n <= 0 {
					goto errParse
				}
			case traceWireFixed64:
				if len(b) < traceFixed64Size {
					goto errParse
				}
				n = traceFixed64Size
			case traceWireBytes:
				ln, k := binary.Uvarint(b)
				if k <= 0 || ln > uint64(len(b)-k) {
					goto errParse
				}
				n = k + int(ln)
			case traceWireStartGroup:
				var stk [traceSkipStackSize]int32
				open := append(stk[:0], num)
				n = 0
				for len(open) > 0 {
					if depth+len(open) > traceMaxDepth {
						goto errDepth
					}
					t, k := binary.Uvarint(b[n:])
					if k <= 0 || t>>traceTagTypeBits == 0 || t>>traceTagTypeBits > traceMaxFieldNumber {
						goto errParse
					}
					n += k
					switch t & traceTagTypeMask {
					case traceWireVarint:
						_, k = binary.Uvarint(b[n:])
						if k <= 0 {
							goto errParse
						}
					case traceWireFixed64:
						k = traceFixed64Size
					case traceWireBytes:
						ln, k2 := binary.Uvarint(b[n:])
						if k2 <= 0 || ln > uint64(len(b)-n-k2) {
							goto errParse
						}
						k = k2 + int(ln)
					case traceWireStartGroup:
						open = append(open, int32(t>>traceTagTypeBits))
						k = 0
					case traceWireEndGroup:
						if open[len(open)-1] != int32(t>>traceTagTypeBits) {
							goto errParse
						}
						open = open[:len(open)-1]
						k = 0
					case traceWireFixed32:
						k = traceFixed32Size
					default:
						goto errParse
					}
					if k > len(b)-n {
						goto errParse
					}
					n += k
				}
			case traceWireFixed32:
				if len(b) < traceFixed32Size {
					goto errParse
				}
				n = traceFixed32Size
			default:
				goto errParse
			}
			m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
errParse:
	return errors.New(traceErrParse)
errDepth:
	return errors.New(traceErrDepth)
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *AnyValue) ProtoCheckInitialized() error {
	return nil
}

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *AnyValue) MarshalJSON() ([]byte, error) {
	return m.ProtoAppendJSON(nil)
}

// MarshalJSONTo writes the ProtoJSON encoding of m to e. It implements
// json.MarshalerTo from encoding/json/v2.
func (m *AnyValue) MarshalJSONTo(e *jsontext.Encoder) error {
	b, err := m.ProtoAppendJSON(e.AvailableBuffer())
	if err != nil {
		return err
	}
	return e.WriteValue(b)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b. It does not
// check required fields.
func (m *AnyValue) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	if m == nil {
		return append(b, "{}"...), nil
	}
	b = append(b, '{')
	if o, ok := m.Value.(*AnyValue_StringValue); ok {
		b = append(b, "\"stringValue\":"...)
		if b, err = jsontext.AppendQuote(b, o.StringValue); err != nil {
			return nil, errors.New("proto: cotorp.test.otlp.AnyValue.string_value contains invalid UTF-8")
		}
		b = append(b, ',')
	}
	if o, ok := m.Value.(*AnyValue_BytesValue); ok {
		b = append(b, "\"bytesValue\":"...)
		b = append(b, '"')
		b = base64.StdEncoding.AppendEncode(b, o.BytesValue)
		b = append(b, '"')
		b = append(b, ',')
	}
	if b[len(b)-1] == ',' {
		b[len(b)-1] = '}'
	} else {
		b = append(b, '}')
	}
	return b, nil
}

// UnmarshalJSON replaces the contents of m with the decoded ProtoJSON
// value in b.
func (m *AnyValue) UnmarshalJSON(b []byte) error {
	*m = AnyValue{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m.
// It does not check required fields.
func (m *AnyValue) ProtoMergeJSON(b []byte) error {
	d := jsontext.NewDecoder(bytes.NewBuffer(b))
	if err := m.ProtoMergeJSONFrom(d); err != nil {
		return err
	}
	if _, err := d.ReadToken(); err != io.EOF {
		return errors.New("proto: cotorp.test.otlp.AnyValue: unexpected data after JSON value")
	}
	return nil
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value
// read from d. It implements json.UnmarshalerFrom from encoding/json/v2.
func (m *AnyValue) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	if lax, _ := json.GetOption(d.Options(), jsontext.AllowInvalidUTF8); lax {
		// ProtoJSON rejects invalid UTF-8, which d would replace (as
		// encoding/json does), so decode the value with a strict decoder.
		v, err := d.ReadValue()
		if err != nil {
			return err
		}
		return m.UnmarshalJSON(v)
	}
	*m = AnyValue{}
	return m.ProtoMergeJSONFrom(d)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it
// into m. It does not check required fields. d should reject invalid
// UTF-8, as jsontext decoders do by default.
func (m *AnyValue) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	tok, err := d.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() == jsontext.KindNull {
		// JSON null leaves the message unchanged.
		return nil
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return errors.New("proto: cotorp.test.otlp.AnyValue: expected a JSON object")
	}
	var seen [2]bool
	var oneofs [1]bool
	var f int
	for {
		if d.PeekKind() == jsontext.KindEndObject {
			break
		}
		kt, err := d.ReadToken()
		if err != nil {
			return err
		}
		key := kt.String()
		switch key {
		case "stringValue", "string_value":
			f = 0
		case "bytesValue", "bytes_value":
			f = 1
		default:
			// Unknown keys are ignored (-json_discard_unknown).
			if err := d.SkipValue(); err != nil {
				return err
			}
			continue
		}
		if seen[f] {
			return errors.New("proto: cotorp.test.otlp.AnyValue: duplicate field " + strconv.Quote(key))
		}
		seen[f] = true
		if d.PeekKind() == jsontext.KindNull {
			// null leaves the field unset.
			if err := d.SkipValue(); err != nil {
				return err
			}
			continue
		}
		switch f {
		case 0, 1:
			if oneofs[0] {
				return errors.New("proto: cotorp.test.otlp.AnyValue: multiple fields set for oneof value")
			}
			oneofs[0] = true
		}
		class := traceClassNone
		switch f {
		case 0:
			class = traceClassString
		case 1:
			class = traceClassBytes
		}
		var sv string
		var by []byte
		var tok jsontext.Token
		if class != traceClassNone {
			var err error
			if tok, err = d.ReadToken(); err != nil {
				return err
			}
		}
		switch class {
		case traceClassString:
			if tok.Kind() != jsontext.KindString {
				return errors.New("proto: cotorp.test.otlp.AnyValue: invalid string " + tok.String())
			}
			sv = tok.String()
		case traceClassBytes:
			s := tok.String()
			if tok.Kind() != jsontext.KindString {
				return errors.New(traceAnyValueErrInvalidBytes + s)
			}
			// Accept standard and URL-safe alphabets, with or without padding.
			enc := base64.StdEncoding
			if strings.ContainsAny(s, "-_") {
				enc = base64.URLEncoding
			}
			if len(s)%traceBase64Quantum != 0 {
				enc = enc.WithPadding(base64.NoPadding)
			}
			var err error
			if by, err = enc.DecodeString(s); err != nil {
				return errors.New(traceAnyValueErrInvalidBytes + s)
			}
		}
		switch f {
		case 0:
			m.Value = &AnyValue_StringValue{StringValue: sv}
		case 1:
			m.Value = &AnyValue_BytesValue{BytesValue: by}
		}
	}
	_, err = d.ReadToken()
	return err
}

type Nothing struct {
	unknownFields []byte
}

// Reset clears all fields of m.
func (m *Nothing) Reset() { *m = Nothing{} }

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *Nothing) ProtoUnknownFields() []byte {
	if m == nil {
		return nil
	}
	return m.unknownFields
}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *Nothing) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *Nothing) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// AppendBinary appends the wire-format encoding of m to b.
func (m *Nothing) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	l := len(b)
	b = slices.Grow(b, size)[:l+size]
	n, err := m.ProtoMarshalToSizedBuffer(b[l:])
	if err != nil {
		return b[:l], err
	}
	if n != size {
		return b[:l], errors.New(traceErrSizeChanged)
	}
	return b, nil
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *Nothing) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if len(m.unknownFields) > 0 {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *Nothing) UnmarshalBinary(b []byte) error {
	*m = Nothing{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *Nothing) ProtoMerge(b []byte) error {
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *Nothing) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= traceMaxDepth {
		goto errDepth
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>traceTagTypeBits == 0 || t>>traceTagTypeBits > traceMaxFieldNumber {
			goto errParse
		}
		start := b
		b = b[n:]
		// Unknown field, or a known field with an unexpected wire type.
		num, typ := int32(t>>traceTagTypeBits), t&traceTagTypeMask
		switch typ {
		case traceWireVarint:
			_, n = binary.Uvarint(b)
			if n <= 0 {
				goto errParse
			}
		case traceWireFixed64:
			if len(b) < traceFixed64Size {
				goto errParse
			}
			n = traceFixed64Size
		case traceWireBytes:
			ln, k := binary.Uvarint(b)
			if k <= 0 || ln > uint64(len(b)-k) {
				goto errParse
			}
			n = k + int(ln)
		case traceWireStartGroup:
			var stk [traceSkipStackSize]int32
			open := append(stk[:0], num)
			n = 0
			for len(open) > 0 {
				if depth+len(open) > traceMaxDepth {
					goto errDepth
				}
				t, k := binary.Uvarint(b[n:])
				if k <= 0 || t>>traceTagTypeBits == 0 || t>>traceTagTypeBits > traceMaxFieldNumber {
					goto errParse
				}
				n += k
				switch t & traceTagTypeMask {
				case traceWireVarint:
					_, k = binary.Uvarint(b[n:])
					if k <= 0 {
						goto errParse
					}
				case traceWireFixed64:
					k = traceFixed64Size
				case traceWireBytes:
					ln, k2 := binary.Uvarint(b[n:])
					if k2 <= 0 || ln > uint64(len(b)-n-k2) {
						goto errParse
					}
					k = k2 + int(ln)
				case traceWireStartGroup:
					open = append(open, int32(t>>traceTagTypeBits))
					k = 0
				case traceWireEndGroup:
					if open[len(open)-1] != int32(t>>traceTagTypeBits) {
						goto errParse
					}
					open = open[:len(open)-1]
					k = 0
				case traceWireFixed32:
					k = traceFixed32Size
				default:
					goto errParse
				}
				if k > len(b)-n {
					goto errParse
				}
				n += k
			}
		case traceWireFixed32:
			if len(b) < traceFixed32Size {
				goto errParse
			}
			n = traceFixed32Size
		default:
			goto errParse
		}
		m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
		b = b[n:]
	}
	return nil
errParse:
	return errors.New(traceErrParse)
errDepth:
	return errors.New(traceErrDepth)
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *Nothing) ProtoCheckInitialized() error {
	return nil
}

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *Nothing) MarshalJSON() ([]byte, error) {
	return m.ProtoAppendJSON(nil)
}

// MarshalJSONTo writes the ProtoJSON encoding of m to e. It implements
// json.MarshalerTo from encoding/json/v2.
func (m *Nothing) MarshalJSONTo(e *jsontext.Encoder) error {
	b, err := m.ProtoAppendJSON(e.AvailableBuffer())
	if err != nil {
		return err
	}
	return e.WriteValue(b)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b. It does not
// check required fields.
func (m *Nothing) ProtoAppendJSON(b []byte) ([]byte, error) {
	if m == nil {
		return append(b, "{}"...), nil
	}
	b = append(b, '{')
	if b[len(b)-1] == ',' {
		b[len(b)-1] = '}'
	} else {
		b = append(b, '}')
	}
	return b, nil
}

// UnmarshalJSON replaces the contents of m with the decoded ProtoJSON
// value in b.
func (m *Nothing) UnmarshalJSON(b []byte) error {
	*m = Nothing{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m.
// It does not check required fields.
func (m *Nothing) ProtoMergeJSON(b []byte) error {
	d := jsontext.NewDecoder(bytes.NewBuffer(b))
	if err := m.ProtoMergeJSONFrom(d); err != nil {
		return err
	}
	if _, err := d.ReadToken(); err != io.EOF {
		return errors.New("proto: cotorp.test.otlp.Nothing: unexpected data after JSON value")
	}
	return nil
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value
// read from d. It implements json.UnmarshalerFrom from encoding/json/v2.
func (m *Nothing) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	if lax, _ := json.GetOption(d.Options(), jsontext.AllowInvalidUTF8); lax {
		// ProtoJSON rejects invalid UTF-8, which d would replace (as
		// encoding/json does), so decode the value with a strict decoder.
		v, err := d.ReadValue()
		if err != nil {
			return err
		}
		return m.UnmarshalJSON(v)
	}
	*m = Nothing{}
	return m.ProtoMergeJSONFrom(d)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it
// into m. It does not check required fields. d should reject invalid
// UTF-8, as jsontext decoders do by default.
func (m *Nothing) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	tok, err := d.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() == jsontext.KindNull {
		// JSON null leaves the message unchanged.
		return nil
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return errors.New("proto: cotorp.test.otlp.Nothing: expected a JSON object")
	}
	for d.PeekKind() != jsontext.KindEndObject {
		if _, err := d.ReadToken(); err != nil {
			return err
		}
		// Unknown keys are ignored (-json_discard_unknown).
		if err := d.SkipValue(); err != nil {
			return err
		}
	}
	_, err = d.ReadToken()
	return err
}
