// Code generated by cotorp. DO NOT EDIT.
// source: editions/editions2024.proto

package editions2024pb

import (
	"bytes"
	"encoding/binary"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"io"
	"math"
	"math/big"
	"math/bits"
	"slices"
	"strconv"
	"strings"
	"unicode/utf8"
)

// Wire types.
const (
	editions2024WireVarint     = 0
	editions2024WireFixed64    = 1
	editions2024WireBytes      = 2
	editions2024WireStartGroup = 3
	editions2024WireEndGroup   = 4
	editions2024WireFixed32    = 5
)

// A tag holds the field number above the wire type in its low three bits.
const (
	editions2024TagTypeBits    = 3
	editions2024TagTypeMask    = 1<<3 - 1
	editions2024MaxFieldNumber = 1<<29 - 1
)

// Encoded sizes.
const (
	editions2024Fixed32Size       = 4
	editions2024Fixed64Size       = 8
	editions2024VarintPayloadBits = 7    // value bits per varint byte
	editions2024VarintContBit     = 0x80 // set on every varint byte but the last
)

// Decoding limits.
const (
	editions2024MaxDepth      = 10000 // maximum message and group nesting
	editions2024SkipStackSize = 16    // group nesting tracked without allocating
)

// ProtoJSON scalar parse classes.
const (
	editions2024ClassNone   = 0
	editions2024ClassSigned = 1
	editions2024ClassString = 5
)

// ProtoJSON limits.
const editions2024MaxJSONExponent = 100 // bounds exact integer parsing of exponent forms

// Error messages used more than once.
const (
	editions2024ErrSizeChanged           = "proto: message size changed during marshal"
	editions2024ErrParse                 = "proto: cannot parse invalid wire-format data"
	editions2024ErrDepth                 = "proto: exceeded maximum recursion depth"
	editions2024VisibleErrInvalidInteger = "proto: cotorp.test.editions2024.Visible: invalid integer "
	editions2024VisibleHiddenSErrUTF8    = "proto: field cotorp.test.editions2024.Visible.Hidden.s contains invalid UTF-8"
)

type Visible struct {
	A      *int32
	Hidden *Visible_Hidden

	unknownFields []byte
}

// Reset clears all fields of m.
func (m *Visible) Reset() { *m = Visible{} }

func (m *Visible) GetA() int32 {
	if m != nil && m.A != nil {
		return *m.A
	}
	return 0
}

func (m *Visible) GetHidden() *Visible_Hidden {
	if m != nil {
		return m.Hidden
	}
	return nil
}

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *Visible) ProtoUnknownFields() []byte {
	if m == nil {
		return nil
	}
	return m.unknownFields
}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *Visible) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	if m.A != nil {
		n += 1 + (bits.Len64(uint64(int64((*m.A)))|1)+editions2024VarintPayloadBits-1)/editions2024VarintPayloadBits
	}
	if m.Hidden != nil {
		l := m.Hidden.ProtoSize()
		n += 1 + l + (bits.Len64(uint64(l)|1)+editions2024VarintPayloadBits-1)/editions2024VarintPayloadBits
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *Visible) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// AppendBinary appends the wire-format encoding of m to b.
func (m *Visible) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	l := len(b)
	b = slices.Grow(b, size)[:l+size]
	n, err := m.ProtoMarshalToSizedBuffer(b[l:])
	if err != nil {
		return b[:l], err
	}
	if n != size {
		return b[:l], errors.New(editions2024ErrSizeChanged)
	}
	return b, nil
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *Visible) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	var u uint64
	if len(m.unknownFields) > 0 {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if m.Hidden != nil {
		n, err := m.Hidden.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i -= n
		u = uint64(n)
		if u < editions2024VarintContBit {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64(u|1) + editions2024VarintPayloadBits - 1) / editions2024VarintPayloadBits
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 2<<editions2024TagTypeBits | editions2024WireBytes
	}
	if m.A != nil {
		u = uint64(int64((*m.A)))
		if u < editions2024VarintContBit {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64(u|1) + editions2024VarintPayloadBits - 1) / editions2024VarintPayloadBits
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 1<<editions2024TagTypeBits | editions2024WireVarint
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *Visible) UnmarshalBinary(b []byte) error {
	*m = Visible{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *Visible) ProtoMerge(b []byte) error {
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *Visible) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= editions2024MaxDepth {
		goto errDepth
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>editions2024TagTypeBits == 0 || t>>editions2024TagTypeBits > editions2024MaxFieldNumber {
			goto errParse
		}
		start := b
		b = b[n:]
		switch t {
		case 1<<editions2024TagTypeBits | editions2024WireVarint:
			x, n := binary.Uvarint(b)
			if n <= 0 {
				goto errParse
			}
			b = b[n:]
			v := int32(x)
			m.A = &v
		case 2<<editions2024TagTypeBits | editions2024WireBytes:
			ln, n := binary.Uvarint(b)
			if n <= 0 || ln > uint64(len(b)-n) {
				goto errParse
			}
			v := b[n : n+int(ln)]
			n += int(ln)
			if m.Hidden == nil {
				m.Hidden = &Visible_Hidden{}
			}
			mv := m.Hidden
			if err := mv.ProtoMergeDepth(v, depth+1); err != nil {
				return err
			}
			b = b[n:]
		default:
			// Unknown field, or a known field with an unexpected wire type.
			num, typ := int32(t>>editions2024TagTypeBits), t&editions2024TagTypeMask
			switch typ {
			case editions2024WireVarint:
				_, n = binary.Uvarint(b)
				if n <= 0 {
					goto errParse
				}
			case editions2024WireFixed64:
				if len(b) < editions2024Fixed64Size {
					goto errParse
				}
				n = editions2024Fixed64Size
			case editions2024WireBytes:
				ln, k := binary.Uvarint(b)
				if k <= 0 || ln > uint64(len(b)-k) {
					goto errParse
				}
				n = k + int(ln)
			case editions2024WireStartGroup:
				var stk [editions2024SkipStackSize]int32
				open := append(stk[:0], num)
				n = 0
				for len(open) > 0 {
					if depth+len(open) > editions2024MaxDepth {
						goto errDepth
					}
					t, k := binary.Uvarint(b[n:])
					if k <= 0 || t>>editions2024TagTypeBits == 0 || t>>editions2024TagTypeBits > editions2024MaxFieldNumber {
						goto errParse
					}
					n += k
					switch t & editions2024TagTypeMask {
					case editions2024WireVarint:
						_, k = binary.Uvarint(b[n:])
						if k <= 0 {
							goto errParse
						}
					case editions2024WireFixed64:
						k = editions2024Fixed64Size
					case editions2024WireBytes:
						ln, k2 := binary.Uvarint(b[n:])
						if k2 <= 0 || ln > uint64(len(b)-n-k2) {
							goto errParse
						}
						k = k2 + int(ln)
					case editions2024WireStartGroup:
						open = append(open, int32(t>>editions2024TagTypeBits))
						k = 0
					case editions2024WireEndGroup:
						if open[len(open)-1] != int32(t>>editions2024TagTypeBits) {
							goto errParse
						}
						open = open[:len(open)-1]
						k = 0
					case editions2024WireFixed32:
						k = editions2024Fixed32Size
					default:
						goto errParse
					}
					if k > len(b)-n {
						goto errParse
					}
					n += k
				}
			case editions2024WireFixed32:
				if len(b) < editions2024Fixed32Size {
					goto errParse
				}
				n = editions2024Fixed32Size
			default:
				goto errParse
			}
			m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
errParse:
	return errors.New(editions2024ErrParse)
errDepth:
	return errors.New(editions2024ErrDepth)
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *Visible) ProtoCheckInitialized() error {
	return nil
}

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *Visible) MarshalJSON() ([]byte, error) {
	return m.ProtoAppendJSON(nil)
}

// MarshalJSONTo writes the ProtoJSON encoding of m to e. It implements
// json.MarshalerTo from encoding/json/v2.
func (m *Visible) MarshalJSONTo(e *jsontext.Encoder) error {
	b, err := m.ProtoAppendJSON(e.AvailableBuffer())
	if err != nil {
		return err
	}
	return e.WriteValue(b)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b. It does not
// check required fields.
func (m *Visible) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	if m == nil {
		return append(b, "{}"...), nil
	}
	b = append(b, '{')
	if m.A != nil {
		b = append(b, "\"a\":"...)
		b = strconv.AppendInt(b, int64((*m.A)), 10)
		b = append(b, ',')
	}
	if m.Hidden != nil {
		b = append(b, "\"hidden\":"...)
		if b, err = m.Hidden.ProtoAppendJSON(b); err != nil {
			return nil, err
		}
		b = append(b, ',')
	}
	if b[len(b)-1] == ',' {
		b[len(b)-1] = '}'
	} else {
		b = append(b, '}')
	}
	return b, nil
}

// UnmarshalJSON replaces the contents of m with the decoded ProtoJSON
// value in b.
func (m *Visible) UnmarshalJSON(b []byte) error {
	*m = Visible{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m.
// It does not check required fields.
func (m *Visible) ProtoMergeJSON(b []byte) error {
	d := jsontext.NewDecoder(bytes.NewBuffer(b))
	if err := m.ProtoMergeJSONFrom(d); err != nil {
		return err
	}
	if _, err := d.ReadToken(); err != io.EOF {
		return errors.New("proto: cotorp.test.editions2024.Visible: unexpected data after JSON value")
	}
	return nil
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value
// read from d. It implements json.UnmarshalerFrom from encoding/json/v2.
func (m *Visible) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	if lax, _ := json.GetOption(d.Options(), jsontext.AllowInvalidUTF8); lax {
		// ProtoJSON rejects invalid UTF-8, which d would replace (as
		// encoding/json does), so decode the value with a strict decoder.
		v, err := d.ReadValue()
		if err != nil {
			return err
		}
		return m.UnmarshalJSON(v)
	}
	*m = Visible{}
	return m.ProtoMergeJSONFrom(d)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it
// into m. It does not check required fields. d should reject invalid
// UTF-8, as jsontext decoders do by default.
func (m *Visible) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	tok, err := d.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() == jsontext.KindNull {
		// JSON null leaves the message unchanged.
		return nil
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return errors.New("proto: cotorp.test.editions2024.Visible: expected a JSON object")
	}
	var seen [2]bool
	var f int
	for {
		if d.PeekKind() == jsontext.KindEndObject {
			break
		}
		kt, err := d.ReadToken()
		if err != nil {
			return err
		}
		key := kt.String()
		switch key {
		case "a":
			f = 0
		case "hidden":
			f = 1
		default:
			return errors.New("proto: cotorp.test.editions2024.Visible: unknown field " + strconv.Quote(key))
		}
		if seen[f] {
			return errors.New("proto: cotorp.test.editions2024.Visible: duplicate field " + strconv.Quote(key))
		}
		seen[f] = true
		if d.PeekKind() == jsontext.KindNull {
			// null leaves the field unset.
			if err := d.SkipValue(); err != nil {
				return err
			}
			continue
		}
		class := editions2024ClassNone
		bits := 64
		switch f {
		case 0:
			class, bits = editions2024ClassSigned, 32
		}
		var iv int64
		var tok jsontext.Token
		if class != editions2024ClassNone {
			var err error
			if tok, err = d.ReadToken(); err != nil {
				return err
			}
		}
		switch class {
		case editions2024ClassSigned:
			s := tok.String()
			if k := tok.Kind(); k != jsontext.KindNumber && (k != jsontext.KindString || s == "" || (s[0] != '-' && (s[0] < '0' || s[0] > '9')) || !jsontext.Value(s).IsValid()) {
				return errors.New("proto: cotorp.test.editions2024.Visible: invalid number " + s)
			}
			var err error
			iv, err = strconv.ParseInt(s, 10, bits)
			if err != nil {
				// Accept exponent and fraction forms that denote an exact integer,
				// bounding the exponent so that exact arithmetic stays cheap.
				if i := strings.IndexAny(s, "eE"); i >= 0 {
					if e, err := strconv.Atoi(s[i+1:]); err != nil || e > editions2024MaxJSONExponent || e < -editions2024MaxJSONExponent {
						return errors.New(editions2024VisibleErrInvalidInteger + s)
					}
				}
				r, ok := new(big.Rat).SetString(s)
				if !ok || !r.IsInt() {
					return errors.New(editions2024VisibleErrInvalidInteger + s)
				}
				n := r.Num()
				if !n.IsInt64() || (bits == 32 && (n.Int64() < math.MinInt32 || n.Int64() > math.MaxInt32)) {
					return errors.New(editions2024VisibleErrInvalidInteger + s)
				}
				iv = n.Int64()
			}
		}
		switch f {
		case 0:
			x := int32(iv)
			m.A = &x
		case 1:
			if m.Hidden == nil {
				m.Hidden = &Visible_Hidden{}
			}
			if err := m.Hidden.ProtoMergeJSONFrom(d); err != nil {
				return err
			}
		}
	}
	_, err = d.ReadToken()
	return err
}

type Visible_Hidden struct {
	S *string

	unknownFields []byte
}

// Reset clears all fields of m.
func (m *Visible_Hidden) Reset() { *m = Visible_Hidden{} }

func (m *Visible_Hidden) GetS() string {
	if m != nil && m.S != nil {
		return *m.S
	}
	return ""
}

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *Visible_Hidden) ProtoUnknownFields() []byte {
	if m == nil {
		return nil
	}
	return m.unknownFields
}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *Visible_Hidden) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	if m.S != nil {
		n += 1 + len((*m.S)) + (bits.Len64(uint64(len((*m.S)))|1)+editions2024VarintPayloadBits-1)/editions2024VarintPayloadBits
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *Visible_Hidden) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// AppendBinary appends the wire-format encoding of m to b.
func (m *Visible_Hidden) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	l := len(b)
	b = slices.Grow(b, size)[:l+size]
	n, err := m.ProtoMarshalToSizedBuffer(b[l:])
	if err != nil {
		return b[:l], err
	}
	if n != size {
		return b[:l], errors.New(editions2024ErrSizeChanged)
	}
	return b, nil
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *Visible_Hidden) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	var u uint64
	if len(m.unknownFields) > 0 {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if m.S != nil {
		if !utf8.ValidString((*m.S)) {
			return 0, errors.New(editions2024VisibleHiddenSErrUTF8)
		}
		i -= len((*m.S))
		copy(b[i:], (*m.S))
		u = uint64(len((*m.S)))
		if u < editions2024VarintContBit {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64(u|1) + editions2024VarintPayloadBits - 1) / editions2024VarintPayloadBits
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 1<<editions2024TagTypeBits | editions2024WireBytes
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *Visible_Hidden) UnmarshalBinary(b []byte) error {
	*m = Visible_Hidden{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *Visible_Hidden) ProtoMerge(b []byte) error {
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *Visible_Hidden) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= editions2024MaxDepth {
		goto errDepth
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>editions2024TagTypeBits == 0 || t>>editions2024TagTypeBits > editions2024MaxFieldNumber {
			goto errParse
		}
		start := b
		b = b[n:]
		switch t {
		case 1<<editions2024TagTypeBits | editions2024WireBytes:
			ln, n := binary.Uvarint(b)
			if n <= 0 || ln > uint64(len(b)-n) {
				goto errParse
			}
			x := b[n : n+int(ln)]
			n += int(ln)
			if !utf8.Valid(x) {
				return errors.New(editions2024VisibleHiddenSErrUTF8)
			}
			b = b[n:]
			v := string(x)
			m.S = &v
		default:
			// Unknown field, or a known field with an unexpected wire type.
			num, typ := int32(t>>editions2024TagTypeBits), t&editions2024TagTypeMask
			switch typ {
			case editions2024WireVarint:
				_, n = binary.Uvarint(b)
				if n <= 0 {
					goto errParse
				}
			case editions2024WireFixed64:
				if len(b) < editions2024Fixed64Size {
					goto errParse
				}
				n = editions2024Fixed64Size
			case editions2024WireBytes:
				ln, k := binary.Uvarint(b)
				if k <= 0 || ln > uint64(len(b)-k) {
					goto errParse
				}
				n = k + int(ln)
			case editions2024WireStartGroup:
				var stk [editions2024SkipStackSize]int32
				open := append(stk[:0], num)
				n = 0
				for len(open) > 0 {
					if depth+len(open) > editions2024MaxDepth {
						goto errDepth
					}
					t, k := binary.Uvarint(b[n:])
					if k <= 0 || t>>editions2024TagTypeBits == 0 || t>>editions2024TagTypeBits > editions2024MaxFieldNumber {
						goto errParse
					}
					n += k
					switch t & editions2024TagTypeMask {
					case editions2024WireVarint:
						_, k = binary.Uvarint(b[n:])
						if k <= 0 {
							goto errParse
						}
					case editions2024WireFixed64:
						k = editions2024Fixed64Size
					case editions2024WireBytes:
						ln, k2 := binary.Uvarint(b[n:])
						if k2 <= 0 || ln > uint64(len(b)-n-k2) {
							goto errParse
						}
						k = k2 + int(ln)
					case editions2024WireStartGroup:
						open = append(open, int32(t>>editions2024TagTypeBits))
						k = 0
					case editions2024WireEndGroup:
						if open[len(open)-1] != int32(t>>editions2024TagTypeBits) {
							goto errParse
						}
						open = open[:len(open)-1]
						k = 0
					case editions2024WireFixed32:
						k = editions2024Fixed32Size
					default:
						goto errParse
					}
					if k > len(b)-n {
						goto errParse
					}
					n += k
				}
			case editions2024WireFixed32:
				if len(b) < editions2024Fixed32Size {
					goto errParse
				}
				n = editions2024Fixed32Size
			default:
				goto errParse
			}
			m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
errParse:
	return errors.New(editions2024ErrParse)
errDepth:
	return errors.New(editions2024ErrDepth)
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *Visible_Hidden) ProtoCheckInitialized() error {
	return nil
}

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *Visible_Hidden) MarshalJSON() ([]byte, error) {
	return m.ProtoAppendJSON(nil)
}

// MarshalJSONTo writes the ProtoJSON encoding of m to e. It implements
// json.MarshalerTo from encoding/json/v2.
func (m *Visible_Hidden) MarshalJSONTo(e *jsontext.Encoder) error {
	b, err := m.ProtoAppendJSON(e.AvailableBuffer())
	if err != nil {
		return err
	}
	return e.WriteValue(b)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b. It does not
// check required fields.
func (m *Visible_Hidden) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	if m == nil {
		return append(b, "{}"...), nil
	}
	b = append(b, '{')
	if m.S != nil {
		b = append(b, "\"s\":"...)
		if b, err = jsontext.AppendQuote(b, (*m.S)); err != nil {
			return nil, errors.New("proto: cotorp.test.editions2024.Visible.Hidden.s contains invalid UTF-8")
		}
		b = append(b, ',')
	}
	if b[len(b)-1] == ',' {
		b[len(b)-1] = '}'
	} else {
		b = append(b, '}')
	}
	return b, nil
}

// UnmarshalJSON replaces the contents of m with the decoded ProtoJSON
// value in b.
func (m *Visible_Hidden) UnmarshalJSON(b []byte) error {
	*m = Visible_Hidden{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m.
// It does not check required fields.
func (m *Visible_Hidden) ProtoMergeJSON(b []byte) error {
	d := jsontext.NewDecoder(bytes.NewBuffer(b))
	if err := m.ProtoMergeJSONFrom(d); err != nil {
		return err
	}
	if _, err := d.ReadToken(); err != io.EOF {
		return errors.New("proto: cotorp.test.editions2024.Visible.Hidden: unexpected data after JSON value")
	}
	return nil
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value
// read from d. It implements json.UnmarshalerFrom from encoding/json/v2.
func (m *Visible_Hidden) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	if lax, _ := json.GetOption(d.Options(), jsontext.AllowInvalidUTF8); lax {
		// ProtoJSON rejects invalid UTF-8, which d would replace (as
		// encoding/json does), so decode the value with a strict decoder.
		v, err := d.ReadValue()
		if err != nil {
			return err
		}
		return m.UnmarshalJSON(v)
	}
	*m = Visible_Hidden{}
	return m.ProtoMergeJSONFrom(d)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it
// into m. It does not check required fields. d should reject invalid
// UTF-8, as jsontext decoders do by default.
func (m *Visible_Hidden) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	tok, err := d.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() == jsontext.KindNull {
		// JSON null leaves the message unchanged.
		return nil
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return errors.New("proto: cotorp.test.editions2024.Visible.Hidden: expected a JSON object")
	}
	var seen [1]bool
	var f int
	for {
		if d.PeekKind() == jsontext.KindEndObject {
			break
		}
		kt, err := d.ReadToken()
		if err != nil {
			return err
		}
		key := kt.String()
		switch key {
		case "s":
			f = 0
		default:
			return errors.New("proto: cotorp.test.editions2024.Visible.Hidden: unknown field " + strconv.Quote(key))
		}
		if seen[f] {
			return errors.New("proto: cotorp.test.editions2024.Visible.Hidden: duplicate field " + strconv.Quote(key))
		}
		seen[f] = true
		if d.PeekKind() == jsontext.KindNull {
			// null leaves the field unset.
			if err := d.SkipValue(); err != nil {
				return err
			}
			continue
		}
		class := editions2024ClassString
		var sv string
		tok, err := d.ReadToken()
		if err != nil {
			return err
		}
		switch class {
		case editions2024ClassString:
			if tok.Kind() != jsontext.KindString {
				return errors.New("proto: cotorp.test.editions2024.Visible.Hidden: invalid string " + tok.String())
			}
			sv = tok.String()
		}
		x := sv
		m.S = &x
	}
	_, err = d.ReadToken()
	return err
}
