// Code generated by cotorp. DO NOT EDIT.
// source: google/protobuf/any.proto

package wktpb

import (
	"bytes"
	"encoding/binary"
	"errors"
	"math/bits"
	"slices"
	"unicode/utf8"
)

// Wire types.
const (
	anyWireVarint     = 0
	anyWireFixed64    = 1
	anyWireBytes      = 2
	anyWireStartGroup = 3
	anyWireEndGroup   = 4
	anyWireFixed32    = 5
)

// A tag holds the field number above the wire type in its low three bits.
const (
	anyTagTypeBits    = 3
	anyTagTypeMask    = 1<<3 - 1
	anyMaxFieldNumber = 1<<29 - 1
)

// Encoded sizes.
const (
	anyFixed32Size       = 4
	anyFixed64Size       = 8
	anyVarintPayloadBits = 7    // value bits per varint byte
	anyVarintContBit     = 0x80 // set on every varint byte but the last
)

// Decoding limits.
const (
	anyMaxDepth      = 10000 // maximum message and group nesting
	anySkipStackSize = 16    // group nesting tracked without allocating
)

// Error messages used more than once.
const (
	anyAnyTypeUrlErrUTF8 = "proto: field google.protobuf.Any.type_url contains invalid UTF-8"
	anyAnyErrUnsupported = "proto: google.protobuf.Any: JSON requires a type registry, which cotorp-generated code does not have"
)

// `Any` contains an arbitrary serialized protocol buffer message along with a
// URL that describes the type of the serialized message.
//
// In its binary encoding, an `Any` is an ordinary message; but in other wire
// forms like JSON, it has a special encoding. The format of the type URL is
// described on the `type_url` field.
//
// Protobuf APIs provide utilities to interact with `Any` values:
//
//   - A 'pack' operation accepts a message and constructs a generic `Any` wrapper
//     around it.
//   - An 'unpack' operation reads the content of an `Any` message, either into an
//     existing message or a new one. Unpack operations must check the type of the
//     value they unpack against the declared `type_url`.
//   - An 'is' operation decides whether an `Any` contains a message of the given
//     type, i.e. whether it can 'unpack' that type.
//
// The JSON format representation of an `Any` follows one of these cases:
//
//   - For types without special-cased JSON encodings, the JSON format
//     representation of the `Any` is the same as that of the message, with an
//     additional `@type` field which contains the type URL.
//   - For types with special-cased JSON encodings (typically called 'well-known'
//     types, listed in https://protobuf.dev/programming-guides/json/#any), the
//     JSON format representation has a key `@type` which contains the type URL
//     and a key `value` which contains the JSON-serialized value.
//
// The text format representation of an `Any` is like a message with one field
// whose name is the type URL in brackets. For example, an `Any` containing a
// `foo.Bar` message may be written `[type.googleapis.com/foo.Bar] { a: 2 }`.
type Any struct {
	// Identifies the type of the serialized Protobuf message with a URI reference
	// consisting of a prefix ending in a slash and the fully-qualified type name.
	//
	// Example: type.googleapis.com/google.protobuf.StringValue
	//
	// This string must contain at least one `/` character, and the content after
	// the last `/` must be the fully-qualified name of the type in canonical
	// form, without a leading dot. Do not write a scheme on these URI references
	// so that clients do not attempt to contact them.
	//
	// The prefix is arbitrary and Protobuf implementations are expected to
	// simply strip off everything up to and including the last `/` to identify
	// the type. `type.googleapis.com/` is a common default prefix that some
	// legacy implementations require. This prefix does not indicate the origin of
	// the type, and URIs containing it are not expected to respond to any
	// requests.
	//
	// All type URL strings must be legal URI references with the additional
	// restriction (for the text format) that the content of the reference
	// must consist only of alphanumeric characters, percent-encoded escapes, and
	// characters in the following set (not including the outer backticks):
	// `/-.~_!$&()*+,;=`. Despite our allowing percent encodings, implementations
	// should not unescape them to prevent confusion with existing parsers. For
	// example, `type.googleapis.com%2FFoo` should be rejected.
	//
	// In the original design of `Any`, the possibility of launching a type
	// resolution service at these type URLs was considered but Protobuf never
	// implemented one and considers contacting these URLs to be problematic and
	// a potential security issue. Do not attempt to contact type URLs.
	TypeUrl string
	// Holds a Protobuf serialization of the type described by type_url.
	Value []byte

	unknownFields []byte
}

// Reset clears all fields of m.
func (m *Any) Reset() { *m = Any{} }

func (m *Any) GetTypeUrl() string {
	if m != nil {
		return m.TypeUrl
	}
	return ""
}

func (m *Any) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *Any) ProtoUnknownFields() []byte {
	if m == nil {
		return nil
	}
	return m.unknownFields
}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *Any) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	if len(m.TypeUrl) > 0 {
		n += 1 + len(m.TypeUrl) + (bits.Len64(uint64(len(m.TypeUrl))|1)+anyVarintPayloadBits-1)/anyVarintPayloadBits
	}
	if len(m.Value) > 0 {
		n += 1 + len(m.Value) + (bits.Len64(uint64(len(m.Value))|1)+anyVarintPayloadBits-1)/anyVarintPayloadBits
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *Any) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// AppendBinary appends the wire-format encoding of m to b.
func (m *Any) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	l := len(b)
	b = slices.Grow(b, size)[:l+size]
	n, err := m.ProtoMarshalToSizedBuffer(b[l:])
	if err != nil {
		return b[:l], err
	}
	if n != size {
		return b[:l], errors.New("proto: message size changed during marshal")
	}
	return b, nil
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *Any) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	var u uint64
	if len(m.unknownFields) > 0 {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(b[i:], m.Value)
		u = uint64(len(m.Value))
		if u < anyVarintContBit {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64(u|1) + anyVarintPayloadBits - 1) / anyVarintPayloadBits
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 2<<anyTagTypeBits | anyWireBytes
	}
	if len(m.TypeUrl) > 0 {
		if !utf8.ValidString(m.TypeUrl) {
			return 0, errors.New(anyAnyTypeUrlErrUTF8)
		}
		i -= len(m.TypeUrl)
		copy(b[i:], m.TypeUrl)
		u = uint64(len(m.TypeUrl))
		if u < anyVarintContBit {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64(u|1) + anyVarintPayloadBits - 1) / anyVarintPayloadBits
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 1<<anyTagTypeBits | anyWireBytes
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *Any) UnmarshalBinary(b []byte) error {
	*m = Any{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *Any) ProtoMerge(b []byte) error {
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *Any) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= anyMaxDepth {
		goto errDepth
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>anyTagTypeBits == 0 || t>>anyTagTypeBits > anyMaxFieldNumber {
			goto errParse
		}
		start := b
		b = b[n:]
		switch t {
		case 1<<anyTagTypeBits | anyWireBytes:
			ln, n := binary.Uvarint(b)
			if n <= 0 || ln > uint64(len(b)-n) {
				goto errParse
			}
			x := b[n : n+int(ln)]
			n += int(ln)
			if !utf8.Valid(x) {
				return errors.New(anyAnyTypeUrlErrUTF8)
			}
			b = b[n:]
			m.TypeUrl = string(x)
		case 2<<anyTagTypeBits | anyWireBytes:
			ln, n := binary.Uvarint(b)
			if n <= 0 || ln > uint64(len(b)-n) {
				goto errParse
			}
			x := b[n : n+int(ln)]
			n += int(ln)
			b = b[n:]
			m.Value = append([]byte{}, x...)
		default:
			// Unknown field, or a known field with an unexpected wire type.
			num, typ := int32(t>>anyTagTypeBits), t&anyTagTypeMask
			switch typ {
			case anyWireVarint:
				_, n = binary.Uvarint(b)
				if n <= 0 {
					goto errParse
				}
			case anyWireFixed64:
				if len(b) < anyFixed64Size {
					goto errParse
				}
				n = anyFixed64Size
			case anyWireBytes:
				ln, k := binary.Uvarint(b)
				if k <= 0 || ln > uint64(len(b)-k) {
					goto errParse
				}
				n = k + int(ln)
			case anyWireStartGroup:
				var stk [anySkipStackSize]int32
				open := append(stk[:0], num)
				n = 0
				for len(open) > 0 {
					if depth+len(open) > anyMaxDepth {
						goto errDepth
					}
					t, k := binary.Uvarint(b[n:])
					if k <= 0 || t>>anyTagTypeBits == 0 || t>>anyTagTypeBits > anyMaxFieldNumber {
						goto errParse
					}
					n += k
					switch t & anyTagTypeMask {
					case anyWireVarint:
						_, k = binary.Uvarint(b[n:])
						if k <= 0 {
							goto errParse
						}
					case anyWireFixed64:
						k = anyFixed64Size
					case anyWireBytes:
						ln, k2 := binary.Uvarint(b[n:])
						if k2 <= 0 || ln > uint64(len(b)-n-k2) {
							goto errParse
						}
						k = k2 + int(ln)
					case anyWireStartGroup:
						open = append(open, int32(t>>anyTagTypeBits))
						k = 0
					case anyWireEndGroup:
						if open[len(open)-1] != int32(t>>anyTagTypeBits) {
							goto errParse
						}
						open = open[:len(open)-1]
						k = 0
					case anyWireFixed32:
						k = anyFixed32Size
					default:
						goto errParse
					}
					if k > len(b)-n {
						goto errParse
					}
					n += k
				}
			case anyWireFixed32:
				if len(b) < anyFixed32Size {
					goto errParse
				}
				n = anyFixed32Size
			default:
				goto errParse
			}
			m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
errParse:
	return errors.New("proto: cannot parse invalid wire-format data")
errDepth:
	return errors.New("proto: exceeded maximum recursion depth")
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *Any) ProtoCheckInitialized() error {
	return nil
}

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *Any) MarshalJSON() ([]byte, error) {
	return m.ProtoAppendJSON(nil)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b. It does not
// check required fields.
func (m *Any) ProtoAppendJSON(b []byte) ([]byte, error) {
	return nil, errors.New(anyAnyErrUnsupported)
}

// UnmarshalJSON replaces the contents of m with the decoded ProtoJSON
// value in b.
func (m *Any) UnmarshalJSON(b []byte) error {
	*m = Any{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m.
// It does not check required fields.
func (m *Any) ProtoMergeJSON(b []byte) error {
	if string(bytes.TrimSpace(b)) == "null" {
		return nil
	}
	return errors.New(anyAnyErrUnsupported)
}
