// Code generated by cotorp. DO NOT EDIT.
// source: google/protobuf/duration.proto

package wktpb

import (
	"bytes"
	"encoding/binary"
	"encoding/json"
	"errors"
	"math/bits"
	"slices"
	"strconv"
	"strings"
	"unicode/utf8"
)

// A Duration represents a signed, fixed-length span of time represented
// as a count of seconds and fractions of seconds at nanosecond
// resolution. It is independent of any calendar and concepts like "day"
// or "month". It is related to Timestamp in that the difference between
// two Timestamp values is a Duration and it can be added or subtracted
// from a Timestamp. Range is approximately +-10,000 years.
//
// # Examples
//
// Example 1: Compute Duration from two Timestamps in pseudo code.
//
//	Timestamp start = ...;
//	Timestamp end = ...;
//	Duration duration = ...;
//
//	duration.seconds = end.seconds - start.seconds;
//	duration.nanos = end.nanos - start.nanos;
//
//	if (duration.seconds < 0 && duration.nanos > 0) {
//	  duration.seconds += 1;
//	  duration.nanos -= 1000000000;
//	} else if (duration.seconds > 0 && duration.nanos < 0) {
//	  duration.seconds -= 1;
//	  duration.nanos += 1000000000;
//	}
//
// Example 2: Compute Timestamp from Timestamp + Duration in pseudo code.
//
//	Timestamp start = ...;
//	Duration duration = ...;
//	Timestamp end = ...;
//
//	end.seconds = start.seconds + duration.seconds;
//	end.nanos = start.nanos + duration.nanos;
//
//	if (end.nanos < 0) {
//	  end.seconds -= 1;
//	  end.nanos += 1000000000;
//	} else if (end.nanos >= 1000000000) {
//	  end.seconds += 1;
//	  end.nanos -= 1000000000;
//	}
//
// Example 3: Compute Duration from datetime.timedelta in Python.
//
//	td = datetime.timedelta(days=3, minutes=10)
//	duration = Duration()
//	duration.FromTimedelta(td)
//
// # JSON Mapping
//
// In JSON format, the Duration type is encoded as a string rather than an
// object, where the string ends in the suffix "s" (indicating seconds) and
// is preceded by the number of seconds, with nanoseconds expressed as
// fractional seconds. For example, 3 seconds with 0 nanoseconds should be
// encoded in JSON format as "3s", while 3 seconds and 1 nanosecond should
// be expressed in JSON format as "3.000000001s", and 3 seconds and 1
// microsecond should be expressed in JSON format as "3.000001s".
type Duration struct {
	// Signed seconds of the span of time. Must be from -315,576,000,000
	// to +315,576,000,000 inclusive. Note: these bounds are computed from:
	// 60 sec/min * 60 min/hr * 24 hr/day * 365.25 days/year * 10000 years
	Seconds int64
	// Signed fractions of a second at nanosecond resolution of the span
	// of time. Durations less than one second are represented with a 0
	// `seconds` field and a positive or negative `nanos` field. For durations
	// of one second or more, a non-zero value for the `nanos` field must be
	// of the same sign as the `seconds` field. Must be from -999,999,999
	// to +999,999,999 inclusive.
	Nanos int32

	unknownFields []byte
}

// Reset clears all fields of m.
func (m *Duration) Reset() { *m = Duration{} }

func (m *Duration) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *Duration) GetNanos() int32 {
	if m != nil {
		return m.Nanos
	}
	return 0
}

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *Duration) ProtoUnknownFields() []byte {
	if m == nil {
		return nil
	}
	return m.unknownFields
}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *Duration) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	if m.Seconds != 0 {
		n += 1 + (bits.Len64((uint64(m.Seconds))|1)+6)/7
	}
	if m.Nanos != 0 {
		n += 1 + (bits.Len64((uint64(int64(m.Nanos)))|1)+6)/7
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *Duration) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// AppendBinary appends the wire-format encoding of m to b.
func (m *Duration) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	l := len(b)
	b = slices.Grow(b, size)[:l+size]
	n, err := m.ProtoMarshalToSizedBuffer(b[l:])
	if err != nil {
		return b[:l], err
	}
	if n != size {
		return b[:l], errors.New("proto: message size changed during marshal")
	}
	return b, nil
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *Duration) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	var u uint64
	if len(m.unknownFields) > 0 {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if m.Nanos != 0 {
		u = uint64(int64(m.Nanos))
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x10
	}
	if m.Seconds != 0 {
		u = uint64(m.Seconds)
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x08
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *Duration) UnmarshalBinary(b []byte) error {
	*m = Duration{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *Duration) ProtoMerge(b []byte) error {
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *Duration) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= 10000 {
		goto errDepth
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>3 == 0 || t>>3 > 536870911 {
			goto errParse
		}
		num, typ := int32(t>>3), int(t&7)
		start := b
		b = b[n:]
		switch num {
		case 1:
			if typ == 0 {
				x, n := binary.Uvarint(b)
				if n <= 0 {
					goto errParse
				}
				b = b[n:]
				m.Seconds = int64(x)
				continue
			}
		case 2:
			if typ == 0 {
				x, n := binary.Uvarint(b)
				if n <= 0 {
					goto errParse
				}
				b = b[n:]
				m.Nanos = int32(x)
				continue
			}
		}
		// Unknown field, or a known field with an unexpected wire type.
		switch typ {
		case 0:
			_, n = binary.Uvarint(b)
			if n <= 0 {
				goto errParse
			}
		case 1:
			if len(b) < 8 {
				goto errParse
			}
			n = 8
		case 2:
			ln, k := binary.Uvarint(b)
			if k <= 0 || ln > uint64(len(b)-k) {
				goto errParse
			}
			n = k + int(ln)
		case 3:
			var stk [16]int32
			open := append(stk[:0], num)
			n = 0
			for len(open) > 0 {
				if depth+len(open) > 10000 {
					goto errDepth
				}
				t, k := binary.Uvarint(b[n:])
				if k <= 0 || t>>3 == 0 || t>>3 > 536870911 {
					goto errParse
				}
				n += k
				switch t & 7 {
				case 0:
					_, k = binary.Uvarint(b[n:])
					if k <= 0 {
						goto errParse
					}
				case 1:
					k = 8
				case 2:
					ln, k2 := binary.Uvarint(b[n:])
					if k2 <= 0 || ln > uint64(len(b)-n-k2) {
						goto errParse
					}
					k = k2 + int(ln)
				case 3:
					open = append(open, int32(t>>3))
					k = 0
				case 4:
					if open[len(open)-1] != int32(t>>3) {
						goto errParse
					}
					open = open[:len(open)-1]
					k = 0
				case 5:
					k = 4
				default:
					goto errParse
				}
				if k > len(b)-n {
					goto errParse
				}
				n += k
			}
		case 5:
			if len(b) < 4 {
				goto errParse
			}
			n = 4
		default:
			goto errParse
		}
		m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
		b = b[n:]
	}
	return nil
errParse:
	return errors.New("proto: cannot parse invalid wire-format data")
errDepth:
	return errors.New("proto: exceeded maximum recursion depth")
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *Duration) ProtoCheckInitialized() error {
	return nil
}

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *Duration) MarshalJSON() ([]byte, error) {
	return m.ProtoAppendJSON(nil)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b. It does not
// check required fields.
func (m *Duration) ProtoAppendJSON(b []byte) ([]byte, error) {
	var s int64
	var ns int32
	if m != nil {
		s, ns = m.Seconds, m.Nanos
	}
	if s < -315576000000 || s > 315576000000 || ns <= -1000000000 || ns >= 1000000000 || (s > 0 && ns < 0) || (s < 0 && ns > 0) {
		return nil, errors.New("proto: google.protobuf.Duration: duration out of range")
	}
	b = append(b, '"')
	if s < 0 || ns < 0 {
		b = append(b, '-')
		s, ns = -s, -ns
	}
	b = strconv.AppendInt(b, s, 10)
	switch {
	case ns == 0:
	case ns%1000000 == 0:
		b = append(b, '.')
		b = append(b, strconv.Itoa(1000 + int(ns)/1000000)[1:]...)
	case ns%1000 == 0:
		b = append(b, '.')
		b = append(b, strconv.Itoa(1000000 + int(ns)/1000)[1:]...)
	default:
		b = append(b, '.')
		b = append(b, strconv.Itoa(1000000000 + int(ns))[1:]...)
	}
	b = append(b, "s\""...)
	return b, nil
}

// UnmarshalJSON replaces the contents of m with the decoded ProtoJSON
// value in b.
func (m *Duration) UnmarshalJSON(b []byte) error {
	*m = Duration{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m.
// It does not check required fields.
func (m *Duration) ProtoMergeJSON(b []byte) error {
	raw := bytes.TrimSpace(b)
	if !json.Valid(raw) {
		return errors.New("proto: google.protobuf.Duration: invalid JSON")
	}
	if string(raw) == "null" {
		return nil
	}
	var s string
	if raw[0] != '"' || !utf8.Valid(raw) {
		return errors.New("proto: google.protobuf.Duration: expected a JSON string")
	}
	if err := json.Unmarshal(raw, &s); err != nil {
		return err
	}
	in := s
	neg := false
	if strings.HasPrefix(s, "-") {
		neg, s = true, s[1:]
	}
	whole, frac, dot := strings.Cut(strings.TrimSuffix(s, "s"), ".")
	if !strings.HasSuffix(s, "s") || whole == "" || strings.Trim(whole, "0123456789") != "" ||
		(dot && (frac == "" || len(frac) > 9 || strings.Trim(frac, "0123456789") != "")) {
		return errors.New("proto: google.protobuf.Duration: invalid duration " + strconv.Quote(in))
	}
	secs, err := strconv.ParseInt(whole, 10, 64)
	if err != nil || secs > 315576000000 {
		return errors.New("proto: google.protobuf.Duration: duration out of range")
	}
	var nanos int64
	if dot {
		nanos, _ = strconv.ParseInt((frac + "000000000")[:9], 10, 64)
	}
	if neg {
		secs, nanos = -secs, -nanos
	}
	m.Seconds, m.Nanos = secs, int32(nanos)
	return nil
}
