// Code generated by cotorp. DO NOT EDIT.
// source: google/protobuf/duration.proto

package wktpb

import (
	"bytes"
	"cmp"
	"encoding/binary"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"io"
	"math/bits"
	"slices"
	"strconv"
	"strings"
)

const (
	durationWireVarint            = 0
	durationWireFixed64           = 1
	durationWireBytes             = 2
	durationWireStartGroup        = 3
	durationWireEndGroup          = 4
	durationWireFixed32           = 5
	durationTagTypeBits           = 3
	durationTagTypeMask           = 1<<3 - 1
	durationMaxFieldNumber        = 1<<29 - 1
	durationFixed32Size           = 4
	durationFixed64Size           = 8
	durationVarintPayloadBits     = 7
	durationVarintContBit         = 0x80
	durationMaxDepth              = 10000
	durationMaxFracDigits         = 9
	durationMaxDurationSeconds    = 315576000000
	durationNanosPerSecond        = 1000000000
	durationNanosPerMilli         = 1000000
	durationNanosPerMicro         = 1000
	durationMicrosPerSecond       = 1000000
	durationMillisPerSecond       = 1000
	durationErrParse              = "proto: cannot parse invalid wire-format data"
	durationDurationErrOutOfRange = "proto: google.protobuf.Duration: duration out of range"
)

// A Duration represents a signed, fixed-length span of time represented
// as a count of seconds and fractions of seconds at nanosecond
// resolution. It is independent of any calendar and concepts like "day"
// or "month". It is related to Timestamp in that the difference between
// two Timestamp values is a Duration and it can be added or subtracted
// from a Timestamp. Range is approximately +-10,000 years.
//
// # Examples
//
// Example 1: Compute Duration from two Timestamps in pseudo code.
//
//	Timestamp start = ...;
//	Timestamp end = ...;
//	Duration duration = ...;
//
//	duration.seconds = end.seconds - start.seconds;
//	duration.nanos = end.nanos - start.nanos;
//
//	if (duration.seconds < 0 && duration.nanos > 0) {
//	  duration.seconds += 1;
//	  duration.nanos -= 1000000000;
//	} else if (duration.seconds > 0 && duration.nanos < 0) {
//	  duration.seconds -= 1;
//	  duration.nanos += 1000000000;
//	}
//
// Example 2: Compute Timestamp from Timestamp + Duration in pseudo code.
//
//	Timestamp start = ...;
//	Duration duration = ...;
//	Timestamp end = ...;
//
//	end.seconds = start.seconds + duration.seconds;
//	end.nanos = start.nanos + duration.nanos;
//
//	if (end.nanos < 0) {
//	  end.seconds -= 1;
//	  end.nanos += 1000000000;
//	} else if (end.nanos >= 1000000000) {
//	  end.seconds += 1;
//	  end.nanos -= 1000000000;
//	}
//
// Example 3: Compute Duration from datetime.timedelta in Python.
//
//	td = datetime.timedelta(days=3, minutes=10)
//	duration = Duration()
//	duration.FromTimedelta(td)
//
// # JSON Mapping
//
// In JSON format, the Duration type is encoded as a string rather than an
// object, where the string ends in the suffix "s" (indicating seconds) and
// is preceded by the number of seconds, with nanoseconds expressed as
// fractional seconds. For example, 3 seconds with 0 nanoseconds should be
// encoded in JSON format as "3s", while 3 seconds and 1 nanosecond should
// be expressed in JSON format as "3.000000001s", and 3 seconds and 1
// microsecond should be expressed in JSON format as "3.000001s".
type Duration struct {
	// Signed seconds of the span of time. Must be from -315,576,000,000
	// to +315,576,000,000 inclusive. Note: these bounds are computed from:
	// 60 sec/min * 60 min/hr * 24 hr/day * 365.25 days/year * 10000 years
	Seconds int64
	// Signed fractions of a second at nanosecond resolution of the span
	// of time. Durations less than one second are represented with a 0
	// `seconds` field and a positive or negative `nanos` field. For durations
	// of one second or more, a non-zero value for the `nanos` field must be
	// of the same sign as the `seconds` field. Must be from -999,999,999
	// to +999,999,999 inclusive.
	Nanos int32

	unknownFields []byte
}

// Reset clears all fields of m.
func (m *Duration) Reset()            { *m = Duration{} }
func (m *Duration) z() *Duration      { return durationIf(m == nil, &durationZeroDuration, m) }
func (m *Duration) GetSeconds() int64 { return m.z().Seconds }
func (m *Duration) GetNanos() int32   { return m.z().Nanos }

// ProtoUnknownFields returns the raw bytes of fields that were not recognized when m was decoded.
func (m *Duration) ProtoUnknownFields() []byte { return m.z().unknownFields }

// ProtoSize returns the size of the wire-format encoding of m.
func (m *Duration) ProtoSize() (n int) {
	m = m.z()
	n += durationSizeVarint(1, uint64(m.Seconds))
	n += durationSizeVarint(1, uint64(int64(m.Nanos)))
	return n + len(m.unknownFields)
}

// MarshalBinary returns the wire-format encoding of m.
func (m *Duration) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *Duration) AppendBinary(b []byte) ([]byte, error) {
	return durationAppendBinary(b, m.ProtoSize(), m.ProtoMarshalToSizedBuffer)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must hold m.ProtoSize() bytes, and returns the count written, without checking required fields.
func (m *Duration) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	m = m.z()
	i := durationCopyUnknown(b, len(b), m.unknownFields)
	i = durationPutVarintField(b, i, uint64(int64(m.Nanos)), 2<<durationTagTypeBits|durationWireVarint)
	i = durationPutVarintField(b, i, uint64(m.Seconds), 1<<durationTagTypeBits|durationWireVarint)
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the wire-format message in b.
func (m *Duration) UnmarshalBinary(b []byte) error { *m = Duration{}; return m.ProtoMergeDepth(b, 0) }

// ProtoMerge decodes the wire-format message in b and merges it into m, without checking required fields.
func (m *Duration) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *Duration) ProtoMergeDepth(b []byte, depth int) error {
	err := durationDepth(depth)
	for t, n := binary.Uvarint(b); n > 0 && err == nil; t, n = binary.Uvarint(b) {
		b = b[n:]
		switch t {
		case 1<<durationTagTypeBits | durationWireVarint:
			n = durationVarint(b, &m.Seconds)
		case 2<<durationTagTypeBits | durationWireVarint:
			n = durationVarint(b, &m.Nanos)
		default:
			n, err = durationUnknown(b, t, depth, &m.unknownFields)
		}
		if n <= 0 || err != nil {
			return cmp.Or(err, errors.New(durationErrParse))
		}
		b = b[n:]
	}
	return durationEnd(b, err)
}

// ProtoCheckInitialized returns an error if a required field of m or of a message in m is not set.
func (m *Duration) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *Duration) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e, implementing json.MarshalerTo from encoding/json/v2.
func (m *Duration) MarshalJSONTo(e *jsontext.Encoder) error {
	return durationMarshalTo(e, m.ProtoAppendJSON)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b, without checking required fields.
func (m *Duration) ProtoAppendJSON(b []byte) ([]byte, error) {
	var s int64
	var ns int32
	if m != nil {
		s, ns = m.Seconds, m.Nanos
	}
	if s < -durationMaxDurationSeconds || s > durationMaxDurationSeconds || ns <= -durationNanosPerSecond || ns >= durationNanosPerSecond || (s > 0 && ns < 0) || (s < 0 && ns > 0) {
		return nil, errors.New(durationDurationErrOutOfRange)
	}
	b = append(b, '"')
	if s < 0 || ns < 0 {
		b = append(b, '-')
		s, ns = -s, -ns
	}
	b = strconv.AppendInt(b, s, 10)
	switch {
	case ns == 0:
	case ns%durationNanosPerMilli == 0:
		b = append(b, '.')
		b = append(b, strconv.Itoa(durationMillisPerSecond + int(ns)/durationNanosPerMilli)[1:]...)
	case ns%durationNanosPerMicro == 0:
		b = append(b, '.')
		b = append(b, strconv.Itoa(durationMicrosPerSecond + int(ns)/durationNanosPerMicro)[1:]...)
	default:
		b = append(b, '.')
		b = append(b, strconv.Itoa(durationNanosPerSecond + int(ns))[1:]...)
	}
	b = append(b, "s\""...)
	return b, nil
}

// UnmarshalJSON replaces the contents of m with the ProtoJSON value in b.
func (m *Duration) UnmarshalJSON(b []byte) error { *m = Duration{}; return m.ProtoMergeJSON(b) }

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m, without checking required fields.
func (m *Duration) ProtoMergeJSON(b []byte) error {
	return durationMergeJSON(b, "google.protobuf.Duration", m.ProtoMergeJSONFrom)
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value read from d, implementing json.UnmarshalerFrom from encoding/json/v2.
func (m *Duration) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	*m = Duration{}
	return durationMergeFrom(d, m.ProtoMergeJSONFrom)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it into m, without checking required fields; d should reject invalid UTF-8, as jsontext decoders do by default.
func (m *Duration) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	tok, err := d.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() == jsontext.KindNull {
		return nil
	}
	if tok.Kind() != jsontext.KindString {
		return errors.New("proto: google.protobuf.Duration: expected a JSON string")
	}
	s := tok.String()
	in := s
	neg := false
	if strings.HasPrefix(s, "-") {
		neg, s = true, s[1:]
	}
	whole, frac, dot := strings.Cut(strings.TrimSuffix(s, "s"), ".")
	if !strings.HasSuffix(s, "s") || whole == "" || strings.Trim(whole, "0123456789") != "" ||
		(dot && (frac == "" || len(frac) > durationMaxFracDigits || strings.Trim(frac, "0123456789") != "")) {
		return errors.New("proto: google.protobuf.Duration: invalid duration " + strconv.Quote(in))
	}
	secs, err := strconv.ParseInt(whole, 10, 64)
	if err != nil || secs > durationMaxDurationSeconds {
		return errors.New(durationDurationErrOutOfRange)
	}
	var nanos int64
	if dot {
		nanos, _ = strconv.ParseInt(frac, 10, 64)
		for range durationMaxFracDigits - len(frac) {
			nanos *= 10
		}
	}
	if neg {
		secs, nanos = -secs, -nanos
	}
	m.Seconds, m.Nanos = secs, int32(nanos)
	return nil
}

var (
	durationZeroDuration Duration
)

func durationSizeVarint(tag int, u uint64) int {
	return durationIf(u == 0, 0, tag+durationVarintLen(u))
}
func durationVarintLen[T ~int | ~int32 | ~int64 | ~uint32 | ~uint64](v T) int {
	return (bits.Len64(uint64(int64(v))|1) + durationVarintPayloadBits - 1) / durationVarintPayloadBits
}
func durationCopyUnknown(b []byte, i int, u []byte) int {
	if len(u) > 0 {
		i -= copy(b[i-len(u):], u)
	}
	return i
}
func durationAppendBinary(b []byte, size int, marshal func([]byte) (int, error)) ([]byte, error) {
	b = slices.Grow(b, size)
	n, err := marshal(b[len(b) : len(b)+size])
	if err == nil && n != size {
		err = errors.New("proto: message size changed during marshal")
	}
	if err != nil {
		return b, err
	}
	return b[:len(b)+size], nil
}
func durationPutVarintField(b []byte, i int, u uint64, tag byte) int {
	if u == 0 {
		return i
	}
	i -= (bits.Len64(u|1)+durationVarintPayloadBits-1)/durationVarintPayloadBits + 1
	b[i] = tag
	p := i + 1
	for ; u >= durationVarintContBit; u >>= durationVarintPayloadBits {
		b[p] = byte(u) | durationVarintContBit
		p++
	}
	b[p] = byte(u)
	return i
}
func durationIf[T any](c bool, a, b T) T {
	if c {
		return a
	}
	return b
}
func durationDepth(depth int) error {
	if depth >= durationMaxDepth {
		return errors.New("proto: exceeded maximum recursion depth")
	}
	return nil
}
func durationReadBytes(b []byte) (v []byte, n int) {
	ln, k := binary.Uvarint(b)
	if k <= 0 || ln > uint64(len(b)-k) {
		return nil, -1
	}
	return b[k : k+int(ln)], k + int(ln)
}
func durationSkipField(b []byte, t uint64, depth int) (int, error) {
	n, num := 0, t>>durationTagTypeBits
	switch wt := t & durationTagTypeMask; {
	case num == 0 || num > durationMaxFieldNumber:
	case wt == durationWireVarint:
		_, n = binary.Uvarint(b)
	case wt == durationWireBytes:
		_, n = durationReadBytes(b)
	case wt == durationWireStartGroup:
		return durationSkipGroup(b, int32(num), depth+1)
	case wt == durationWireFixed64 || wt == durationWireFixed32:
		n = durationIf(wt == durationWireFixed64, durationFixed64Size, durationFixed32Size)
		n = durationIf(len(b) >= n, n, 0)
	}
	if n <= 0 {
		return 0, errors.New(durationErrParse)
	}
	return n, nil
}
func durationSkipGroup(b []byte, num int32, depth int) (int, error) {
	n, err := 0, durationDepth(depth)
	for err == nil {
		t, k := binary.Uvarint(b[n:])
		if k <= 0 {
			return 0, errors.New(durationErrParse)
		}
		if n += k; t == uint64(num)<<durationTagTypeBits|durationWireEndGroup {
			return n, nil
		}
		k, err = durationSkipField(b[n:], t, depth)
		n += k
	}
	return 0, err
}
func durationUnknown(b []byte, t uint64, depth int, unk *[]byte) (int, error) {
	n, err := durationSkipField(b, t, depth)
	if err == nil {
		*unk = append(binary.AppendUvarint(*unk, t), b[:n]...)
	}
	return n, err
}
func durationEnd(b []byte, err error) error {
	if err == nil && len(b) > 0 {
		return errors.New(durationErrParse)
	}
	return err
}
func durationVarint[T ~int | ~int32 | ~int64 | ~uint32 | ~uint64](b []byte, p *T) int {
	u, n := binary.Uvarint(b)
	*p = T(u)
	return n
}
func durationMarshalTo(e *jsontext.Encoder, f func([]byte) ([]byte, error)) error {
	b, err := f(e.AvailableBuffer())
	if err != nil {
		return err
	}
	return e.WriteValue(b)
}
func durationMergeJSON(b []byte, name string, merge func(*jsontext.Decoder) error) error {
	d := jsontext.NewDecoder(bytes.NewBuffer(b))
	if err := merge(d); err != nil {
		return err
	}
	if _, err := d.ReadToken(); err != io.EOF {
		return durationJSONError(name, "unexpected data after JSON value")
	}
	return nil
}
func durationMergeFrom(d *jsontext.Decoder, merge func(*jsontext.Decoder) error) error {
	d, err := durationStrictDecoder(d)
	return cmp.Or(err, merge(d))
}
func durationStrictDecoder(d *jsontext.Decoder) (*jsontext.Decoder, error) {
	if lax, _ := json.GetOption(d.Options(), jsontext.AllowInvalidUTF8); !lax {
		return d, nil
	}
	v, err := d.ReadValue()
	if err != nil {
		return d, err
	}
	return jsontext.NewDecoder(bytes.NewBuffer(v)), nil
}
func durationJSONError(name, msg string) error { return errors.New("proto: " + name + ": " + msg) }
