// Code generated by cotorp. DO NOT EDIT.
// source: google/protobuf/empty.proto

package wktpb

import (
	"bytes"
	"encoding/binary"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"io"
	"slices"
	"strconv"
)

// Wire types.
const (
	emptyWireVarint     = 0
	emptyWireFixed64    = 1
	emptyWireBytes      = 2
	emptyWireStartGroup = 3
	emptyWireEndGroup   = 4
	emptyWireFixed32    = 5
)

// A tag holds the field number above the wire type in its low three bits.
const (
	emptyTagTypeBits    = 3
	emptyTagTypeMask    = 1<<3 - 1
	emptyMaxFieldNumber = 1<<29 - 1
)

// Encoded sizes.
const (
	emptyFixed32Size = 4
	emptyFixed64Size = 8
)

// Decoding limits.
const (
	emptyMaxDepth      = 10000 // maximum message and group nesting
	emptySkipStackSize = 16    // group nesting tracked without allocating
)

// Error messages used more than once.
const (
	emptyErrParse = "proto: cannot parse invalid wire-format data"
	emptyErrDepth = "proto: exceeded maximum recursion depth"
)

// A generic empty message that you can re-use to avoid defining duplicated
// empty messages in your APIs. A typical example is to use it as the request
// or the response type of an API method. For instance:
//
//	service Foo {
//	  rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty);
//	}
type Empty struct {
	unknownFields []byte
}

// Reset clears all fields of m.
func (m *Empty) Reset() { *m = Empty{} }

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *Empty) ProtoUnknownFields() []byte {
	if m == nil {
		return nil
	}
	return m.unknownFields
}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *Empty) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *Empty) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *Empty) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	b = slices.Grow(b, size)
	n, err := m.ProtoMarshalToSizedBuffer(b[len(b) : len(b)+size])
	return emptyAppended(b, size, n, err)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *Empty) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if len(m.unknownFields) > 0 {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *Empty) UnmarshalBinary(b []byte) error {
	*m = Empty{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *Empty) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *Empty) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= emptyMaxDepth {
		goto errDepth
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>emptyTagTypeBits == 0 || t>>emptyTagTypeBits > emptyMaxFieldNumber {
			goto errParse
		}
		start := b
		b = b[n:]
		// Unknown field, or a known field with an unexpected wire type.
		n, err := emptySkipField(b, t, depth)
		if err != nil {
			return err
		}
		m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
		b = b[n:]
	}
	return nil
errParse:
	return errors.New(emptyErrParse)
errDepth:
	return errors.New(emptyErrDepth)
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *Empty) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *Empty) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e. It implements
// json.MarshalerTo from encoding/json/v2.
func (m *Empty) MarshalJSONTo(e *jsontext.Encoder) error {
	b, err := m.ProtoAppendJSON(e.AvailableBuffer())
	return emptyWriteJSON(e, b, err)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b. It does not
// check required fields.
func (m *Empty) ProtoAppendJSON(b []byte) ([]byte, error) {
	if m == nil {
		return append(b, "{}"...), nil
	}
	start := len(b)
	return emptyCloseObject(b, start), nil
}

// UnmarshalJSON replaces the contents of m with the decoded ProtoJSON
// value in b.
func (m *Empty) UnmarshalJSON(b []byte) error {
	*m = Empty{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m.
// It does not check required fields.
func (m *Empty) ProtoMergeJSON(b []byte) error {
	d := jsontext.NewDecoder(bytes.NewBuffer(b))
	return emptyEndJSON(d, m.ProtoMergeJSONFrom(d), "google.protobuf.Empty")
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value
// read from d. It implements json.UnmarshalerFrom from encoding/json/v2.
func (m *Empty) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	d, err := emptyStrictDecoder(d)
	if err != nil {
		return err
	}
	*m = Empty{}
	return m.ProtoMergeJSONFrom(d)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it
// into m. It does not check required fields. d should reject invalid
// UTF-8, as jsontext decoders do by default.
func (m *Empty) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	ok, err := emptyOpenJSON(d, jsontext.KindBeginObject, "google.protobuf.Empty", "object")
	if !ok {
		return err
	}
	if d.PeekKind() != jsontext.KindEndObject {
		kt, err := d.ReadToken()
		if err != nil {
			return err
		}
		return errors.New("proto: google.protobuf.Empty: unknown field " + strconv.Quote(kt.String()))
	}
	_, err = d.ReadToken()
	return err
}

// emptyReadBytes returns the length-delimited value at the start of b and the
// number of bytes it occupies, or n < 0 if it is malformed.
func emptyReadBytes(b []byte) (v []byte, n int) {
	ln, k := binary.Uvarint(b)
	if k <= 0 || ln > uint64(len(b)-k) {
		return nil, -1
	}
	return b[k : k+int(ln)], k + int(ln)
}

// emptySkipField returns the length of the value at the start of b of a field
// with tag t, in a message nested depth levels deep.
func emptySkipField(b []byte, t uint64, depth int) (int, error) {
	switch t & emptyTagTypeMask {
	case emptyWireVarint:
		if _, n := binary.Uvarint(b); n > 0 {
			return n, nil
		}
	case emptyWireFixed64:
		if len(b) >= emptyFixed64Size {
			return emptyFixed64Size, nil
		}
	case emptyWireBytes:
		if _, n := emptyReadBytes(b); n >= 0 {
			return n, nil
		}
	case emptyWireStartGroup:
		return emptySkipGroup(b, int32(t>>emptyTagTypeBits), depth)
	case emptyWireFixed32:
		if len(b) >= emptyFixed32Size {
			return emptyFixed32Size, nil
		}
	}
	return 0, errors.New(emptyErrParse)
}

// emptySkipGroup returns the length of the body of group num at the start of
// b, including its end-group tag, in a message nested depth levels deep.
// Nested groups are tracked with a small stack.
func emptySkipGroup(b []byte, num int32, depth int) (int, error) {
	var stk [emptySkipStackSize]int32
	open := append(stk[:0], num)
	n := 0
	for len(open) > 0 {
		if depth+len(open) > emptyMaxDepth {
			return 0, errors.New(emptyErrDepth)
		}
		t, k := binary.Uvarint(b[n:])
		if k <= 0 || t>>emptyTagTypeBits == 0 || t>>emptyTagTypeBits > emptyMaxFieldNumber {
			return 0, errors.New(emptyErrParse)
		}
		n += k
		switch t & emptyTagTypeMask {
		case emptyWireStartGroup:
			open = append(open, int32(t>>emptyTagTypeBits))
		case emptyWireEndGroup:
			if open[len(open)-1] != int32(t>>emptyTagTypeBits) {
				return 0, errors.New(emptyErrParse)
			}
			open = open[:len(open)-1]
		default:
			k, err := emptySkipField(b[n:], t, depth)
			if err != nil {
				return 0, err
			}
			n += k
		}
	}
	return n, nil
}

// emptyAppended finishes AppendBinary: b has capacity for size more bytes,
// of which ProtoMarshalToSizedBuffer wrote n or failed with err.
func emptyAppended(b []byte, size, n int, err error) ([]byte, error) {
	if err == nil && n != size {
		err = errors.New("proto: message size changed during marshal")
	}
	if err != nil {
		return b, err
	}
	return b[:len(b)+size], nil
}

// emptyWriteJSON finishes MarshalJSONTo: it writes the JSON value b to e,
// unless producing b failed with err.
func emptyWriteJSON(e *jsontext.Encoder, b []byte, err error) error {
	if err != nil {
		return err
	}
	return e.WriteValue(b)
}

// emptyCloseObject finishes a JSON object whose members were appended to b from
// index start, each preceded by a comma: the first comma becomes the
// opening brace.
func emptyCloseObject(b []byte, start int) []byte {
	if len(b) == start {
		return append(b, "{}"...)
	}
	b[start] = '{'
	return append(b, '}')
}

// emptyEndJSON finishes ProtoMergeJSON for message name: decoding one value
// from d failed with err, or d must have no more data.
func emptyEndJSON(d *jsontext.Decoder, err error, name string) error {
	if err != nil {
		return err
	}
	if _, err := d.ReadToken(); err != io.EOF {
		return emptyJSONError(name, "unexpected data after JSON value")
	}
	return nil
}

// emptyStrictDecoder returns d, or a strict decoder for the next value of d if d
// replaces invalid UTF-8 (as encoding/json's decoder does), which
// ProtoJSON rejects.
func emptyStrictDecoder(d *jsontext.Decoder) (*jsontext.Decoder, error) {
	if lax, _ := json.GetOption(d.Options(), jsontext.AllowInvalidUTF8); !lax {
		return d, nil
	}
	v, err := d.ReadValue()
	if err != nil {
		return nil, err
	}
	return jsontext.NewDecoder(bytes.NewBuffer(v)), nil
}

// emptyOpenJSON reads the first token of the value of message name, which
// must be of the given kind. It reports false if the value is null, which
// leaves the message unchanged, or on error.
func emptyOpenJSON(d *jsontext.Decoder, kind jsontext.Kind, name, what string) (bool, error) {
	if d.PeekKind() == jsontext.KindNull {
		return false, d.SkipValue()
	}
	err := emptyExpectJSON(d, kind, name, what)
	return err == nil, err
}

// emptyExpectJSON reads a token of the given kind, a JSON what, in message name.
func emptyExpectJSON(d *jsontext.Decoder, kind jsontext.Kind, name, what string) error {
	tok, err := d.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != kind {
		return emptyJSONError(name, "expected a JSON "+what)
	}
	return nil
}

// emptyJSONError returns an error about the ProtoJSON value of message name.
func emptyJSONError(name, msg string) error {
	return errors.New("proto: " + name + ": " + msg)
}
