// Code generated by cotorp. DO NOT EDIT.
// source: google/protobuf/empty.proto

package wktpb

import (
	"bytes"
	"cmp"
	"encoding/binary"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"io"
	"slices"
	"strconv"
)

const (
	emptyWireVarint     = 0
	emptyWireFixed64    = 1
	emptyWireBytes      = 2
	emptyWireStartGroup = 3
	emptyWireEndGroup   = 4
	emptyWireFixed32    = 5
	emptyTagTypeBits    = 3
	emptyTagTypeMask    = 1<<3 - 1
	emptyMaxFieldNumber = 1<<29 - 1
	emptyFixed32Size    = 4
	emptyFixed64Size    = 8
	emptyMaxDepth       = 10000
	emptyErrParse       = "proto: cannot parse invalid wire-format data"
)

// A generic empty message that you can re-use to avoid defining duplicated
// empty messages in your APIs. A typical example is to use it as the request
// or the response type of an API method. For instance:
//
//	service Foo {
//	  rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty);
//	}
type Empty struct {
	unknownFields []byte
}

// Reset clears all fields of m.
func (m *Empty) Reset()    { *m = Empty{} }
func (m *Empty) z() *Empty { return emptyIf(m == nil, &emptyZeroEmpty, m) }

// ProtoUnknownFields returns the raw bytes of fields that were not recognized when m was decoded.
func (m *Empty) ProtoUnknownFields() []byte { return m.z().unknownFields }

// ProtoSize returns the size of the wire-format encoding of m.
func (m *Empty) ProtoSize() (n int) {
	m = m.z()
	return n + len(m.unknownFields)
}

// MarshalBinary returns the wire-format encoding of m.
func (m *Empty) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *Empty) AppendBinary(b []byte) ([]byte, error) {
	return emptyAppendBinary(b, m.ProtoSize(), m.ProtoMarshalToSizedBuffer)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must hold m.ProtoSize() bytes, and returns the count written, without checking required fields.
func (m *Empty) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	m = m.z()
	i := emptyCopyUnknown(b, len(b), m.unknownFields)
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the wire-format message in b.
func (m *Empty) UnmarshalBinary(b []byte) error { *m = Empty{}; return m.ProtoMergeDepth(b, 0) }

// ProtoMerge decodes the wire-format message in b and merges it into m, without checking required fields.
func (m *Empty) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *Empty) ProtoMergeDepth(b []byte, depth int) error {
	err := emptyDepth(depth)
	for t, n := binary.Uvarint(b); n > 0 && err == nil; t, n = binary.Uvarint(b) {
		b = b[n:]
		n, err = emptyUnknown(b, t, depth, &m.unknownFields)
		if n <= 0 || err != nil {
			return cmp.Or(err, errors.New(emptyErrParse))
		}
		b = b[n:]
	}
	return emptyEnd(b, err)
}

// ProtoCheckInitialized returns an error if a required field of m or of a message in m is not set.
func (m *Empty) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *Empty) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e, implementing json.MarshalerTo from encoding/json/v2.
func (m *Empty) MarshalJSONTo(e *jsontext.Encoder) error {
	return emptyMarshalTo(e, m.ProtoAppendJSON)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b, without checking required fields.
func (m *Empty) ProtoAppendJSON(b []byte) ([]byte, error) {
	m, start := m.z(), len(b)
	return emptyCloseObject(b, start), nil
}

// UnmarshalJSON replaces the contents of m with the ProtoJSON value in b.
func (m *Empty) UnmarshalJSON(b []byte) error { *m = Empty{}; return m.ProtoMergeJSON(b) }

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m, without checking required fields.
func (m *Empty) ProtoMergeJSON(b []byte) error {
	return emptyMergeJSON(b, "google.protobuf.Empty", m.ProtoMergeJSONFrom)
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value read from d, implementing json.UnmarshalerFrom from encoding/json/v2.
func (m *Empty) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	*m = Empty{}
	return emptyMergeFrom(d, m.ProtoMergeJSONFrom)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it into m, without checking required fields; d should reject invalid UTF-8, as jsontext decoders do by default.
func (m *Empty) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	for kt, err := emptyOpenObject(d, "google.protobuf.Empty"); kt.Kind() != jsontext.KindEndObject; kt, err = emptyNextKey(d, err) {
		if err != nil {
			return err
		}
		return errors.New("proto: google.protobuf.Empty: unknown field " + strconv.Quote(kt.String()))
	}
	return nil
}

var (
	emptyZeroEmpty Empty
)

func emptyCopyUnknown(b []byte, i int, u []byte) int {
	if len(u) > 0 {
		i -= copy(b[i-len(u):], u)
	}
	return i
}
func emptyAppendBinary(b []byte, size int, marshal func([]byte) (int, error)) ([]byte, error) {
	b = slices.Grow(b, size)
	n, err := marshal(b[len(b) : len(b)+size])
	if err == nil && n != size {
		err = errors.New("proto: message size changed during marshal")
	}
	if err != nil {
		return b, err
	}
	return b[:len(b)+size], nil
}
func emptyIf[T any](c bool, a, b T) T {
	if c {
		return a
	}
	return b
}
func emptyDepth(depth int) error {
	if depth >= emptyMaxDepth {
		return errors.New("proto: exceeded maximum recursion depth")
	}
	return nil
}
func emptyReadBytes(b []byte) (v []byte, n int) {
	ln, k := binary.Uvarint(b)
	if k <= 0 || ln > uint64(len(b)-k) {
		return nil, -1
	}
	return b[k : k+int(ln)], k + int(ln)
}
func emptySkipField(b []byte, t uint64, depth int) (int, error) {
	n, num := 0, t>>emptyTagTypeBits
	switch wt := t & emptyTagTypeMask; {
	case num == 0 || num > emptyMaxFieldNumber:
	case wt == emptyWireVarint:
		_, n = binary.Uvarint(b)
	case wt == emptyWireBytes:
		_, n = emptyReadBytes(b)
	case wt == emptyWireStartGroup:
		return emptySkipGroup(b, int32(num), depth+1)
	case wt == emptyWireFixed64 || wt == emptyWireFixed32:
		n = emptyIf(wt == emptyWireFixed64, emptyFixed64Size, emptyFixed32Size)
		n = emptyIf(len(b) >= n, n, 0)
	}
	if n <= 0 {
		return 0, errors.New(emptyErrParse)
	}
	return n, nil
}
func emptySkipGroup(b []byte, num int32, depth int) (int, error) {
	n, err := 0, emptyDepth(depth)
	for err == nil {
		t, k := binary.Uvarint(b[n:])
		if k <= 0 {
			return 0, errors.New(emptyErrParse)
		}
		if n += k; t == uint64(num)<<emptyTagTypeBits|emptyWireEndGroup {
			return n, nil
		}
		k, err = emptySkipField(b[n:], t, depth)
		n += k
	}
	return 0, err
}
func emptyUnknown(b []byte, t uint64, depth int, unk *[]byte) (int, error) {
	n, err := emptySkipField(b, t, depth)
	if err == nil {
		*unk = append(binary.AppendUvarint(*unk, t), b[:n]...)
	}
	return n, err
}
func emptyEnd(b []byte, err error) error {
	if err == nil && len(b) > 0 {
		return errors.New(emptyErrParse)
	}
	return err
}
func emptyMarshalTo(e *jsontext.Encoder, f func([]byte) ([]byte, error)) error {
	b, err := f(e.AvailableBuffer())
	if err != nil {
		return err
	}
	return e.WriteValue(b)
}
func emptyCloseObject(b []byte, start int) []byte {
	if len(b) == start {
		return append(b, "{}"...)
	}
	b[start] = '{'
	return append(b, '}')
}
func emptyMergeJSON(b []byte, name string, merge func(*jsontext.Decoder) error) error {
	d := jsontext.NewDecoder(bytes.NewBuffer(b))
	if err := merge(d); err != nil {
		return err
	}
	if _, err := d.ReadToken(); err != io.EOF {
		return emptyJSONError(name, "unexpected data after JSON value")
	}
	return nil
}
func emptyMergeFrom(d *jsontext.Decoder, merge func(*jsontext.Decoder) error) error {
	d, err := emptyStrictDecoder(d)
	return cmp.Or(err, merge(d))
}
func emptyStrictDecoder(d *jsontext.Decoder) (*jsontext.Decoder, error) {
	if lax, _ := json.GetOption(d.Options(), jsontext.AllowInvalidUTF8); !lax {
		return d, nil
	}
	v, err := d.ReadValue()
	if err != nil {
		return d, err
	}
	return jsontext.NewDecoder(bytes.NewBuffer(v)), nil
}
func emptyExpectJSON(d *jsontext.Decoder, kind jsontext.Kind, name, what string) error {
	tok, err := d.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != kind {
		return emptyJSONError(name, "expected a JSON "+what)
	}
	return nil
}
func emptyOpenObject(d *jsontext.Decoder, name string) (jsontext.Token, error) {
	if d.PeekKind() == jsontext.KindNull {
		return jsontext.EndObject, d.SkipValue()
	}
	return emptyNextKey(d, emptyExpectJSON(d, jsontext.KindBeginObject, name, "object"))
}
func emptyNextKey(d *jsontext.Decoder, err error) (jsontext.Token, error) {
	if err != nil {
		return jsontext.Token{}, err
	}
	return d.ReadToken()
}
func emptyJSONError(name, msg string) error { return errors.New("proto: " + name + ": " + msg) }
