// Code generated by cotorp. DO NOT EDIT.
// source: google/protobuf/field_mask.proto

package wktpb

import (
	"bytes"
	"cmp"
	"encoding/binary"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"io"
	"math/bits"
	"slices"
	"strconv"
	"strings"
	"unicode/utf8"
)

const (
	fieldMaskWireVarint        = 0
	fieldMaskWireFixed64       = 1
	fieldMaskWireBytes         = 2
	fieldMaskWireStartGroup    = 3
	fieldMaskWireEndGroup      = 4
	fieldMaskWireFixed32       = 5
	fieldMaskTagTypeBits       = 3
	fieldMaskTagTypeMask       = 1<<3 - 1
	fieldMaskMaxFieldNumber    = 1<<29 - 1
	fieldMaskFixed32Size       = 4
	fieldMaskFixed64Size       = 8
	fieldMaskVarintPayloadBits = 7
	fieldMaskVarintContBit     = 0x80
	fieldMaskMaxDepth          = 10000
	fieldMaskE1                = "proto: field google.protobuf.FieldMask.paths contains invalid UTF-8"
	fieldMaskE2                = "proto: cannot parse invalid wire-format data"
	fieldMaskE3                = "proto: google.protobuf.FieldMask: path cannot be represented in JSON: "
)

// `FieldMask` represents a set of symbolic field paths, for example:
//
//	paths: "f.a"
//	paths: "f.b.d"
//
// Here `f` represents a field in some root message, `a` and `b`
// fields in the message found in `f`, and `d` a field found in the
// message in `f.b`.
//
// Field masks are used to specify a subset of fields that should be
// returned by a get operation or modified by an update operation.
// Field masks also have a custom JSON encoding (see below).
//
// # Field Masks in Projections
//
// When used in the context of a projection, a response message or
// sub-message is filtered by the API to only contain those fields as
// specified in the mask. For example, if the mask in the previous
// example is applied to a response message as follows:
//
//	f {
//	  a : 22
//	  b {
//	    d : 1
//	    x : 2
//	  }
//	  y : 13
//	}
//	z: 8
//
// The result will not contain specific values for fields x,y and z
// (their value will be set to the default, and omitted in proto text
// output):
//
//	f {
//	  a : 22
//	  b {
//	    d : 1
//	  }
//	}
//
// A repeated field is not allowed except at the last position of a
// paths string.
//
// If a FieldMask object is not present in a get operation, the
// operation applies to all fields (as if a FieldMask of all fields
// had been specified).
//
// Note that a field mask does not necessarily apply to the
// top-level response message. In case of a REST get operation, the
// field mask applies directly to the response, but in case of a REST
// list operation, the mask instead applies to each individual message
// in the returned resource list. In case of a REST custom method,
// other definitions may be used. Where the mask applies will be
// clearly documented together with its declaration in the API.  In
// any case, the effect on the returned resource/resources is required
// behavior for APIs.
//
// # Field Masks in Update Operations
//
// A field mask in update operations specifies which fields of the
// targeted resource are going to be updated. The API is required
// to only change the values of the fields as specified in the mask
// and leave the others untouched. If a resource is passed in to
// describe the updated values, the API ignores the values of all
// fields not covered by the mask.
//
// If a repeated field is specified for an update operation, new values will
// be appended to the existing repeated field in the target resource. Note that
// a repeated field is only allowed in the last position of a `paths` string.
//
// If a sub-message is specified in the last position of the field mask for an
// update operation, then new value will be merged into the existing sub-message
// in the target resource.
//
// For example, given the target message:
//
//	f {
//	  b {
//	    d: 1
//	    x: 2
//	  }
//	  c: [1]
//	}
//
// And an update message:
//
//	f {
//	  b {
//	    d: 10
//	  }
//	  c: [2]
//	}
//
// then if the field mask is:
//
//	paths: ["f.b", "f.c"]
//
// then the result will be:
//
//	f {
//	  b {
//	    d: 10
//	    x: 2
//	  }
//	  c: [1, 2]
//	}
//
// An implementation may provide options to override this default behavior for
// repeated and message fields.
//
// Note that libraries which implement FieldMask resolution have various
// different behaviors in the face of empty masks or the special "*" mask.
// When implementing a service you should confirm these cases have the
// appropriate behavior in the underlying FieldMask library that you desire,
// and you may need to special case those cases in your application code if
// the underlying field mask library behavior differs from your intended
// service semantics.
//
// Update methods implementing https://google.aip.dev/134
// - MUST support the special value * meaning "full replace"
// - MUST treat an omitted field mask as "replace fields which are present".
//
// Other methods implementing https://google.aip.dev/157
// - SHOULD support the special value "*" to mean "get all".
// - MUST treat an omitted field mask to mean "get all", unless otherwise
// documented.
//
// ## Considerations for HTTP REST
//
// The HTTP kind of an update operation which uses a field mask must
// be set to PATCH instead of PUT in order to satisfy HTTP semantics
// (PUT must only be used for full updates).
//
// # JSON Encoding of Field Masks
//
// In JSON, a field mask is encoded as a single string where paths are
// separated by a comma. Fields name in each path are converted
// to/from lower-camel naming conventions.
//
// As an example, consider the following message declarations:
//
//	message Profile {
//	  User user = 1;
//	  Photo photo = 2;
//	}
//	message User {
//	  string display_name = 1;
//	  string address = 2;
//	}
//
// In proto a field mask for `Profile` may look as such:
//
//	mask {
//	  paths: "user.display_name"
//	  paths: "photo"
//	}
//
// In JSON, the same mask is represented as below:
//
//	{
//	  mask: "user.displayName,photo"
//	}
//
// # Field Masks and Oneof Fields
//
// Field masks treat fields in oneofs just as regular fields. Consider the
// following message:
//
//	message SampleMessage {
//	  oneof test_oneof {
//	    string name = 4;
//	    SubMessage sub_message = 9;
//	  }
//	}
//
// The field mask can be:
//
//	mask {
//	  paths: "name"
//	}
//
// Or:
//
//	mask {
//	  paths: "sub_message"
//	}
//
// Note that oneof type names ("test_oneof" in this case) cannot be used in
// paths.
//
// ## Field Mask Verification
//
// The implementation of any API method which has a FieldMask type field in the
// request should verify the included field paths, and return an
// `INVALID_ARGUMENT` error if any path is unmappable.
type FieldMask struct {
	// The set of field mask paths.
	Paths []string

	u []byte
}

// Reset clears all fields of m.
func (m *FieldMask) Reset()             { *m = FieldMask{} }
func (m *FieldMask) z() *FieldMask      { return fieldMaskIf(m == nil, &fieldMaskZFieldMask, m) }
func (m *FieldMask) GetPaths() []string { return m.z().Paths }

// ProtoUnknownFields returns the raw bytes of fields that were not recognized when m was decoded.
func (m *FieldMask) ProtoUnknownFields() []byte { return m.z().u }

// ProtoSize returns the size of the wire-format encoding of m.
func (m *FieldMask) ProtoSize() (n int) {
	m = m.z()
	n += fieldMaskSizeEach(1, m.Paths, fieldMaskBytesLen)
	return n + len(m.u)
}

// MarshalBinary returns the wire-format encoding of m.
func (m *FieldMask) MarshalBinary() ([]byte, error) { return m.AppendBinary(nil) }

// AppendBinary appends the wire-format encoding of m to b.
func (m *FieldMask) AppendBinary(b []byte) ([]byte, error) {
	return fieldMaskAppendBinary(b, m.ProtoSize(), m.ProtoMarshalToSizedBuffer)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must hold m.ProtoSize() bytes, and returns the count written, without checking required fields.
func (m *FieldMask) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	m = m.z()
	i := fieldMaskCopyUnknown(b, len(b), m.u)
	for _, v := range slices.Backward(m.Paths) {
		if !utf8.ValidString(v) {
			return 0, errors.New(fieldMaskE1)
		}
		i = fieldMaskPutVarint(b, fieldMaskPutVarint(b, i-copy(b[i-len(v):], v), uint64(len(v))), 1<<fieldMaskTagTypeBits|fieldMaskWireBytes)
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the wire-format message in b.
func (m *FieldMask) UnmarshalBinary(b []byte) error { *m = FieldMask{}; return m.ProtoMergeDepth(b, 0) }

// ProtoMerge decodes the wire-format message in b and merges it into m, without checking required fields.
func (m *FieldMask) ProtoMerge(b []byte) error { return m.ProtoMergeDepth(b, 0) }

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *FieldMask) ProtoMergeDepth(b []byte, depth int) error {
	err := fieldMaskDepth(depth)
	for t, n := binary.Uvarint(b); n > 0 && err == nil; t, n = binary.Uvarint(b) {
		b = b[n:]
		switch t {
		case 1<<fieldMaskTagTypeBits | fieldMaskWireBytes:
			n, err = fieldMaskString(b, fieldMaskGrow(&m.Paths), fieldMaskE1)
		default:
			n, err = fieldMaskUnknown(b, t, depth, &m.u)
		}
		if n <= 0 || err != nil {
			return cmp.Or(err, errors.New(fieldMaskE2))
		}
		b = b[n:]
	}
	return fieldMaskEnd(b, err)
}

// ProtoCheckInitialized returns an error if a required field of m or of a message in m is not set.
func (m *FieldMask) ProtoCheckInitialized() error { return nil }

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *FieldMask) MarshalJSON() ([]byte, error) { return m.ProtoAppendJSON(nil) }

// MarshalJSONTo writes the ProtoJSON encoding of m to e, implementing json.MarshalerTo from encoding/json/v2.
func (m *FieldMask) MarshalJSONTo(e *jsontext.Encoder) error {
	return fieldMaskMarshalTo(e, m.ProtoAppendJSON)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b, without checking required fields.
func (m *FieldMask) ProtoAppendJSON(b []byte) ([]byte, error) {
	b = append(b, '"')
	if m != nil {
		for j, p := range m.Paths {
			if j > 0 {
				b = append(b, ',')
			}
			for ci := 0; ci < len(p); ci++ {
				switch c := p[ci]; {
				case c == '_':
					if ci+1 >= len(p) || p[ci+1] < 'a' || p[ci+1] > 'z' {
						return nil, errors.New(fieldMaskE3 + strconv.Quote(p))
					}
					ci++
					b = append(b, p[ci]-('a'-'A'))
				case c >= 'A' && c <= 'Z', c < ' ', c == '"', c == '\\', c == ',':
					return nil, errors.New(fieldMaskE3 + strconv.Quote(p))
				default:
					b = append(b, c)
				}
			}
		}
	}
	b = append(b, '"')
	return b, nil
}

// UnmarshalJSON replaces the contents of m with the ProtoJSON value in b.
func (m *FieldMask) UnmarshalJSON(b []byte) error { *m = FieldMask{}; return m.ProtoMergeJSON(b) }

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m, without checking required fields.
func (m *FieldMask) ProtoMergeJSON(b []byte) error {
	return fieldMaskMergeJSON(b, "google.protobuf.FieldMask", m.ProtoMergeJSONFrom)
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value read from d, implementing json.UnmarshalerFrom from encoding/json/v2.
func (m *FieldMask) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	*m = FieldMask{}
	return fieldMaskMergeFrom(d, m.ProtoMergeJSONFrom)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it into m, without checking required fields; d should reject invalid UTF-8, as jsontext decoders do by default.
func (m *FieldMask) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	tok, err := d.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() == jsontext.KindNull {
		return nil
	}
	if tok.Kind() != jsontext.KindString {
		return errors.New("proto: google.protobuf.FieldMask: expected a JSON string")
	}
	s := tok.String()
	if s == "" {
		return nil
	}
	for _, p := range strings.Split(s, ",") {
		var sb []byte
		for ci := 0; ci < len(p); ci++ {
			switch c := p[ci]; {
			case c == '_':
				return errors.New("proto: google.protobuf.FieldMask: invalid path " + strconv.Quote(p))
			case c >= 'A' && c <= 'Z':
				sb = append(sb, '_', c+('a'-'A'))
			default:
				sb = append(sb, c)
			}
		}
		m.Paths = append(m.Paths, string(sb))
	}
	return nil
}

var (
	fieldMaskZFieldMask FieldMask
)

func fieldMaskSizeLen(l int) int { return l + fieldMaskVarintLen(l) }
func fieldMaskSizeEach[T any](tag int, s []T, size func(T) int) (n int) {
	for _, v := range s {
		n += tag + size(v)
	}
	return n
}
func fieldMaskVarintLen[T ~int | ~int32 | ~int64 | ~uint32 | ~uint64](v T) int {
	return (bits.Len64(uint64(int64(v))|1) + fieldMaskVarintPayloadBits - 1) / fieldMaskVarintPayloadBits
}
func fieldMaskBytesLen[T ~string | ~[]byte](v T) int { return fieldMaskSizeLen(len(v)) }
func fieldMaskCopyUnknown(b []byte, i int, u []byte) int {
	if len(u) > 0 {
		i -= copy(b[i-len(u):], u)
	}
	return i
}
func fieldMaskAppendBinary(b []byte, size int, marshal func([]byte) (int, error)) ([]byte, error) {
	b = slices.Grow(b, size)
	n, err := marshal(b[len(b) : len(b)+size])
	if err == nil && n != size {
		err = errors.New("proto: message size changed during marshal")
	}
	if err != nil {
		return b, err
	}
	return b[:len(b)+size], nil
}
func fieldMaskPutVarint(b []byte, i int, u uint64) int {
	if u < fieldMaskVarintContBit {
		b[i-1] = byte(u)
		return i - 1
	}
	i -= (bits.Len64(u|1) + fieldMaskVarintPayloadBits - 1) / fieldMaskVarintPayloadBits
	binary.PutUvarint(b[i:], u)
	return i
}
func fieldMaskIf[T any](c bool, a, b T) T {
	if c {
		return a
	}
	return b
}
func fieldMaskDepth(depth int) error {
	if depth >= fieldMaskMaxDepth {
		return errors.New("proto: exceeded maximum recursion depth")
	}
	return nil
}
func fieldMaskReadBytes(b []byte) (v []byte, n int) {
	ln, k := binary.Uvarint(b)
	if k <= 0 || ln > uint64(len(b)-k) {
		return nil, -1
	}
	return b[k : k+int(ln)], k + int(ln)
}
func fieldMaskSkipField(b []byte, t uint64, depth int) (int, error) {
	n, num := 0, t>>fieldMaskTagTypeBits
	switch wt := t & fieldMaskTagTypeMask; {
	case num == 0 || num > fieldMaskMaxFieldNumber:
	case wt == fieldMaskWireVarint:
		_, n = binary.Uvarint(b)
	case wt == fieldMaskWireBytes:
		_, n = fieldMaskReadBytes(b)
	case wt == fieldMaskWireStartGroup:
		return fieldMaskSkipGroup(b, int32(num), depth+1)
	case wt == fieldMaskWireFixed64 || wt == fieldMaskWireFixed32:
		n = fieldMaskIf(wt == fieldMaskWireFixed64, fieldMaskFixed64Size, fieldMaskFixed32Size)
		n = fieldMaskIf(len(b) >= n, n, 0)
	}
	if n <= 0 {
		return 0, errors.New(fieldMaskE2)
	}
	return n, nil
}
func fieldMaskSkipGroup(b []byte, num int32, depth int) (int, error) {
	n, err := 0, fieldMaskDepth(depth)
	for err == nil {
		t, k := binary.Uvarint(b[n:])
		if k <= 0 {
			return 0, errors.New(fieldMaskE2)
		}
		if n += k; t == uint64(num)<<fieldMaskTagTypeBits|fieldMaskWireEndGroup {
			return n, nil
		}
		k, err = fieldMaskSkipField(b[n:], t, depth)
		n += k
	}
	return 0, err
}
func fieldMaskUnknown(b []byte, t uint64, depth int, unk *[]byte) (int, error) {
	n, err := fieldMaskSkipField(b, t, depth)
	if err == nil {
		*unk = append(binary.AppendUvarint(*unk, t), b[:n]...)
	}
	return n, err
}
func fieldMaskEnd(b []byte, err error) error {
	if err == nil && len(b) > 0 {
		return errors.New(fieldMaskE2)
	}
	return err
}
func fieldMaskString(b []byte, p *string, errUTF8 string) (int, error) {
	ln, k := binary.Uvarint(b)
	if k <= 0 || ln > uint64(len(b)-k) {
		return -1, nil
	}
	x := b[k : k+int(ln)]
	if errUTF8 != "" && !utf8.Valid(x) {
		return 0, errors.New(errUTF8)
	}
	*p = string(x)
	return k + int(ln), nil
}
func fieldMaskGrow[T any](s *[]T) *T { var z T; *s = append(*s, z); return &(*s)[len(*s)-1] }
func fieldMaskMarshalTo(e *jsontext.Encoder, f func([]byte) ([]byte, error)) error {
	b, err := f(e.AvailableBuffer())
	if err != nil {
		return err
	}
	return e.WriteValue(b)
}
func fieldMaskMergeJSON(b []byte, name string, merge func(*jsontext.Decoder) error) error {
	d := jsontext.NewDecoder(bytes.NewBuffer(b))
	if err := merge(d); err != nil {
		return err
	}
	if _, err := d.ReadToken(); err != io.EOF {
		return fieldMaskJSONError(name, "unexpected data after JSON value")
	}
	return nil
}
func fieldMaskMergeFrom(d *jsontext.Decoder, merge func(*jsontext.Decoder) error) error {
	d, err := fieldMaskStrictDecoder(d)
	return cmp.Or(err, merge(d))
}
func fieldMaskStrictDecoder(d *jsontext.Decoder) (*jsontext.Decoder, error) {
	if lax, _ := json.GetOption(d.Options(), jsontext.AllowInvalidUTF8); !lax {
		return d, nil
	}
	v, err := d.ReadValue()
	if err != nil {
		return d, err
	}
	return jsontext.NewDecoder(bytes.NewBuffer(v)), nil
}
func fieldMaskJSONError(name, msg string) error { return errors.New("proto: " + name + ": " + msg) }
