// Code generated by cotorp. DO NOT EDIT.
// source: google/protobuf/struct.proto

package wktpb

import (
	"bytes"
	"cmp"
	"encoding/binary"
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"io"
	"math"
	"math/bits"
	"slices"
	"strconv"
	"unicode/utf8"
)

// Wire types.
const (
	structWireVarint     = 0
	structWireFixed64    = 1
	structWireBytes      = 2
	structWireStartGroup = 3
	structWireEndGroup   = 4
	structWireFixed32    = 5
)

// A tag holds the field number above the wire type in its low three bits.
const (
	structTagTypeBits    = 3
	structTagTypeMask    = 1<<3 - 1
	structMaxFieldNumber = 1<<29 - 1
)

// Map entries are encoded as messages with these field numbers.
const (
	structMapKeyField   = 1
	structMapValueField = 2
)

// Encoded sizes.
const (
	structFixed32Size       = 4
	structFixed64Size       = 8
	structVarintPayloadBits = 7    // value bits per varint byte
	structVarintContBit     = 0x80 // set on every varint byte but the last
)

// Decoding limits.
const (
	structMaxDepth      = 10000 // maximum message and group nesting
	structSkipStackSize = 16    // group nesting tracked without allocating
)

// Error messages used more than once.
const (
	structStructFieldsEntryKeyErrUTF8 = "proto: field google.protobuf.Struct.FieldsEntry.key contains invalid UTF-8"
	structErrParse                    = "proto: cannot parse invalid wire-format data"
	structErrDepth                    = "proto: exceeded maximum recursion depth"
	structValueStringValueErrUTF8     = "proto: field google.protobuf.Value.string_value contains invalid UTF-8"
)

// Represents a JSON `null`.
//
// `NullValue` is a sentinel, using an enum with only one value to represent
// the null value for the `Value` type union.
//
// A field of type `NullValue` with any value other than `0` is considered
// invalid. Most ProtoJSON serializers will emit a `Value` with a `null_value`
// set as a JSON `null` regardless of the integer value, and so will round trip
// to a `0` value.
type NullValue int32

const (
	// Null value.
	NullValue_NULL_VALUE NullValue = 0
)

// NullValue_name maps NullValue numbers to their names.
var NullValue_name = map[int32]string{
	0: "NULL_VALUE",
}

// NullValue_value maps NullValue names to their numbers.
var NullValue_value = map[string]int32{
	"NULL_VALUE": 0,
}

// Enum returns a pointer to a copy of x.
func (x NullValue) Enum() *NullValue { return &x }

// String returns the name of x, or its number if it has no name.
func (x NullValue) String() string {
	if s, ok := NullValue_name[int32(x)]; ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// IsValid reports whether x is a declared value of NullValue.
func (x NullValue) IsValid() bool {
	switch x {
	case NullValue_NULL_VALUE:
		return true
	}
	return false
}

// Represents a JSON object.
//
// An unordered key-value map, intending to perfectly capture the semantics of a
// JSON object. This enables parsing any arbitrary JSON payload as a message
// field in ProtoJSON format.
//
// This follows RFC 8259 guidelines for interoperable JSON: notably this type
// cannot represent large Int64 values or `NaN`/`Infinity` numbers,
// since the JSON format generally does not support those values in its number
// type.
//
// If you do not intend to parse arbitrary JSON into your message, a custom
// typed message should be preferred instead of using this type.
type Struct struct {
	// Unordered map of dynamically typed values.
	Fields map[string]*Value

	unknownFields []byte
}

// Reset clears all fields of m.
func (m *Struct) Reset() { *m = Struct{} }

func (m *Struct) GetFields() map[string]*Value {
	if m != nil {
		return m.Fields
	}
	return nil
}

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *Struct) ProtoUnknownFields() []byte {
	if m == nil {
		return nil
	}
	return m.unknownFields
}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *Struct) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	for k, v := range m.Fields {
		_, _ = k, v
		lv := v.ProtoSize()
		l := 1 + len(k) + (bits.Len64(uint64(len(k))|1)+structVarintPayloadBits-1)/structVarintPayloadBits + 1 + lv + (bits.Len64(uint64(lv)|1)+structVarintPayloadBits-1)/structVarintPayloadBits
		n += 1 + l + (bits.Len64(uint64(l)|1)+structVarintPayloadBits-1)/structVarintPayloadBits
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *Struct) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// AppendBinary appends the wire-format encoding of m to b.
func (m *Struct) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	b = slices.Grow(b, size)
	n, err := m.ProtoMarshalToSizedBuffer(b[len(b) : len(b)+size])
	return structAppended(b, size, n, err)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *Struct) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if len(m.unknownFields) > 0 {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if len(m.Fields) > 0 {
		for _, k := range slices.Backward(structSortedKeys(m.Fields, make([]string, 0, len(m.Fields)))) {
			v := m.Fields[k]
			start := i
			n, err := v.ProtoMarshalToSizedBuffer(b[:i])
			if err != nil {
				return 0, err
			}
			i -= n
			i = structPutVarint(b, i, uint64(n))
			i = structPutVarint(b, i, structMapValueField<<structTagTypeBits|structWireBytes)
			if !utf8.ValidString(k) {
				return 0, errors.New(structStructFieldsEntryKeyErrUTF8)
			}
			i -= len(k)
			copy(b[i:], k)
			i = structPutVarint(b, i, uint64(len(k)))
			i = structPutVarint(b, i, structMapKeyField<<structTagTypeBits|structWireBytes)
			i = structPutVarint(b, i, uint64(start-i))
			i = structPutVarint(b, i, 1<<structTagTypeBits|structWireBytes)
		}
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *Struct) UnmarshalBinary(b []byte) error {
	*m = Struct{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *Struct) ProtoMerge(b []byte) error {
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *Struct) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= structMaxDepth {
		goto errDepth
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>structTagTypeBits == 0 || t>>structTagTypeBits > structMaxFieldNumber {
			goto errParse
		}
		start := b
		b = b[n:]
		switch t {
		case 1<<structTagTypeBits | structWireBytes:
			v, n := structReadBytes(b)
			if n < 0 {
				goto errParse
			}
			var mk string
			var mv *Value
			for len(v) > 0 {
				t, n := binary.Uvarint(v)
				if n <= 0 || t>>structTagTypeBits == 0 || t>>structTagTypeBits > structMaxFieldNumber {
					goto errParse
				}
				v = v[n:]
				switch t {
				case structMapKeyField<<structTagTypeBits | structWireBytes:
					x, n := structReadBytes(v)
					if n < 0 {
						goto errParse
					}
					if !utf8.Valid(x) {
						return errors.New(structStructFieldsEntryKeyErrUTF8)
					}
					mk = string(x)
					v = v[n:]
				case structMapValueField<<structTagTypeBits | structWireBytes:
					x, n := structReadBytes(v)
					if n < 0 {
						goto errParse
					}
					if mv == nil {
						mv = &Value{}
					}
					if err := mv.ProtoMergeDepth(x, depth+1); err != nil {
						return err
					}
					v = v[n:]
				default:
					n, err := structSkipField(v, t, depth)
					if err != nil {
						return err
					}
					v = v[n:]
				}
			}
			if mv == nil {
				mv = &Value{}
			}
			if m.Fields == nil {
				m.Fields = make(map[string]*Value)
			}
			m.Fields[mk] = mv
			b = b[n:]
		default:
			// Unknown field, or a known field with an unexpected wire type.
			n, err := structSkipField(b, t, depth)
			if err != nil {
				return err
			}
			m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
errParse:
	return errors.New(structErrParse)
errDepth:
	return errors.New(structErrDepth)
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *Struct) ProtoCheckInitialized() error {
	return nil
}

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *Struct) MarshalJSON() ([]byte, error) {
	return m.ProtoAppendJSON(nil)
}

// MarshalJSONTo writes the ProtoJSON encoding of m to e. It implements
// json.MarshalerTo from encoding/json/v2.
func (m *Struct) MarshalJSONTo(e *jsontext.Encoder) error {
	b, err := m.ProtoAppendJSON(e.AvailableBuffer())
	return structWriteJSON(e, b, err)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b. It does not
// check required fields.
func (m *Struct) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	b = append(b, '{')
	if m != nil {
		for _, k := range structSortedKeys(m.Fields, make([]string, 0, len(m.Fields))) {
			v := m.Fields[k]
			if b, err = jsontext.AppendQuote(b, k); err != nil {
				return nil, errors.New("proto: google.protobuf.Struct.fields contains invalid UTF-8")
			}
			b = append(b, ':')
			if b, err = v.ProtoAppendJSON(b); err != nil {
				return nil, err
			}
			b = append(b, ',')
		}
	}
	if b[len(b)-1] == ',' {
		b[len(b)-1] = '}'
	} else {
		b = append(b, '}')
	}
	return b, nil
}

// UnmarshalJSON replaces the contents of m with the decoded ProtoJSON
// value in b.
func (m *Struct) UnmarshalJSON(b []byte) error {
	*m = Struct{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m.
// It does not check required fields.
func (m *Struct) ProtoMergeJSON(b []byte) error {
	d := jsontext.NewDecoder(bytes.NewBuffer(b))
	return structEndJSON(d, m.ProtoMergeJSONFrom(d), "google.protobuf.Struct")
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value
// read from d. It implements json.UnmarshalerFrom from encoding/json/v2.
func (m *Struct) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	d, err := structStrictDecoder(d)
	if err != nil {
		return err
	}
	*m = Struct{}
	return m.ProtoMergeJSONFrom(d)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it
// into m. It does not check required fields. d should reject invalid
// UTF-8, as jsontext decoders do by default.
func (m *Struct) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	ok, err := structOpenJSON(d, jsontext.KindBeginObject, "google.protobuf.Struct", "object")
	if !ok {
		return err
	}
	for d.PeekKind() != jsontext.KindEndObject {
		kt, err := d.ReadToken()
		if err != nil {
			return err
		}
		mk := kt.String()
		k := mk
		mv := &Value{}
		if err := mv.ProtoMergeJSONFrom(d); err != nil {
			return err
		}
		if m.Fields == nil {
			m.Fields = make(map[string]*Value)
		}
		m.Fields[k] = mv
	}
	_, err = d.ReadToken()
	return err
}

// Represents a JSON value.
//
// `Value` represents a dynamically typed value which can be either
// null, a number, a string, a boolean, a recursive struct value, or a
// list of values. A producer of value is expected to set one of these
// variants. Absence of any variant is an invalid state.
type Value struct {
	// The kind of value.
	//
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_NullValue
	//	*Value_NumberValue
	//	*Value_StringValue
	//	*Value_BoolValue
	//	*Value_StructValue
	//	*Value_ListValue
	Kind isValue_Kind

	unknownFields []byte
}

// Reset clears all fields of m.
func (m *Value) Reset() { *m = Value{} }

func (m *Value) GetKind() isValue_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (m *Value) GetNullValue() NullValue {
	if x, ok := m.GetKind().(*Value_NullValue); ok {
		return x.NullValue
	}
	return NullValue_NULL_VALUE
}

func (m *Value) GetNumberValue() float64 {
	if x, ok := m.GetKind().(*Value_NumberValue); ok {
		return x.NumberValue
	}
	return 0
}

func (m *Value) GetStringValue() string {
	if x, ok := m.GetKind().(*Value_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *Value) GetBoolValue() bool {
	if x, ok := m.GetKind().(*Value_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (m *Value) GetStructValue() *Struct {
	if x, ok := m.GetKind().(*Value_StructValue); ok {
		return x.StructValue
	}
	return nil
}

func (m *Value) GetListValue() *ListValue {
	if x, ok := m.GetKind().(*Value_ListValue); ok {
		return x.ListValue
	}
	return nil
}

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *Value) ProtoUnknownFields() []byte {
	if m == nil {
		return nil
	}
	return m.unknownFields
}

type isValue_Kind interface {
	isValue_Kind()
}

// Represents a JSON `null`.
type Value_NullValue struct {
	NullValue NullValue
}

func (*Value_NullValue) isValue_Kind() {}

// Represents a JSON number. Must not be `NaN`, `Infinity` or
// `-Infinity`, since those are not supported in JSON. This also cannot
// represent large Int64 values, since JSON format generally does not
// support them in its number type.
type Value_NumberValue struct {
	NumberValue float64
}

func (*Value_NumberValue) isValue_Kind() {}

// Represents a JSON string.
type Value_StringValue struct {
	StringValue string
}

func (*Value_StringValue) isValue_Kind() {}

// Represents a JSON boolean (`true` or `false` literal in JSON).
type Value_BoolValue struct {
	BoolValue bool
}

func (*Value_BoolValue) isValue_Kind() {}

// Represents a JSON object.
type Value_StructValue struct {
	StructValue *Struct
}

func (*Value_StructValue) isValue_Kind() {}

// Represents a JSON array.
type Value_ListValue struct {
	ListValue *ListValue
}

func (*Value_ListValue) isValue_Kind() {}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *Value) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	switch o := m.Kind.(type) {
	case *Value_NullValue:
		n += 1 + (bits.Len64(uint64(int64(o.NullValue))|1)+structVarintPayloadBits-1)/structVarintPayloadBits
	case *Value_NumberValue:
		n += 1 + structFixed64Size
	case *Value_StringValue:
		n += 1 + len(o.StringValue) + (bits.Len64(uint64(len(o.StringValue))|1)+structVarintPayloadBits-1)/structVarintPayloadBits
	case *Value_BoolValue:
		n += 1 + 1
	case *Value_StructValue:
		l := o.StructValue.ProtoSize()
		n += 1 + l + (bits.Len64(uint64(l)|1)+structVarintPayloadBits-1)/structVarintPayloadBits
	case *Value_ListValue:
		l := o.ListValue.ProtoSize()
		n += 1 + l + (bits.Len64(uint64(l)|1)+structVarintPayloadBits-1)/structVarintPayloadBits
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *Value) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// AppendBinary appends the wire-format encoding of m to b.
func (m *Value) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	b = slices.Grow(b, size)
	n, err := m.ProtoMarshalToSizedBuffer(b[len(b) : len(b)+size])
	return structAppended(b, size, n, err)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *Value) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if len(m.unknownFields) > 0 {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if o, ok := m.Kind.(*Value_ListValue); ok {
		n, err := o.ListValue.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i -= n
		i = structPutVarint(b, i, uint64(n))
		i = structPutVarint(b, i, 6<<structTagTypeBits|structWireBytes)
	}
	if o, ok := m.Kind.(*Value_StructValue); ok {
		n, err := o.StructValue.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i -= n
		i = structPutVarint(b, i, uint64(n))
		i = structPutVarint(b, i, 5<<structTagTypeBits|structWireBytes)
	}
	if o, ok := m.Kind.(*Value_BoolValue); ok {
		i--
		if o.BoolValue {
			b[i] = 1
		} else {
			b[i] = 0
		}
		i = structPutVarint(b, i, 4<<structTagTypeBits|structWireVarint)
	}
	if o, ok := m.Kind.(*Value_StringValue); ok {
		if !utf8.ValidString(o.StringValue) {
			return 0, errors.New(structValueStringValueErrUTF8)
		}
		i -= len(o.StringValue)
		copy(b[i:], o.StringValue)
		i = structPutVarint(b, i, uint64(len(o.StringValue)))
		i = structPutVarint(b, i, 3<<structTagTypeBits|structWireBytes)
	}
	if o, ok := m.Kind.(*Value_NumberValue); ok {
		i -= structFixed64Size
		binary.LittleEndian.PutUint64(b[i:], math.Float64bits(o.NumberValue))
		i = structPutVarint(b, i, 2<<structTagTypeBits|structWireFixed64)
	}
	if o, ok := m.Kind.(*Value_NullValue); ok {
		i = structPutVarint(b, i, uint64(int64(o.NullValue)))
		i = structPutVarint(b, i, 1<<structTagTypeBits|structWireVarint)
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *Value) UnmarshalBinary(b []byte) error {
	*m = Value{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *Value) ProtoMerge(b []byte) error {
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *Value) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= structMaxDepth {
		goto errDepth
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>structTagTypeBits == 0 || t>>structTagTypeBits > structMaxFieldNumber {
			goto errParse
		}
		start := b
		b = b[n:]
		switch t {
		case 1<<structTagTypeBits | structWireVarint:
			x, n := binary.Uvarint(b)
			if n <= 0 {
				goto errParse
			}
			b = b[n:]
			m.Kind = &Value_NullValue{NullValue: NullValue(int32(x))}
		case 2<<structTagTypeBits | structWireFixed64:
			if len(b) < structFixed64Size {
				goto errParse
			}
			x, n := binary.LittleEndian.Uint64(b), structFixed64Size
			b = b[n:]
			m.Kind = &Value_NumberValue{NumberValue: math.Float64frombits(x)}
		case 3<<structTagTypeBits | structWireBytes:
			x, n := structReadBytes(b)
			if n < 0 {
				goto errParse
			}
			if !utf8.Valid(x) {
				return errors.New(structValueStringValueErrUTF8)
			}
			b = b[n:]
			m.Kind = &Value_StringValue{StringValue: string(x)}
		case 4<<structTagTypeBits | structWireVarint:
			x, n := binary.Uvarint(b)
			if n <= 0 {
				goto errParse
			}
			b = b[n:]
			m.Kind = &Value_BoolValue{BoolValue: x != 0}
		case 5<<structTagTypeBits | structWireBytes:
			v, n := structReadBytes(b)
			if n < 0 {
				goto errParse
			}
			var mv *Struct
			if o, ok := m.Kind.(*Value_StructValue); ok && o.StructValue != nil {
				mv = o.StructValue
			} else {
				mv = &Struct{}
				m.Kind = &Value_StructValue{StructValue: mv}
			}
			if err := mv.ProtoMergeDepth(v, depth+1); err != nil {
				return err
			}
			b = b[n:]
		case 6<<structTagTypeBits | structWireBytes:
			v, n := structReadBytes(b)
			if n < 0 {
				goto errParse
			}
			var mv *ListValue
			if o, ok := m.Kind.(*Value_ListValue); ok && o.ListValue != nil {
				mv = o.ListValue
			} else {
				mv = &ListValue{}
				m.Kind = &Value_ListValue{ListValue: mv}
			}
			if err := mv.ProtoMergeDepth(v, depth+1); err != nil {
				return err
			}
			b = b[n:]
		default:
			// Unknown field, or a known field with an unexpected wire type.
			n, err := structSkipField(b, t, depth)
			if err != nil {
				return err
			}
			m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
errParse:
	return errors.New(structErrParse)
errDepth:
	return errors.New(structErrDepth)
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *Value) ProtoCheckInitialized() error {
	return nil
}

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *Value) MarshalJSON() ([]byte, error) {
	return m.ProtoAppendJSON(nil)
}

// MarshalJSONTo writes the ProtoJSON encoding of m to e. It implements
// json.MarshalerTo from encoding/json/v2.
func (m *Value) MarshalJSONTo(e *jsontext.Encoder) error {
	b, err := m.ProtoAppendJSON(e.AvailableBuffer())
	return structWriteJSON(e, b, err)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b. It does not
// check required fields.
func (m *Value) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	if m == nil {
		return append(b, "null"...), nil
	}
	switch o := m.Kind.(type) {
	case *Value_NullValue:
		b = append(b, "null"...)
	case *Value_NumberValue:
		if math.IsNaN(o.NumberValue) || math.IsInf(o.NumberValue, 0) {
			return nil, errors.New("proto: google.protobuf.Value: number_value cannot be NaN or Infinity")
		}
		b = jsontext.AppendFloat(b, o.NumberValue, 64)
	case *Value_StringValue:
		if b, err = jsontext.AppendQuote(b, o.StringValue); err != nil {
			return nil, errors.New("proto: google.protobuf.Value.string_value contains invalid UTF-8")
		}
	case *Value_BoolValue:
		if o.BoolValue {
			b = append(b, "true"...)
		} else {
			b = append(b, "false"...)
		}
	case *Value_StructValue:
		if b, err = o.StructValue.ProtoAppendJSON(b); err != nil {
			return nil, err
		}
	case *Value_ListValue:
		if b, err = o.ListValue.ProtoAppendJSON(b); err != nil {
			return nil, err
		}
	default:
		return nil, errors.New("proto: google.protobuf.Value: no kind is set")
	}
	return b, nil
}

// UnmarshalJSON replaces the contents of m with the decoded ProtoJSON
// value in b.
func (m *Value) UnmarshalJSON(b []byte) error {
	*m = Value{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m.
// It does not check required fields.
func (m *Value) ProtoMergeJSON(b []byte) error {
	d := jsontext.NewDecoder(bytes.NewBuffer(b))
	return structEndJSON(d, m.ProtoMergeJSONFrom(d), "google.protobuf.Value")
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value
// read from d. It implements json.UnmarshalerFrom from encoding/json/v2.
func (m *Value) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	d, err := structStrictDecoder(d)
	if err != nil {
		return err
	}
	*m = Value{}
	return m.ProtoMergeJSONFrom(d)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it
// into m. It does not check required fields. d should reject invalid
// UTF-8, as jsontext decoders do by default.
func (m *Value) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	switch d.PeekKind() {
	case jsontext.KindNull:
		if err := d.SkipValue(); err != nil {
			return err
		}
		m.Kind = &Value_NullValue{}
	case jsontext.KindTrue, jsontext.KindFalse:
		tok, err := d.ReadToken()
		if err != nil {
			return err
		}
		m.Kind = &Value_BoolValue{BoolValue: tok.Bool()}
	case jsontext.KindString:
		tok, err := d.ReadToken()
		if err != nil {
			return err
		}
		m.Kind = &Value_StringValue{StringValue: tok.String()}
	case jsontext.KindBeginObject:
		x := &Struct{}
		if err := x.ProtoMergeJSONFrom(d); err != nil {
			return err
		}
		m.Kind = &Value_StructValue{StructValue: x}
	case jsontext.KindBeginArray:
		x := &ListValue{}
		if err := x.ProtoMergeJSONFrom(d); err != nil {
			return err
		}
		m.Kind = &Value_ListValue{ListValue: x}
	case jsontext.KindNumber:
		tok, err := d.ReadToken()
		if err != nil {
			return err
		}
		fv, err := strconv.ParseFloat(tok.String(), 64)
		if err != nil {
			return errors.New("proto: google.protobuf.Value: invalid number " + tok.String())
		}
		m.Kind = &Value_NumberValue{NumberValue: fv}
	default:
		// A syntax error, which the read reports.
		if _, err := d.ReadToken(); err != nil {
			return err
		}
		return errors.New("proto: google.protobuf.Value: invalid JSON")
	}
	return nil
}

// Represents a JSON array.
type ListValue struct {
	// Repeated field of dynamically typed values.
	Values []*Value

	unknownFields []byte
}

// Reset clears all fields of m.
func (m *ListValue) Reset() { *m = ListValue{} }

func (m *ListValue) GetValues() []*Value {
	if m != nil {
		return m.Values
	}
	return nil
}

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *ListValue) ProtoUnknownFields() []byte {
	if m == nil {
		return nil
	}
	return m.unknownFields
}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *ListValue) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	for _, v := range m.Values {
		l := v.ProtoSize()
		n += 1 + l + (bits.Len64(uint64(l)|1)+structVarintPayloadBits-1)/structVarintPayloadBits
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *ListValue) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// AppendBinary appends the wire-format encoding of m to b.
func (m *ListValue) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	b = slices.Grow(b, size)
	n, err := m.ProtoMarshalToSizedBuffer(b[len(b) : len(b)+size])
	return structAppended(b, size, n, err)
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *ListValue) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	if len(m.unknownFields) > 0 {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	for _, v := range slices.Backward(m.Values) {
		n, err := v.ProtoMarshalToSizedBuffer(b[:i])
		if err != nil {
			return 0, err
		}
		i -= n
		i = structPutVarint(b, i, uint64(n))
		i = structPutVarint(b, i, 1<<structTagTypeBits|structWireBytes)
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *ListValue) UnmarshalBinary(b []byte) error {
	*m = ListValue{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *ListValue) ProtoMerge(b []byte) error {
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *ListValue) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= structMaxDepth {
		goto errDepth
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>structTagTypeBits == 0 || t>>structTagTypeBits > structMaxFieldNumber {
			goto errParse
		}
		start := b
		b = b[n:]
		switch t {
		case 1<<structTagTypeBits | structWireBytes:
			v, n := structReadBytes(b)
			if n < 0 {
				goto errParse
			}
			mv := &Value{}
			m.Values = append(m.Values, mv)
			if err := mv.ProtoMergeDepth(v, depth+1); err != nil {
				return err
			}
			b = b[n:]
		default:
			// Unknown field, or a known field with an unexpected wire type.
			n, err := structSkipField(b, t, depth)
			if err != nil {
				return err
			}
			m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
			b = b[n:]
		}
	}
	return nil
errParse:
	return errors.New(structErrParse)
errDepth:
	return errors.New(structErrDepth)
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *ListValue) ProtoCheckInitialized() error {
	return nil
}

// MarshalJSON returns the ProtoJSON encoding of m.
func (m *ListValue) MarshalJSON() ([]byte, error) {
	return m.ProtoAppendJSON(nil)
}

// MarshalJSONTo writes the ProtoJSON encoding of m to e. It implements
// json.MarshalerTo from encoding/json/v2.
func (m *ListValue) MarshalJSONTo(e *jsontext.Encoder) error {
	b, err := m.ProtoAppendJSON(e.AvailableBuffer())
	return structWriteJSON(e, b, err)
}

// ProtoAppendJSON appends the ProtoJSON encoding of m to b. It does not
// check required fields.
func (m *ListValue) ProtoAppendJSON(b []byte) ([]byte, error) {
	var err error
	b = append(b, '[')
	if m != nil {
		for j := range m.Values {
			if b, err = m.Values[j].ProtoAppendJSON(b); err != nil {
				return nil, err
			}
			b = append(b, ',')
		}
	}
	if b[len(b)-1] == ',' {
		b[len(b)-1] = ']'
	} else {
		b = append(b, ']')
	}
	return b, nil
}

// UnmarshalJSON replaces the contents of m with the decoded ProtoJSON
// value in b.
func (m *ListValue) UnmarshalJSON(b []byte) error {
	*m = ListValue{}
	return m.ProtoMergeJSON(b)
}

// ProtoMergeJSON decodes the ProtoJSON value in b and merges it into m.
// It does not check required fields.
func (m *ListValue) ProtoMergeJSON(b []byte) error {
	d := jsontext.NewDecoder(bytes.NewBuffer(b))
	return structEndJSON(d, m.ProtoMergeJSONFrom(d), "google.protobuf.ListValue")
}

// UnmarshalJSONFrom replaces the contents of m with the ProtoJSON value
// read from d. It implements json.UnmarshalerFrom from encoding/json/v2.
func (m *ListValue) UnmarshalJSONFrom(d *jsontext.Decoder) error {
	d, err := structStrictDecoder(d)
	if err != nil {
		return err
	}
	*m = ListValue{}
	return m.ProtoMergeJSONFrom(d)
}

// ProtoMergeJSONFrom decodes one ProtoJSON value from d and merges it
// into m. It does not check required fields. d should reject invalid
// UTF-8, as jsontext decoders do by default.
func (m *ListValue) ProtoMergeJSONFrom(d *jsontext.Decoder) error {
	ok, err := structOpenJSON(d, jsontext.KindBeginArray, "google.protobuf.ListValue", "array")
	if !ok {
		return err
	}
	for d.PeekKind() != jsontext.KindEndArray {
		mv := &Value{}
		if err := mv.ProtoMergeJSONFrom(d); err != nil {
			return err
		}
		m.Values = append(m.Values, mv)
	}
	_, err = d.ReadToken()
	return err
}

// structPutVarint writes u as a varint ending at b[i] and returns the index of
// its first byte.
func structPutVarint(b []byte, i int, u uint64) int {
	if u < structVarintContBit {
		b[i-1] = byte(u)
		return i - 1
	}
	i -= (bits.Len64(u|1) + structVarintPayloadBits - 1) / structVarintPayloadBits
	binary.PutUvarint(b[i:], u)
	return i
}

// structReadBytes returns the length-delimited value at the start of b and the
// number of bytes it occupies, or n < 0 if it is malformed.
func structReadBytes(b []byte) (v []byte, n int) {
	ln, k := binary.Uvarint(b)
	if k <= 0 || ln > uint64(len(b)-k) {
		return nil, -1
	}
	return b[k : k+int(ln)], k + int(ln)
}

// structSkipField returns the length of the value at the start of b of a field
// with tag t, in a message nested depth levels deep.
func structSkipField(b []byte, t uint64, depth int) (int, error) {
	switch t & structTagTypeMask {
	case structWireVarint:
		if _, n := binary.Uvarint(b); n > 0 {
			return n, nil
		}
	case structWireFixed64:
		if len(b) >= structFixed64Size {
			return structFixed64Size, nil
		}
	case structWireBytes:
		if _, n := structReadBytes(b); n >= 0 {
			return n, nil
		}
	case structWireStartGroup:
		return structSkipGroup(b, int32(t>>structTagTypeBits), depth)
	case structWireFixed32:
		if len(b) >= structFixed32Size {
			return structFixed32Size, nil
		}
	}
	return 0, errors.New(structErrParse)
}

// structSkipGroup returns the length of the body of group num at the start of
// b, including its end-group tag, in a message nested depth levels deep.
// Nested groups are tracked with a small stack.
func structSkipGroup(b []byte, num int32, depth int) (int, error) {
	var stk [structSkipStackSize]int32
	open := append(stk[:0], num)
	n := 0
	for len(open) > 0 {
		if depth+len(open) > structMaxDepth {
			return 0, errors.New(structErrDepth)
		}
		t, k := binary.Uvarint(b[n:])
		if k <= 0 || t>>structTagTypeBits == 0 || t>>structTagTypeBits > structMaxFieldNumber {
			return 0, errors.New(structErrParse)
		}
		n += k
		switch t & structTagTypeMask {
		case structWireStartGroup:
			open = append(open, int32(t>>structTagTypeBits))
		case structWireEndGroup:
			if open[len(open)-1] != int32(t>>structTagTypeBits) {
				return 0, errors.New(structErrParse)
			}
			open = open[:len(open)-1]
		default:
			k, err := structSkipField(b[n:], t, depth)
			if err != nil {
				return 0, err
			}
			n += k
		}
	}
	return n, nil
}

// structAppended finishes AppendBinary: b has capacity for size more bytes,
// of which ProtoMarshalToSizedBuffer wrote n or failed with err.
func structAppended(b []byte, size, n int, err error) ([]byte, error) {
	if err == nil && n != size {
		err = errors.New("proto: message size changed during marshal")
	}
	if err != nil {
		return b, err
	}
	return b[:len(b)+size], nil
}

// structSortedKeys appends the keys of m to keys, which should be empty, and
// sorts them. The caller allocates keys, so that it can stay on the stack.
func structSortedKeys[K cmp.Ordered, V any](m map[K]V, keys []K) []K {
	for k := range m {
		keys = append(keys, k)
	}
	slices.Sort(keys)
	return keys
}

// structWriteJSON finishes MarshalJSONTo: it writes the JSON value b to e,
// unless producing b failed with err.
func structWriteJSON(e *jsontext.Encoder, b []byte, err error) error {
	if err != nil {
		return err
	}
	return e.WriteValue(b)
}

// structEndJSON finishes ProtoMergeJSON for message name: decoding one value
// from d failed with err, or d must have no more data.
func structEndJSON(d *jsontext.Decoder, err error, name string) error {
	if err != nil {
		return err
	}
	if _, err := d.ReadToken(); err != io.EOF {
		return structJSONError(name, "unexpected data after JSON value")
	}
	return nil
}

// structStrictDecoder returns d, or a strict decoder for the next value of d if d
// replaces invalid UTF-8 (as encoding/json's decoder does), which
// ProtoJSON rejects.
func structStrictDecoder(d *jsontext.Decoder) (*jsontext.Decoder, error) {
	if lax, _ := json.GetOption(d.Options(), jsontext.AllowInvalidUTF8); !lax {
		return d, nil
	}
	v, err := d.ReadValue()
	if err != nil {
		return nil, err
	}
	return jsontext.NewDecoder(bytes.NewBuffer(v)), nil
}

// structOpenJSON reads the first token of the value of message name, which
// must be of the given kind. It reports false if the value is null, which
// leaves the message unchanged, or on error.
func structOpenJSON(d *jsontext.Decoder, kind jsontext.Kind, name, what string) (bool, error) {
	if d.PeekKind() == jsontext.KindNull {
		return false, d.SkipValue()
	}
	err := structExpectJSON(d, kind, name, what)
	return err == nil, err
}

// structExpectJSON reads a token of the given kind, a JSON what, in message name.
func structExpectJSON(d *jsontext.Decoder, kind jsontext.Kind, name, what string) error {
	tok, err := d.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != kind {
		return structJSONError(name, "expected a JSON "+what)
	}
	return nil
}

// structJSONError returns an error about the ProtoJSON value of message name.
func structJSONError(name, msg string) error {
	return errors.New("proto: " + name + ": " + msg)
}
