// Code generated by cotorp. DO NOT EDIT.
// source: common/common.proto

package commonpb

import (
	"encoding/binary"
	"errors"
	"math/bits"
	"slices"
	"strconv"
	"unicode/utf8"
)

type Color int32

const (
	Color_COLOR_UNSPECIFIED Color = 0
	Color_COLOR_RED         Color = 1
	Color_COLOR_GREEN       Color = 2
	Color_COLOR_BLUE        Color = 3
)

// Color_name maps Color numbers to their names.
var Color_name = map[int32]string{
	0: "COLOR_UNSPECIFIED",
	1: "COLOR_RED",
	2: "COLOR_GREEN",
	3: "COLOR_BLUE",
}

// Color_value maps Color names to their numbers.
var Color_value = map[string]int32{
	"COLOR_UNSPECIFIED": 0,
	"COLOR_RED":         1,
	"COLOR_GREEN":       2,
	"COLOR_BLUE":        3,
}

// Enum returns a pointer to a copy of x.
func (x Color) Enum() *Color { return &x }

// String returns the name of x, or its number if it has no name.
func (x Color) String() string {
	if s, ok := Color_name[int32(x)]; ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// IsValid reports whether x is a declared value of Color.
func (x Color) IsValid() bool {
	switch x {
	case 0, 1, 2, 3:
		return true
	}
	return false
}

// Shared is a message referenced from other packages.
type Shared struct {
	Label string
	Value int64

	unknownFields []byte
}

// Reset clears all fields of m.
func (m *Shared) Reset() { *m = Shared{} }

func (m *Shared) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Shared) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

// ProtoUnknownFields returns the raw bytes of fields that were not
// recognized when m was decoded.
func (m *Shared) ProtoUnknownFields() []byte {
	if m == nil {
		return nil
	}
	return m.unknownFields
}

// ProtoSize returns the size of the wire-format encoding of m.
func (m *Shared) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	if len(m.Label) > 0 {
		n += 1 + len(m.Label) + (bits.Len64((uint64(len(m.Label)))|1)+6)/7
	}
	if m.Value != 0 {
		n += 1 + (bits.Len64((uint64(m.Value))|1)+6)/7
	}
	n += len(m.unknownFields)
	return n
}

// MarshalBinary returns the wire-format encoding of m.
func (m *Shared) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// AppendBinary appends the wire-format encoding of m to b.
func (m *Shared) AppendBinary(b []byte) ([]byte, error) {
	size := m.ProtoSize()
	l := len(b)
	b = slices.Grow(b, size)[:l+size]
	n, err := m.ProtoMarshalToSizedBuffer(b[l:])
	if err != nil {
		return b[:l], err
	}
	if n != size {
		return b[:l], errors.New("proto: message size changed during marshal")
	}
	return b, nil
}

// ProtoMarshalToSizedBuffer encodes m into the end of b, which must be
// at least m.ProtoSize() bytes long, and returns the number of bytes
// written. It does not check required fields.
func (m *Shared) ProtoMarshalToSizedBuffer(b []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(b)
	var u uint64
	if len(m.unknownFields) > 0 {
		i -= len(m.unknownFields)
		copy(b[i:], m.unknownFields)
	}
	if m.Value != 0 {
		u = uint64(m.Value)
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x10
	}
	if len(m.Label) > 0 {
		if !utf8.ValidString(m.Label) {
			return 0, errors.New("proto: field cotorp.test.common.Shared.label contains invalid UTF-8")
		}
		i -= len(m.Label)
		copy(b[i:], m.Label)
		u = uint64(len(m.Label))
		if u < 0x80 {
			i--
			b[i] = byte(u)
		} else {
			i -= (bits.Len64((u)|1) + 6) / 7
			binary.PutUvarint(b[i:], u)
		}
		i--
		b[i] = 0x0a
	}
	return len(b) - i, nil
}

// UnmarshalBinary replaces the contents of m with the decoded
// wire-format message in b.
func (m *Shared) UnmarshalBinary(b []byte) error {
	*m = Shared{}
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMerge decodes the wire-format message in b and merges it into m.
// It does not check required fields.
func (m *Shared) ProtoMerge(b []byte) error {
	return m.ProtoMergeDepth(b, 0)
}

// ProtoMergeDepth is ProtoMerge for a message nested depth levels deep.
func (m *Shared) ProtoMergeDepth(b []byte, depth int) error {
	if depth >= 10000 {
		goto errDepth
	}
	for len(b) > 0 {
		t, n := binary.Uvarint(b)
		if n <= 0 || t>>3 == 0 || t>>3 > 536870911 {
			goto errParse
		}
		num, typ := int32(t>>3), int(t&7)
		start := b
		b = b[n:]
		switch num {
		case 1:
			if typ == 2 {
				ln, n := binary.Uvarint(b)
				if n <= 0 || ln > uint64(len(b)-n) {
					goto errParse
				}
				x := b[n : n+int(ln)]
				n += int(ln)
				if !utf8.Valid(x) {
					return errors.New("proto: field cotorp.test.common.Shared.label contains invalid UTF-8")
				}
				b = b[n:]
				m.Label = string(x)
				continue
			}
		case 2:
			if typ == 0 {
				x, n := binary.Uvarint(b)
				if n <= 0 {
					goto errParse
				}
				b = b[n:]
				m.Value = int64(x)
				continue
			}
		}
		// Unknown field, or a known field with an unexpected wire type.
		switch typ {
		case 0:
			_, n = binary.Uvarint(b)
			if n <= 0 {
				goto errParse
			}
		case 1:
			if len(b) < 8 {
				goto errParse
			}
			n = 8
		case 2:
			ln, k := binary.Uvarint(b)
			if k <= 0 || ln > uint64(len(b)-k) {
				goto errParse
			}
			n = k + int(ln)
		case 3:
			var stk [16]int32
			open := append(stk[:0], num)
			n = 0
			for len(open) > 0 {
				if depth+len(open) > 10000 {
					goto errDepth
				}
				t, k := binary.Uvarint(b[n:])
				if k <= 0 || t>>3 == 0 || t>>3 > 536870911 {
					goto errParse
				}
				n += k
				switch t & 7 {
				case 0:
					_, k = binary.Uvarint(b[n:])
					if k <= 0 {
						goto errParse
					}
				case 1:
					k = 8
				case 2:
					ln, k2 := binary.Uvarint(b[n:])
					if k2 <= 0 || ln > uint64(len(b)-n-k2) {
						goto errParse
					}
					k = k2 + int(ln)
				case 3:
					open = append(open, int32(t>>3))
					k = 0
				case 4:
					if open[len(open)-1] != int32(t>>3) {
						goto errParse
					}
					open = open[:len(open)-1]
					k = 0
				case 5:
					k = 4
				default:
					goto errParse
				}
				if k > len(b)-n {
					goto errParse
				}
				n += k
			}
		case 5:
			if len(b) < 4 {
				goto errParse
			}
			n = 4
		default:
			goto errParse
		}
		m.unknownFields = append(m.unknownFields, start[:len(start)-len(b)+n]...)
		b = b[n:]
	}
	return nil
errParse:
	return errors.New("proto: cannot parse invalid wire-format data")
errDepth:
	return errors.New("proto: exceeded maximum recursion depth")
}

// ProtoCheckInitialized returns an error if any required field in m
// or its sub-messages is not set.
func (m *Shared) ProtoCheckInitialized() error {
	return nil
}
